//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class T_FeeInCase : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        T_Fee fn_FeeID;
        [Association(@"T_FeeInCaseReferencesT_Fee")]
        public T_Fee n_FeeID
        {
            get { return fn_FeeID; }
            set { SetPropertyValue<T_Fee>("n_FeeID", ref fn_FeeID, value); }
        }
        TCase_Base fn_CaseID;
        [Association(@"T_FeeInCaseReferencesTCase_Base")]
        public TCase_Base n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TCase_Base>("n_CaseID", ref fn_CaseID, value); }
        }
        int fn_ProcessID;
        [Indexed(Name = @"in_ProcessID_T_FeeInCase")]
        public int n_ProcessID
        {
            get { return fn_ProcessID; }
            set { SetPropertyValue<int>("n_ProcessID", ref fn_ProcessID, value); }
        }
        string fs_IsMainCase;
        [Size(1)]
        public string s_IsMainCase
        {
            get { return fs_IsMainCase; }
            set { SetPropertyValue<string>("s_IsMainCase", ref fs_IsMainCase, value); }
        }
        string fIsMainCase;
        [Size(1)]
        public string IsMainCase
        {
            get { return fIsMainCase; }
            set { SetPropertyValue<string>("IsMainCase", ref fIsMainCase, value); }
        }
        int fn_AnnualFeeID;
        public int n_AnnualFeeID
        {
            get { return fn_AnnualFeeID; }
            set { SetPropertyValue<int>("n_AnnualFeeID", ref fn_AnnualFeeID, value); }
        }
    }

}
