//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class T_Fee : XPLiteObject
    {
        int fn_FeeID;
        [Key(true)]
        public int n_FeeID
        {
            get { return fn_FeeID; }
            set { SetPropertyValue<int>("n_FeeID", ref fn_FeeID, value); }
        }
        int fn_FeeCodeID;
        public int n_FeeCodeID
        {
            get { return fn_FeeCodeID; }
            set { SetPropertyValue<int>("n_FeeCodeID", ref fn_FeeCodeID, value); }
        }
        string fs_Status;
        [Size(50)]
        public string s_Status
        {
            get { return fs_Status; }
            set { SetPropertyValue<string>("s_Status", ref fs_Status, value); }
        }
        string fs_PayMode;
        [Size(2)]
        public string s_PayMode
        {
            get { return fs_PayMode; }
            set { SetPropertyValue<string>("s_PayMode", ref fs_PayMode, value); }
        }
        string fs_StatusOrder;
        [Size(50)]
        public string s_StatusOrder
        {
            get { return fs_StatusOrder; }
            set { SetPropertyValue<string>("s_StatusOrder", ref fs_StatusOrder, value); }
        }
        int fn_ChargeCurrency;
        public int n_ChargeCurrency
        {
            get { return fn_ChargeCurrency; }
            set { SetPropertyValue<int>("n_ChargeCurrency", ref fn_ChargeCurrency, value); }
        }
        decimal fn_ChargeOFee;
        public decimal n_ChargeOFee
        {
            get { return fn_ChargeOFee; }
            set { SetPropertyValue<decimal>("n_ChargeOFee", ref fn_ChargeOFee, value); }
        }
        decimal fn_ChargeAFee;
        public decimal n_ChargeAFee
        {
            get { return fn_ChargeAFee; }
            set { SetPropertyValue<decimal>("n_ChargeAFee", ref fn_ChargeAFee, value); }
        }
        decimal fn_ChargeTFee;
        public decimal n_ChargeTFee
        {
            get { return fn_ChargeTFee; }
            set { SetPropertyValue<decimal>("n_ChargeTFee", ref fn_ChargeTFee, value); }
        }
        DateTime fdt_ChargeShldPayDate;
        public DateTime dt_ChargeShldPayDate
        {
            get { return fdt_ChargeShldPayDate; }
            set { SetPropertyValue<DateTime>("dt_ChargeShldPayDate", ref fdt_ChargeShldPayDate, value); }
        }
        DateTime fdt_ChargePayDate;
        public DateTime dt_ChargePayDate
        {
            get { return fdt_ChargePayDate; }
            set { SetPropertyValue<DateTime>("dt_ChargePayDate", ref fdt_ChargePayDate, value); }
        }
        int fn_OfficialCurrency;
        public int n_OfficialCurrency
        {
            get { return fn_OfficialCurrency; }
            set { SetPropertyValue<int>("n_OfficialCurrency", ref fn_OfficialCurrency, value); }
        }
        decimal fn_OfficialFee;
        public decimal n_OfficialFee
        {
            get { return fn_OfficialFee; }
            set { SetPropertyValue<decimal>("n_OfficialFee", ref fn_OfficialFee, value); }
        }
        string fs_OfficialDiscMark;
        [Size(1)]
        public string s_OfficialDiscMark
        {
            get { return fs_OfficialDiscMark; }
            set { SetPropertyValue<string>("s_OfficialDiscMark", ref fs_OfficialDiscMark, value); }
        }
        string fs_OfficialDiscStyle;
        [Size(1)]
        public string s_OfficialDiscStyle
        {
            get { return fs_OfficialDiscStyle; }
            set { SetPropertyValue<string>("s_OfficialDiscStyle", ref fs_OfficialDiscStyle, value); }
        }
        decimal fn_OfficialDiscount;
        public decimal n_OfficialDiscount
        {
            get { return fn_OfficialDiscount; }
            set { SetPropertyValue<decimal>("n_OfficialDiscount", ref fn_OfficialDiscount, value); }
        }
        DateTime fdt_OfficialShldPayDate;
        public DateTime dt_OfficialShldPayDate
        {
            get { return fdt_OfficialShldPayDate; }
            set { SetPropertyValue<DateTime>("dt_OfficialShldPayDate", ref fdt_OfficialShldPayDate, value); }
        }
        DateTime fdt_OfficialPayDate;
        public DateTime dt_OfficialPayDate
        {
            get { return fdt_OfficialPayDate; }
            set { SetPropertyValue<DateTime>("dt_OfficialPayDate", ref fdt_OfficialPayDate, value); }
        }
        string fs_OfficialReceiptPath;
        [Size(500)]
        public string s_OfficialReceiptPath
        {
            get { return fs_OfficialReceiptPath; }
            set { SetPropertyValue<string>("s_OfficialReceiptPath", ref fs_OfficialReceiptPath, value); }
        }
        int fn_PayFeeListID;
        public int n_PayFeeListID
        {
            get { return fn_PayFeeListID; }
            set { SetPropertyValue<int>("n_PayFeeListID", ref fn_PayFeeListID, value); }
        }
        string fs_Notes;
        [Size(800)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
        string fs_InvoiceNum;
        [Size(50)]
        public string s_InvoiceNum
        {
            get { return fs_InvoiceNum; }
            set { SetPropertyValue<string>("s_InvoiceNum", ref fs_InvoiceNum, value); }
        }
        decimal fn_Rate;
        public decimal n_Rate
        {
            get { return fn_Rate; }
            set { SetPropertyValue<decimal>("n_Rate", ref fn_Rate, value); }
        }
        string fs_IsActive;
        [Size(1)]
        public string s_IsActive
        {
            get { return fs_IsActive; }
            set { SetPropertyValue<string>("s_IsActive", ref fs_IsActive, value); }
        }
        DateTime fdt_CreateDate;
        public DateTime dt_CreateDate
        {
            get { return fdt_CreateDate; }
            set { SetPropertyValue<DateTime>("dt_CreateDate", ref fdt_CreateDate, value); }
        }
        DateTime fdt_EditDate;
        public DateTime dt_EditDate
        {
            get { return fdt_EditDate; }
            set { SetPropertyValue<DateTime>("dt_EditDate", ref fdt_EditDate, value); }
        }
        string fs_FeePaymentStatue;
        public string s_FeePaymentStatue
        {
            get { return fs_FeePaymentStatue; }
            set { SetPropertyValue<string>("s_FeePaymentStatue", ref fs_FeePaymentStatue, value); }
        }
        string fs_FeeReceiveCashStatue;
        public string s_FeeReceiveCashStatue
        {
            get { return fs_FeeReceiveCashStatue; }
            set { SetPropertyValue<string>("s_FeeReceiveCashStatue", ref fs_FeeReceiveCashStatue, value); }
        }
        int fn_ExchangeCurrency;
        public int n_ExchangeCurrency
        {
            get { return fn_ExchangeCurrency; }
            set { SetPropertyValue<int>("n_ExchangeCurrency", ref fn_ExchangeCurrency, value); }
        }
        int fn_CameFileID;
        public int n_CameFileID
        {
            get { return fn_CameFileID; }
            set { SetPropertyValue<int>("n_CameFileID", ref fn_CameFileID, value); }
        }
        string fs_ChargeFeeName;
        [Size(500)]
        public string s_ChargeFeeName
        {
            get { return fs_ChargeFeeName; }
            set { SetPropertyValue<string>("s_ChargeFeeName", ref fs_ChargeFeeName, value); }
        }
        string fs_OfficialFeeName;
        [Size(500)]
        public string s_OfficialFeeName
        {
            get { return fs_OfficialFeeName; }
            set { SetPropertyValue<string>("s_OfficialFeeName", ref fs_OfficialFeeName, value); }
        }
        string fs_FeeName;
        [Size(200)]
        public string s_FeeName
        {
            get { return fs_FeeName; }
            set { SetPropertyValue<string>("s_FeeName", ref fs_FeeName, value); }
        }
        string fs_ProcessMark;
        [Size(10)]
        public string s_ProcessMark
        {
            get { return fs_ProcessMark; }
            set { SetPropertyValue<string>("s_ProcessMark", ref fs_ProcessMark, value); }
        }
        int fn_Asker;
        public int n_Asker
        {
            get { return fn_Asker; }
            set { SetPropertyValue<int>("n_Asker", ref fn_Asker, value); }
        }
        DateTime fdt_AskDate;
        public DateTime dt_AskDate
        {
            get { return fdt_AskDate; }
            set { SetPropertyValue<DateTime>("dt_AskDate", ref fdt_AskDate, value); }
        }
        int fn_Checker;
        public int n_Checker
        {
            get { return fn_Checker; }
            set { SetPropertyValue<int>("n_Checker", ref fn_Checker, value); }
        }
        DateTime fdt_CheckDate;
        public DateTime dt_CheckDate
        {
            get { return fdt_CheckDate; }
            set { SetPropertyValue<DateTime>("dt_CheckDate", ref fdt_CheckDate, value); }
        }
        int fn_Payer;
        public int n_Payer
        {
            get { return fn_Payer; }
            set { SetPropertyValue<int>("n_Payer", ref fn_Payer, value); }
        }
        DateTime fdt_PayDate;
        public DateTime dt_PayDate
        {
            get { return fdt_PayDate; }
            set { SetPropertyValue<DateTime>("dt_PayDate", ref fdt_PayDate, value); }
        }
        int fn_Receipter;
        public int n_Receipter
        {
            get { return fn_Receipter; }
            set { SetPropertyValue<int>("n_Receipter", ref fn_Receipter, value); }
        }
        DateTime fdt_ReceiptDate;
        public DateTime dt_ReceiptDate
        {
            get { return fdt_ReceiptDate; }
            set { SetPropertyValue<DateTime>("dt_ReceiptDate", ref fdt_ReceiptDate, value); }
        }
        string fs_ReceiptNo;
        [Size(200)]
        public string s_ReceiptNo
        {
            get { return fs_ReceiptNo; }
            set { SetPropertyValue<string>("s_ReceiptNo", ref fs_ReceiptNo, value); }
        }
        string fs_ProcessNote;
        [Size(800)]
        public string s_ProcessNote
        {
            get { return fs_ProcessNote; }
            set { SetPropertyValue<string>("s_ProcessNote", ref fs_ProcessNote, value); }
        }
        string fs_CaseSerial;
        public string s_CaseSerial
        {
            get { return fs_CaseSerial; }
            set { SetPropertyValue<string>("s_CaseSerial", ref fs_CaseSerial, value); }
        }
        string fs_ClientContacts;
        [Size(1000)]
        public string s_ClientContacts
        {
            get { return fs_ClientContacts; }
            set { SetPropertyValue<string>("s_ClientContacts", ref fs_ClientContacts, value); }
        }
        string fs_AppNo;
        public string s_AppNo
        {
            get { return fs_AppNo; }
            set { SetPropertyValue<string>("s_AppNo", ref fs_AppNo, value); }
        }
        DateTime fdt_AppDate;
        public DateTime dt_AppDate
        {
            get { return fdt_AppDate; }
            set { SetPropertyValue<DateTime>("dt_AppDate", ref fdt_AppDate, value); }
        }
        string fs_Applicants;
        [Size(1000)]
        public string s_Applicants
        {
            get { return fs_Applicants; }
            set { SetPropertyValue<string>("s_Applicants", ref fs_Applicants, value); }
        }
        string fs_Introducer;
        [Size(300)]
        public string s_Introducer
        {
            get { return fs_Introducer; }
            set { SetPropertyValue<string>("s_Introducer", ref fs_Introducer, value); }
        }
        string fs_Attorney;
        [Size(200)]
        public string s_Attorney
        {
            get { return fs_Attorney; }
            set { SetPropertyValue<string>("s_Attorney", ref fs_Attorney, value); }
        }
        int fn_PatentTypeID;
        public int n_PatentTypeID
        {
            get { return fn_PatentTypeID; }
            set { SetPropertyValue<int>("n_PatentTypeID", ref fn_PatentTypeID, value); }
        }
        int fn_FBillListID;
        public int n_FBillListID
        {
            get { return fn_FBillListID; }
            set { SetPropertyValue<int>("n_FBillListID", ref fn_FBillListID, value); }
        }
        bool fn_BonusCalced;
        public bool n_BonusCalced
        {
            get { return fn_BonusCalced; }
            set { SetPropertyValue<bool>("n_BonusCalced", ref fn_BonusCalced, value); }
        }
        string fs_Creator;
        [Size(50)]
        public string s_Creator
        {
            get { return fs_Creator; }
            set { SetPropertyValue<string>("s_Creator", ref fs_Creator, value); }
        }
        string fs_Editor;
        [Size(50)]
        public string s_Editor
        {
            get { return fs_Editor; }
            set { SetPropertyValue<string>("s_Editor", ref fs_Editor, value); }
        }
        int fn_ExpenseID;
        public int n_ExpenseID
        {
            get { return fn_ExpenseID; }
            set { SetPropertyValue<int>("n_ExpenseID", ref fn_ExpenseID, value); }
        }
        char fs_BonusFeeType;
        public char s_BonusFeeType
        {
            get { return fs_BonusFeeType; }
            set { SetPropertyValue<char>("s_BonusFeeType", ref fs_BonusFeeType, value); }
        }
        int fn_MainCaseID;
        public int n_MainCaseID
        {
            get { return fn_MainCaseID; }
            set { SetPropertyValue<int>("n_MainCaseID", ref fn_MainCaseID, value); }
        }
        string fs_ChargeNativeName;
        [Size(500)]
        public string s_ChargeNativeName
        {
            get { return fs_ChargeNativeName; }
            set { SetPropertyValue<string>("s_ChargeNativeName", ref fs_ChargeNativeName, value); }
        }
        string fs_OfficialNativeName;
        [Size(500)]
        public string s_OfficialNativeName
        {
            get { return fs_OfficialNativeName; }
            set { SetPropertyValue<string>("s_OfficialNativeName", ref fs_OfficialNativeName, value); }
        }
        string fs_ReviewStatus;
        [Size(2)]
        public string s_ReviewStatus
        {
            get { return fs_ReviewStatus; }
            set { SetPropertyValue<string>("s_ReviewStatus", ref fs_ReviewStatus, value); }
        }
        decimal fn_moreUnitCount;
        public decimal n_moreUnitCount
        {
            get { return fn_moreUnitCount; }
            set { SetPropertyValue<decimal>("n_moreUnitCount", ref fn_moreUnitCount, value); }
        }
        string fs_feeBeyondItemUnit;
        [Size(10)]
        public string s_feeBeyondItemUnit
        {
            get { return fs_feeBeyondItemUnit; }
            set { SetPropertyValue<string>("s_feeBeyondItemUnit", ref fs_feeBeyondItemUnit, value); }
        }
        decimal fn_ChargeDiscountAFeeRate;
        public decimal n_ChargeDiscountAFeeRate
        {
            get { return fn_ChargeDiscountAFeeRate; }
            set { SetPropertyValue<decimal>("n_ChargeDiscountAFeeRate", ref fn_ChargeDiscountAFeeRate, value); }
        }
        decimal fn_OriAgencyFee;
        public decimal n_OriAgencyFee
        {
            get { return fn_OriAgencyFee; }
            set { SetPropertyValue<decimal>("n_OriAgencyFee", ref fn_OriAgencyFee, value); }
        }
        string fs_TransLateFeeDiscountType;
        public string s_TransLateFeeDiscountType
        {
            get { return fs_TransLateFeeDiscountType; }
            set { SetPropertyValue<string>("s_TransLateFeeDiscountType", ref fs_TransLateFeeDiscountType, value); }
        }
        decimal fn_OriTransLateCount;
        public decimal n_OriTransLateCount
        {
            get { return fn_OriTransLateCount; }
            set { SetPropertyValue<decimal>("n_OriTransLateCount", ref fn_OriTransLateCount, value); }
        }
        int fn_CreatorID;
        public int n_CreatorID
        {
            get { return fn_CreatorID; }
            set { SetPropertyValue<int>("n_CreatorID", ref fn_CreatorID, value); }
        }
        string fs_CheckStatus;
        [Size(1)]
        public string s_CheckStatus
        {
            get { return fs_CheckStatus; }
            set { SetPropertyValue<string>("s_CheckStatus", ref fs_CheckStatus, value); }
        }
        int fn_BillID;
        [Indexed(Name = @"in_BillID_T_Fee")]
        public int n_BillID
        {
            get { return fn_BillID; }
            set { SetPropertyValue<int>("n_BillID", ref fn_BillID, value); }
        }
        string fs_FeeMode;
        [Size(1)]
        public string s_FeeMode
        {
            get { return fs_FeeMode; }
            set { SetPropertyValue<string>("s_FeeMode", ref fs_FeeMode, value); }
        }
        string fs_ElecPayer;
        public string s_ElecPayer
        {
            get { return fs_ElecPayer; }
            set { SetPropertyValue<string>("s_ElecPayer", ref fs_ElecPayer, value); }
        }
        string fs_ChargingCheckStatus;
        [Size(1)]
        public string s_ChargingCheckStatus
        {
            get { return fs_ChargingCheckStatus; }
            set { SetPropertyValue<string>("s_ChargingCheckStatus", ref fs_ChargingCheckStatus, value); }
        }
        int fn_ChargingChecker;
        public int n_ChargingChecker
        {
            get { return fn_ChargingChecker; }
            set { SetPropertyValue<int>("n_ChargingChecker", ref fn_ChargingChecker, value); }
        }
        DateTime fdt_ChargingCheckDate;
        public DateTime dt_ChargingCheckDate
        {
            get { return fdt_ChargingCheckDate; }
            set { SetPropertyValue<DateTime>("dt_ChargingCheckDate", ref fdt_ChargingCheckDate, value); }
        }
        string fs_ChargingNotes;
        [Size(800)]
        public string s_ChargingNotes
        {
            get { return fs_ChargingNotes; }
            set { SetPropertyValue<string>("s_ChargingNotes", ref fs_ChargingNotes, value); }
        }
        [Association(@"T_FeeInCaseReferencesT_Fee")]
        public XPCollection<T_FeeInCase> T_FeeInCases { get { return GetCollection<T_FeeInCase>("T_FeeInCases"); } }
    }

}
