//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class T_FileInCase : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        T_MainFiles fn_FileID;
        [Association(@"T_FileInCaseReferencesT_MainFiles")]
        public T_MainFiles n_FileID
        {
            get { return fn_FileID; }
            set { SetPropertyValue<T_MainFiles>("n_FileID", ref fn_FileID, value); }
        }
        TCase_Base fn_CaseID;
        [Association(@"T_FileInCaseReferencesTCase_Base")]
        public TCase_Base n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TCase_Base>("n_CaseID", ref fn_CaseID, value); }
        }
        int fn_ProcessID;
        [Indexed(Name = @"in_ProcessID_T_FileInCase")]
        public int n_ProcessID
        {
            get { return fn_ProcessID; }
            set { SetPropertyValue<int>("n_ProcessID", ref fn_ProcessID, value); }
        }
        string fs_IsMainCase;
        [Size(1)]
        public string s_IsMainCase
        {
            get { return fs_IsMainCase; }
            set { SetPropertyValue<string>("s_IsMainCase", ref fs_IsMainCase, value); }
        }
        string fs_SelectType;
        [Size(1)]
        public string s_SelectType
        {
            get { return fs_SelectType; }
            set { SetPropertyValue<string>("s_SelectType", ref fs_SelectType, value); }
        }
        string fs_MaterialType;
        [Size(50)]
        public string s_MaterialType
        {
            get { return fs_MaterialType; }
            set { SetPropertyValue<string>("s_MaterialType", ref fs_MaterialType, value); }
        }
        int fn_AnnualFeeID;
        public int n_AnnualFeeID
        {
            get { return fn_AnnualFeeID; }
            set { SetPropertyValue<int>("n_AnnualFeeID", ref fn_AnnualFeeID, value); }
        }
    }

}
