//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class T_InFiles : T_MainFiles
    {
        int fn_FileCodeID;
        public int n_FileCodeID
        {
            get { return fn_FileCodeID; }
            set { SetPropertyValue<int>("n_FileCodeID", ref fn_FileCodeID, value); }
        }
        string fs_FileType;
        [Size(50)]
        public string s_FileType
        {
            get { return fs_FileType; }
            set { SetPropertyValue<string>("s_FileType", ref fs_FileType, value); }
        }
        int fn_GovOfficeID;
        public int n_GovOfficeID
        {
            get { return fn_GovOfficeID; }
            set { SetPropertyValue<int>("n_GovOfficeID", ref fn_GovOfficeID, value); }
        }
        string fs_Officer;
        [Size(50)]
        public string s_Officer
        {
            get { return fs_Officer; }
            set { SetPropertyValue<string>("s_Officer", ref fs_Officer, value); }
        }
        string fs_OfficialNO;
        [Size(50)]
        public string s_OfficialNO
        {
            get { return fs_OfficialNO; }
            set { SetPropertyValue<string>("s_OfficialNO", ref fs_OfficialNO, value); }
        }
        string fs_OFileStatus;
        [Size(1)]
        public string s_OFileStatus
        {
            get { return fs_OFileStatus; }
            set { SetPropertyValue<string>("s_OFileStatus", ref fs_OFileStatus, value); }
        }
        string fs_NeedTransfer;
        [Size(1)]
        public string s_NeedTransfer
        {
            get { return fs_NeedTransfer; }
            set { SetPropertyValue<string>("s_NeedTransfer", ref fs_NeedTransfer, value); }
        }
        string fs_Lock;
        [Size(1)]
        public string s_Lock
        {
            get { return fs_Lock; }
            set { SetPropertyValue<string>("s_Lock", ref fs_Lock, value); }
        }
        string fs_Locker;
        [Size(50)]
        public string s_Locker
        {
            get { return fs_Locker; }
            set { SetPropertyValue<string>("s_Locker", ref fs_Locker, value); }
        }
        int fn_AgencyOfficeID;
        public int n_AgencyOfficeID
        {
            get { return fn_AgencyOfficeID; }
            set { SetPropertyValue<int>("n_AgencyOfficeID", ref fn_AgencyOfficeID, value); }
        }
        DateTime fdt_TransmitDate;
        public DateTime dt_TransmitDate
        {
            get { return fdt_TransmitDate; }
            set { SetPropertyValue<DateTime>("dt_TransmitDate", ref fdt_TransmitDate, value); }
        }
        string fs_GetCertificater;
        [Size(200)]
        public string s_GetCertificater
        {
            get { return fs_GetCertificater; }
            set { SetPropertyValue<string>("s_GetCertificater", ref fs_GetCertificater, value); }
        }
        DateTime fdt_GetCertificatedate;
        public DateTime dt_GetCertificatedate
        {
            get { return fdt_GetCertificatedate; }
            set { SetPropertyValue<DateTime>("dt_GetCertificatedate", ref fdt_GetCertificatedate, value); }
        }
        string fs_Distribute;
        [Size(1)]
        public string s_Distribute
        {
            get { return fs_Distribute; }
            set { SetPropertyValue<string>("s_Distribute", ref fs_Distribute, value); }
        }
        string fs_Note;
        [Size(500)]
        public string s_Note
        {
            get { return fs_Note; }
            set { SetPropertyValue<string>("s_Note", ref fs_Note, value); }
        }
        string fs_Urgent;
        [Size(2)]
        public string s_Urgent
        {
            get { return fs_Urgent; }
            set { SetPropertyValue<string>("s_Urgent", ref fs_Urgent, value); }
        }
        int fn_ParentID;
        public int n_ParentID
        {
            get { return fn_ParentID; }
            set { SetPropertyValue<int>("n_ParentID", ref fn_ParentID, value); }
        }
        string fs_IsPreChange;
        [Size(1)]
        public string s_IsPreChange
        {
            get { return fs_IsPreChange; }
            set { SetPropertyValue<string>("s_IsPreChange", ref fs_IsPreChange, value); }
        }
    }

}
