//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TCase_Base : XPLiteObject
    {
        int fn_CaseID;
        [Key(true)]
        public int n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<int>("n_CaseID", ref fn_CaseID, value); }
        }
        string fs_IPType;
        [Size(1)]
        public string s_IPType
        {
            get { return fs_IPType; }
            set { SetPropertyValue<string>("s_IPType", ref fs_IPType, value); }
        }
        string fs_CaseSerial;
        [Size(50)]
        public string s_CaseSerial
        {
            get { return fs_CaseSerial; }
            set { SetPropertyValue<string>("s_CaseSerial", ref fs_CaseSerial, value); }
        }
        int fn_FlowNum;
        public int n_FlowNum
        {
            get { return fn_FlowNum; }
            set { SetPropertyValue<int>("n_FlowNum", ref fn_FlowNum, value); }
        }
        string fs_CaseName;
        [Size(500)]
        public string s_CaseName
        {
            get { return fs_CaseName; }
            set { SetPropertyValue<string>("s_CaseName", ref fs_CaseName, value); }
        }
        string fs_CaseOtherName;
        [Size(500)]
        public string s_CaseOtherName
        {
            get { return fs_CaseOtherName; }
            set { SetPropertyValue<string>("s_CaseOtherName", ref fs_CaseOtherName, value); }
        }
        int fn_BusinessTypeID;
        public int n_BusinessTypeID
        {
            get { return fn_BusinessTypeID; }
            set { SetPropertyValue<int>("n_BusinessTypeID", ref fn_BusinessTypeID, value); }
        }
        string fs_FlowDirection;
        [Size(2)]
        public string s_FlowDirection
        {
            get { return fs_FlowDirection; }
            set { SetPropertyValue<string>("s_FlowDirection", ref fs_FlowDirection, value); }
        }
        int fn_FirstAttorney;
        public int n_FirstAttorney
        {
            get { return fn_FirstAttorney; }
            set { SetPropertyValue<int>("n_FirstAttorney", ref fn_FirstAttorney, value); }
        }
        int fn_SecondAttorney;
        public int n_SecondAttorney
        {
            get { return fn_SecondAttorney; }
            set { SetPropertyValue<int>("n_SecondAttorney", ref fn_SecondAttorney, value); }
        }
        int fn_OfficeID;
        public int n_OfficeID
        {
            get { return fn_OfficeID; }
            set { SetPropertyValue<int>("n_OfficeID", ref fn_OfficeID, value); }
        }
        int fn_RegCountry;
        public int n_RegCountry
        {
            get { return fn_RegCountry; }
            set { SetPropertyValue<int>("n_RegCountry", ref fn_RegCountry, value); }
        }
        TCstmr_CoopAgency fn_CoopAgencyFromID;
        [Association(@"TCase_BaseReferencesTCstmr_CoopAgency")]
        public TCstmr_CoopAgency n_CoopAgencyFromID
        {
            get { return fn_CoopAgencyFromID; }
            set { SetPropertyValue<TCstmr_CoopAgency>("n_CoopAgencyFromID", ref fn_CoopAgencyFromID, value); }
        }
        TCstmr_CoopAgency fn_CoopAgencyToID;
        [Association(@"TCase_BaseReferencesTCstmr_CoopAgency1")]
        public TCstmr_CoopAgency n_CoopAgencyToID
        {
            get { return fn_CoopAgencyToID; }
            set { SetPropertyValue<TCstmr_CoopAgency>("n_CoopAgencyToID", ref fn_CoopAgencyToID, value); }
        }
        string fs_CoopAgencyFromNo;
        [Size(50)]
        public string s_CoopAgencyFromNo
        {
            get { return fs_CoopAgencyFromNo; }
            set { SetPropertyValue<string>("s_CoopAgencyFromNo", ref fs_CoopAgencyFromNo, value); }
        }
        string fs_CoopAgencyToNo;
        [Size(50)]
        public string s_CoopAgencyToNo
        {
            get { return fs_CoopAgencyToNo; }
            set { SetPropertyValue<string>("s_CoopAgencyToNo", ref fs_CoopAgencyToNo, value); }
        }
        TCstmr_Client fn_ClientID;
        [Association(@"TCase_BaseReferencesTCstmr_Client")]
        public TCstmr_Client n_ClientID
        {
            get { return fn_ClientID; }
            set { SetPropertyValue<TCstmr_Client>("n_ClientID", ref fn_ClientID, value); }
        }
        string fs_ClientSerial;
        public string s_ClientSerial
        {
            get { return fs_ClientSerial; }
            set { SetPropertyValue<string>("s_ClientSerial", ref fs_ClientSerial, value); }
        }
        int fn_IntroID;
        [Indexed(Name = @"in_IntroID_TCase_Base")]
        public int n_IntroID
        {
            get { return fn_IntroID; }
            set { SetPropertyValue<int>("n_IntroID", ref fn_IntroID, value); }
        }
        decimal fn_IntroFee;
        public decimal n_IntroFee
        {
            get { return fn_IntroFee; }
            set { SetPropertyValue<decimal>("n_IntroFee", ref fn_IntroFee, value); }
        }
        int fn_IntroCurrency;
        public int n_IntroCurrency
        {
            get { return fn_IntroCurrency; }
            set { SetPropertyValue<int>("n_IntroCurrency", ref fn_IntroCurrency, value); }
        }
        string fs_IntroSerial;
        [Size(50)]
        public string s_IntroSerial
        {
            get { return fs_IntroSerial; }
            set { SetPropertyValue<string>("s_IntroSerial", ref fs_IntroSerial, value); }
        }
        DateTime fdt_UndertakeDate;
        public DateTime dt_UndertakeDate
        {
            get { return fdt_UndertakeDate; }
            set { SetPropertyValue<DateTime>("dt_UndertakeDate", ref fdt_UndertakeDate, value); }
        }
        DateTime fdt_ShldSbmtDate;
        public DateTime dt_ShldSbmtDate
        {
            get { return fdt_ShldSbmtDate; }
            set { SetPropertyValue<DateTime>("dt_ShldSbmtDate", ref fdt_ShldSbmtDate, value); }
        }
        DateTime fdt_SubmitDate;
        public DateTime dt_SubmitDate
        {
            get { return fdt_SubmitDate; }
            set { SetPropertyValue<DateTime>("dt_SubmitDate", ref fdt_SubmitDate, value); }
        }
        string fs_CaseStatus;
        [Size(50)]
        public string s_CaseStatus
        {
            get { return fs_CaseStatus; }
            set { SetPropertyValue<string>("s_CaseStatus", ref fs_CaseStatus, value); }
        }
        string fs_FeeMode;
        [Size(1)]
        public string s_FeeMode
        {
            get { return fs_FeeMode; }
            set { SetPropertyValue<string>("s_FeeMode", ref fs_FeeMode, value); }
        }
        decimal fn_FeeDiscount;
        public decimal n_FeeDiscount
        {
            get { return fn_FeeDiscount; }
            set { SetPropertyValue<decimal>("n_FeeDiscount", ref fn_FeeDiscount, value); }
        }
        decimal fn_FixAFee;
        public decimal n_FixAFee
        {
            get { return fn_FixAFee; }
            set { SetPropertyValue<decimal>("n_FixAFee", ref fn_FixAFee, value); }
        }
        decimal fn_FixFee;
        public decimal n_FixFee
        {
            get { return fn_FixFee; }
            set { SetPropertyValue<decimal>("n_FixFee", ref fn_FixFee, value); }
        }
        string fs_PayMode;
        [Size(2)]
        public string s_PayMode
        {
            get { return fs_PayMode; }
            set { SetPropertyValue<string>("s_PayMode", ref fs_PayMode, value); }
        }
        string fs_FeeStatusOrder;
        [Size(10)]
        public string s_FeeStatusOrder
        {
            get { return fs_FeeStatusOrder; }
            set { SetPropertyValue<string>("s_FeeStatusOrder", ref fs_FeeStatusOrder, value); }
        }
        string fs_FeeStatusInit;
        [Size(10)]
        public string s_FeeStatusInit
        {
            get { return fs_FeeStatusInit; }
            set { SetPropertyValue<string>("s_FeeStatusInit", ref fs_FeeStatusInit, value); }
        }
        int fn_ChargeCurrency;
        public int n_ChargeCurrency
        {
            get { return fn_ChargeCurrency; }
            set { SetPropertyValue<int>("n_ChargeCurrency", ref fn_ChargeCurrency, value); }
        }
        int fn_OfficialCurrency;
        public int n_OfficialCurrency
        {
            get { return fn_OfficialCurrency; }
            set { SetPropertyValue<int>("n_OfficialCurrency", ref fn_OfficialCurrency, value); }
        }
        string fs_IsRegOnline;
        [Size(1)]
        public string s_IsRegOnline
        {
            get { return fs_IsRegOnline; }
            set { SetPropertyValue<string>("s_IsRegOnline", ref fs_IsRegOnline, value); }
        }
        string fs_TotalSerial;
        [Size(20)]
        public string s_TotalSerial
        {
            get { return fs_TotalSerial; }
            set { SetPropertyValue<string>("s_TotalSerial", ref fs_TotalSerial, value); }
        }
        string fs_SerialLocation;
        [Size(20)]
        public string s_SerialLocation
        {
            get { return fs_SerialLocation; }
            set { SetPropertyValue<string>("s_SerialLocation", ref fs_SerialLocation, value); }
        }
        string fs_InConsole;
        [Size(1)]
        public string s_InConsole
        {
            get { return fs_InConsole; }
            set { SetPropertyValue<string>("s_InConsole", ref fs_InConsole, value); }
        }
        DateTime fdt_CreateDate;
        public DateTime dt_CreateDate
        {
            get { return fdt_CreateDate; }
            set { SetPropertyValue<DateTime>("dt_CreateDate", ref fdt_CreateDate, value); }
        }
        DateTime fdt_EditDate;
        public DateTime dt_EditDate
        {
            get { return fdt_EditDate; }
            set { SetPropertyValue<DateTime>("dt_EditDate", ref fdt_EditDate, value); }
        }
        string fs_OtherName;
        [Size(500)]
        public string s_OtherName
        {
            get { return fs_OtherName; }
            set { SetPropertyValue<string>("s_OtherName", ref fs_OtherName, value); }
        }
        int fn_EndProcess;
        public int n_EndProcess
        {
            get { return fn_EndProcess; }
            set { SetPropertyValue<int>("n_EndProcess", ref fn_EndProcess, value); }
        }
        decimal fn_IntroPer;
        public decimal n_IntroPer
        {
            get { return fn_IntroPer; }
            set { SetPropertyValue<decimal>("n_IntroPer", ref fn_IntroPer, value); }
        }
        string fs_SubmitStatus;
        [Size(1)]
        public string s_SubmitStatus
        {
            get { return fs_SubmitStatus; }
            set { SetPropertyValue<string>("s_SubmitStatus", ref fs_SubmitStatus, value); }
        }
        DateTime fdt_SubmittedDate;
        public DateTime dt_SubmittedDate
        {
            get { return fdt_SubmittedDate; }
            set { SetPropertyValue<DateTime>("dt_SubmittedDate", ref fdt_SubmittedDate, value); }
        }
        string fs_ProcessMark;
        [Size(10)]
        public string s_ProcessMark
        {
            get { return fs_ProcessMark; }
            set { SetPropertyValue<string>("s_ProcessMark", ref fs_ProcessMark, value); }
        }
        int fn_DepartmentID;
        public int n_DepartmentID
        {
            get { return fn_DepartmentID; }
            set { SetPropertyValue<int>("n_DepartmentID", ref fn_DepartmentID, value); }
        }
        string fs_Applicants;
        [Size(1000)]
        public string s_Applicants
        {
            get { return fs_Applicants; }
            set { SetPropertyValue<string>("s_Applicants", ref fs_Applicants, value); }
        }
        string fs_ClientContacts;
        [Size(1000)]
        public string s_ClientContacts
        {
            get { return fs_ClientContacts; }
            set { SetPropertyValue<string>("s_ClientContacts", ref fs_ClientContacts, value); }
        }
        string fs_Dealers;
        [Size(1000)]
        public string s_Dealers
        {
            get { return fs_Dealers; }
            set { SetPropertyValue<string>("s_Dealers", ref fs_Dealers, value); }
        }
        string fs_Creator;
        [Size(50)]
        public string s_Creator
        {
            get { return fs_Creator; }
            set { SetPropertyValue<string>("s_Creator", ref fs_Creator, value); }
        }
        string fs_Editor;
        [Size(50)]
        public string s_Editor
        {
            get { return fs_Editor; }
            set { SetPropertyValue<string>("s_Editor", ref fs_Editor, value); }
        }
        string fs_CurrentOperator;
        [Size(50)]
        public string s_CurrentOperator
        {
            get { return fs_CurrentOperator; }
            set { SetPropertyValue<string>("s_CurrentOperator", ref fs_CurrentOperator, value); }
        }
        int fn_ContractID;
        [Indexed(Name = @"in_ContractID_TCase_Base")]
        public int n_ContractID
        {
            get { return fn_ContractID; }
            set { SetPropertyValue<int>("n_ContractID", ref fn_ContractID, value); }
        }
        string fs_CaseNativeName;
        [Size(300)]
        public string s_CaseNativeName
        {
            get { return fs_CaseNativeName; }
            set { SetPropertyValue<string>("s_CaseNativeName", ref fs_CaseNativeName, value); }
        }
        int fn_AppCountry;
        public int n_AppCountry
        {
            get { return fn_AppCountry; }
            set { SetPropertyValue<int>("n_AppCountry", ref fn_AppCountry, value); }
        }
        string fs_DealersID;
        [Size(500)]
        public string s_DealersID
        {
            get { return fs_DealersID; }
            set { SetPropertyValue<string>("s_DealersID", ref fs_DealersID, value); }
        }
        int fn_ProcessID;
        public int n_ProcessID
        {
            get { return fn_ProcessID; }
            set { SetPropertyValue<int>("n_ProcessID", ref fn_ProcessID, value); }
        }
        int fn_StartProcessID;
        public int n_StartProcessID
        {
            get { return fn_StartProcessID; }
            set { SetPropertyValue<int>("n_StartProcessID", ref fn_StartProcessID, value); }
        }
        string fs_AppNo;
        public string s_AppNo
        {
            get { return fs_AppNo; }
            set { SetPropertyValue<string>("s_AppNo", ref fs_AppNo, value); }
        }
        DateTime fdt_AppDate;
        public DateTime dt_AppDate
        {
            get { return fdt_AppDate; }
            set { SetPropertyValue<DateTime>("dt_AppDate", ref fdt_AppDate, value); }
        }
        string fs_ApplicantAddresses;
        [Size(500)]
        public string s_ApplicantAddresses
        {
            get { return fs_ApplicantAddresses; }
            set { SetPropertyValue<string>("s_ApplicantAddresses", ref fs_ApplicantAddresses, value); }
        }
        string fs_AcceptNO;
        [Size(50)]
        public string s_AcceptNO
        {
            get { return fs_AcceptNO; }
            set { SetPropertyValue<string>("s_AcceptNO", ref fs_AcceptNO, value); }
        }
        string fs_CProcessCodeIDs;
        [Size(500)]
        public string s_CProcessCodeIDs
        {
            get { return fs_CProcessCodeIDs; }
            set { SetPropertyValue<string>("s_CProcessCodeIDs", ref fs_CProcessCodeIDs, value); }
        }
        string fs_NCProcessCodeIDs;
        [Size(500)]
        public string s_NCProcessCodeIDs
        {
            get { return fs_NCProcessCodeIDs; }
            set { SetPropertyValue<string>("s_NCProcessCodeIDs", ref fs_NCProcessCodeIDs, value); }
        }
        string fs_ApplicantsCountry;
        [Size(500)]
        public string s_ApplicantsCountry
        {
            get { return fs_ApplicantsCountry; }
            set { SetPropertyValue<string>("s_ApplicantsCountry", ref fs_ApplicantsCountry, value); }
        }
        string fs_ApplicantsNativeName;
        [Size(1000)]
        public string s_ApplicantsNativeName
        {
            get { return fs_ApplicantsNativeName; }
            set { SetPropertyValue<string>("s_ApplicantsNativeName", ref fs_ApplicantsNativeName, value); }
        }
        string fs_CustomField1;
        public string s_CustomField1
        {
            get { return fs_CustomField1; }
            set { SetPropertyValue<string>("s_CustomField1", ref fs_CustomField1, value); }
        }
        string fs_CustomField2;
        public string s_CustomField2
        {
            get { return fs_CustomField2; }
            set { SetPropertyValue<string>("s_CustomField2", ref fs_CustomField2, value); }
        }
        string fs_CustomField3;
        public string s_CustomField3
        {
            get { return fs_CustomField3; }
            set { SetPropertyValue<string>("s_CustomField3", ref fs_CustomField3, value); }
        }
        string fs_CustomField4;
        public string s_CustomField4
        {
            get { return fs_CustomField4; }
            set { SetPropertyValue<string>("s_CustomField4", ref fs_CustomField4, value); }
        }
        string fs_CustomField5;
        public string s_CustomField5
        {
            get { return fs_CustomField5; }
            set { SetPropertyValue<string>("s_CustomField5", ref fs_CustomField5, value); }
        }
        string fs_CustomField6;
        public string s_CustomField6
        {
            get { return fs_CustomField6; }
            set { SetPropertyValue<string>("s_CustomField6", ref fs_CustomField6, value); }
        }
        string fs_CustomField7;
        public string s_CustomField7
        {
            get { return fs_CustomField7; }
            set { SetPropertyValue<string>("s_CustomField7", ref fs_CustomField7, value); }
        }
        string fs_CustomField8;
        public string s_CustomField8
        {
            get { return fs_CustomField8; }
            set { SetPropertyValue<string>("s_CustomField8", ref fs_CustomField8, value); }
        }
        string fs_CustomField9;
        public string s_CustomField9
        {
            get { return fs_CustomField9; }
            set { SetPropertyValue<string>("s_CustomField9", ref fs_CustomField9, value); }
        }
        string fs_CustomField10;
        public string s_CustomField10
        {
            get { return fs_CustomField10; }
            set { SetPropertyValue<string>("s_CustomField10", ref fs_CustomField10, value); }
        }
        int fn_SecurityLevelID;
        [Indexed(Name = @"in_SecurityLevelID_TCase_Base")]
        public int n_SecurityLevelID
        {
            get { return fn_SecurityLevelID; }
            set { SetPropertyValue<int>("n_SecurityLevelID", ref fn_SecurityLevelID, value); }
        }
        string fs_ApplicantID;
        [Size(300)]
        public string s_ApplicantID
        {
            get { return fs_ApplicantID; }
            set { SetPropertyValue<string>("s_ApplicantID", ref fs_ApplicantID, value); }
        }
        string fs_IsTempCase;
        [Size(2)]
        public string s_IsTempCase
        {
            get { return fs_IsTempCase; }
            set { SetPropertyValue<string>("s_IsTempCase", ref fs_IsTempCase, value); }
        }
        string fs_IsMiddleCase;
        [Size(2)]
        public string s_IsMiddleCase
        {
            get { return fs_IsMiddleCase; }
            set { SetPropertyValue<string>("s_IsMiddleCase", ref fs_IsMiddleCase, value); }
        }
        DateTime fdt_SendCheckDate;
        public DateTime dt_SendCheckDate
        {
            get { return fdt_SendCheckDate; }
            set { SetPropertyValue<DateTime>("dt_SendCheckDate", ref fdt_SendCheckDate, value); }
        }
        int fn_PreferentialCombineID;
        public int n_PreferentialCombineID
        {
            get { return fn_PreferentialCombineID; }
            set { SetPropertyValue<int>("n_PreferentialCombineID", ref fn_PreferentialCombineID, value); }
        }
        string fs_ElecPayer;
        public string s_ElecPayer
        {
            get { return fs_ElecPayer; }
            set { SetPropertyValue<string>("s_ElecPayer", ref fs_ElecPayer, value); }
        }
        string fs_ClientCName;
        [Size(500)]
        public string s_ClientCName
        {
            get { return fs_ClientCName; }
            set { SetPropertyValue<string>("s_ClientCName", ref fs_ClientCName, value); }
        }
        string fs_ArchiveStatus;
        [Size(1)]
        public string s_ArchiveStatus
        {
            get { return fs_ArchiveStatus; }
            set { SetPropertyValue<string>("s_ArchiveStatus", ref fs_ArchiveStatus, value); }
        }
        string fs_ArchivePosition;
        public string s_ArchivePosition
        {
            get { return fs_ArchivePosition; }
            set { SetPropertyValue<string>("s_ArchivePosition", ref fs_ArchivePosition, value); }
        }
        int fn_BorrowTimes;
        public int n_BorrowTimes
        {
            get { return fn_BorrowTimes; }
            set { SetPropertyValue<int>("n_BorrowTimes", ref fn_BorrowTimes, value); }
        }
        int fn_CreatorID;
        public int n_CreatorID
        {
            get { return fn_CreatorID; }
            set { SetPropertyValue<int>("n_CreatorID", ref fn_CreatorID, value); }
        }
        string fs_RelatedUserIDs;
        [Size(1000)]
        public string s_RelatedUserIDs
        {
            get { return fs_RelatedUserIDs; }
            set { SetPropertyValue<string>("s_RelatedUserIDs", ref fs_RelatedUserIDs, value); }
        }
        int fn_CutRateID;
        public int n_CutRateID
        {
            get { return fn_CutRateID; }
            set { SetPropertyValue<int>("n_CutRateID", ref fn_CutRateID, value); }
        }
        string fs_PriceDesc;
        [Size(SizeAttribute.Unlimited)]
        public string s_PriceDesc
        {
            get { return fs_PriceDesc; }
            set { SetPropertyValue<string>("s_PriceDesc", ref fs_PriceDesc, value); }
        }
        string fs_PayerBillToName;
        [Size(300)]
        public string s_PayerBillToName
        {
            get { return fs_PayerBillToName; }
            set { SetPropertyValue<string>("s_PayerBillToName", ref fs_PayerBillToName, value); }
        }
        string fs_PayerStreet;
        [Size(300)]
        public string s_PayerStreet
        {
            get { return fs_PayerStreet; }
            set { SetPropertyValue<string>("s_PayerStreet", ref fs_PayerStreet, value); }
        }
        string fs_PayerCity;
        public string s_PayerCity
        {
            get { return fs_PayerCity; }
            set { SetPropertyValue<string>("s_PayerCity", ref fs_PayerCity, value); }
        }
        string fs_PayerState;
        public string s_PayerState
        {
            get { return fs_PayerState; }
            set { SetPropertyValue<string>("s_PayerState", ref fs_PayerState, value); }
        }
        string fs_PayerZipCode;
        [Size(50)]
        public string s_PayerZipCode
        {
            get { return fs_PayerZipCode; }
            set { SetPropertyValue<string>("s_PayerZipCode", ref fs_PayerZipCode, value); }
        }
        int fn_PayerCountry;
        public int n_PayerCountry
        {
            get { return fn_PayerCountry; }
            set { SetPropertyValue<int>("n_PayerCountry", ref fn_PayerCountry, value); }
        }
        string fs_PayerEmail;
        public string s_PayerEmail
        {
            get { return fs_PayerEmail; }
            set { SetPropertyValue<string>("s_PayerEmail", ref fs_PayerEmail, value); }
        }
        string fs_AppsSerial;
        [Size(500)]
        public string s_AppsSerial
        {
            get { return fs_AppsSerial; }
            set { SetPropertyValue<string>("s_AppsSerial", ref fs_AppsSerial, value); }
        }
        string fs_ManualCreateChain;
        [Size(1)]
        public string s_ManualCreateChain
        {
            get { return fs_ManualCreateChain; }
            set { SetPropertyValue<string>("s_ManualCreateChain", ref fs_ManualCreateChain, value); }
        }
        string fs_ApplicantCodes;
        [Size(1000)]
        public string s_ApplicantCodes
        {
            get { return fs_ApplicantCodes; }
            set { SetPropertyValue<string>("s_ApplicantCodes", ref fs_ApplicantCodes, value); }
        }
        [Association(@"T_DemandReferencesTCase_Base")]
        public XPCollection<T_Demand> T_Demands { get { return GetCollection<T_Demand>("T_Demands"); } }
        [Association(@"TCase_ApplicantReferencesTCase_Base")]
        public XPCollection<TCase_Applicant> TCase_Applicants { get { return GetCollection<TCase_Applicant>("TCase_Applicants"); } }
        [Association(@"TCase_AttorneyReferencesTCase_Base")]
        public XPCollection<TCase_Attorney> TCase_Attorneys { get { return GetCollection<TCase_Attorney>("TCase_Attorneys"); } }
        [Association(@"TCase_CaseCustomFieldReferencesTCase_Base")]
        public XPCollection<TCase_CaseCustomField> TCase_CaseCustomFields { get { return GetCollection<TCase_CaseCustomField>("TCase_CaseCustomFields"); } }
        [Association(@"TCase_ClientContactReferencesTCase_Base")]
        public XPCollection<TCase_ClientContact> TCase_ClientContacts { get { return GetCollection<TCase_ClientContact>("TCase_ClientContacts"); } }
        [Association(@"TCase_ClientsReferencesTCase_Base")]
        public XPCollection<TCase_Clients> TCase_Clientss { get { return GetCollection<TCase_Clients>("TCase_Clientss"); } }
        [Association(@"TCase_ContactReferencesTCase_Base")]
        public XPCollection<TCase_Contact> TCase_Contacts { get { return GetCollection<TCase_Contact>("TCase_Contacts"); } }
        [Association(@"TCase_DepartmentReferencesTCase_Base")]
        public XPCollection<TCase_Department> TCase_Departments { get { return GetCollection<TCase_Department>("TCase_Departments"); } }
        [Association(@"TCase_IntroContactReferencesTCase_Base")]
        public XPCollection<TCase_IntroContact> TCase_IntroContacts { get { return GetCollection<TCase_IntroContact>("TCase_IntroContacts"); } }
        [Association(@"TCase_MemoReferencesTCase_Base")]
        public XPCollection<TCase_Memo> TCase_Memos { get { return GetCollection<TCase_Memo>("TCase_Memos"); } }
        [Association(@"TCase_ToAgencyContactReferencesTCase_Base")]
        public XPCollection<TCase_ToAgencyContact> TCase_ToAgencyContacts { get { return GetCollection<TCase_ToAgencyContact>("TCase_ToAgencyContacts"); } }
        [Association(@"T_FeeInCaseReferencesTCase_Base")]
        public XPCollection<T_FeeInCase> T_FeeInCases { get { return GetCollection<T_FeeInCase>("T_FeeInCases"); } }
        [Association(@"T_FileInCaseReferencesTCase_Base")]
        public XPCollection<T_FileInCase> T_FileInCases { get { return GetCollection<T_FileInCase>("T_FileInCases"); } }
    }

}
