//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TCase_Attorney : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TCase_Base fn_CaseID;
        [Association(@"TCase_AttorneyReferencesTCase_Base")]
        public TCase_Base n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TCase_Base>("n_CaseID", ref fn_CaseID, value); }
        }
        int fn_Sequence;
        public int n_Sequence
        {
            get { return fn_Sequence; }
            set { SetPropertyValue<int>("n_Sequence", ref fn_Sequence, value); }
        }
        TCode_Employee fn_AttorneyID;
        [Indexed(Name = @"in_AttorneyID_TCase_Attorney")]
        [Association(@"TCase_AttorneyReferencesTCode_Employee")]
        public TCode_Employee n_AttorneyID
        {
            get { return fn_AttorneyID; }
            set { SetPropertyValue<TCode_Employee>("n_AttorneyID", ref fn_AttorneyID, value); }
        }
        DateTime fdt_AssignDate;
        public DateTime dt_AssignDate
        {
            get { return fdt_AssignDate; }
            set { SetPropertyValue<DateTime>("dt_AssignDate", ref fdt_AssignDate, value); }
        }
        int fn_AssignorID;
        public int n_AssignorID
        {
            get { return fn_AssignorID; }
            set { SetPropertyValue<int>("n_AssignorID", ref fn_AssignorID, value); }
        }
        int fn_CaseRoleID;
        public int n_CaseRoleID
        {
            get { return fn_CaseRoleID; }
            set { SetPropertyValue<int>("n_CaseRoleID", ref fn_CaseRoleID, value); }
        }
    }

}
