//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TCase_CaseCustomField : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TCase_Base fn_CaseID;
        [Association(@"TCase_CaseCustomFieldReferencesTCase_Base")]
        public TCase_Base n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TCase_Base>("n_CaseID", ref fn_CaseID, value); }
        }
        int fn_FieldCodeID;
        public int n_FieldCodeID
        {
            get { return fn_FieldCodeID; }
            set { SetPropertyValue<int>("n_FieldCodeID", ref fn_FieldCodeID, value); }
        }
        string fs_Value;
        [Size(500)]
        public string s_Value
        {
            get { return fs_Value; }
            set { SetPropertyValue<string>("s_Value", ref fs_Value, value); }
        }
    }

}
