//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TCode_Employee : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        string fs_Role;
        [Size(50)]
        public string s_Role
        {
            get { return fs_Role; }
            set { SetPropertyValue<string>("s_Role", ref fs_Role, value); }
        }
        string fs_IPType;
        [Size(50)]
        public string s_IPType
        {
            get { return fs_IPType; }
            set { SetPropertyValue<string>("s_IPType", ref fs_IPType, value); }
        }
        string fs_Name;
        [Size(50)]
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_OtherName;
        [Size(50)]
        public string s_OtherName
        {
            get { return fs_OtherName; }
            set { SetPropertyValue<string>("s_OtherName", ref fs_OtherName, value); }
        }
        string fs_InternalCode;
        [Size(4)]
        public string s_InternalCode
        {
            get { return fs_InternalCode; }
            set { SetPropertyValue<string>("s_InternalCode", ref fs_InternalCode, value); }
        }
        string fs_CertificateNo;
        [Size(20)]
        public string s_CertificateNo
        {
            get { return fs_CertificateNo; }
            set { SetPropertyValue<string>("s_CertificateNo", ref fs_CertificateNo, value); }
        }
        string fs_Phone;
        [Size(150)]
        public string s_Phone
        {
            get { return fs_Phone; }
            set { SetPropertyValue<string>("s_Phone", ref fs_Phone, value); }
        }
        string fs_Mobile;
        [Size(150)]
        public string s_Mobile
        {
            get { return fs_Mobile; }
            set { SetPropertyValue<string>("s_Mobile", ref fs_Mobile, value); }
        }
        string fs_Fax;
        [Size(150)]
        public string s_Fax
        {
            get { return fs_Fax; }
            set { SetPropertyValue<string>("s_Fax", ref fs_Fax, value); }
        }
        string fs_Email;
        [Size(300)]
        public string s_Email
        {
            get { return fs_Email; }
            set { SetPropertyValue<string>("s_Email", ref fs_Email, value); }
        }
        string fs_IMAddress;
        public string s_IMAddress
        {
            get { return fs_IMAddress; }
            set { SetPropertyValue<string>("s_IMAddress", ref fs_IMAddress, value); }
        }
        string fs_Facebook;
        [Size(200)]
        public string s_Facebook
        {
            get { return fs_Facebook; }
            set { SetPropertyValue<string>("s_Facebook", ref fs_Facebook, value); }
        }
        string fs_Twitter;
        [Size(200)]
        public string s_Twitter
        {
            get { return fs_Twitter; }
            set { SetPropertyValue<string>("s_Twitter", ref fs_Twitter, value); }
        }
        string fs_Notes;
        [Size(800)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
        decimal fn_ChargeRate1;
        public decimal n_ChargeRate1
        {
            get { return fn_ChargeRate1; }
            set { SetPropertyValue<decimal>("n_ChargeRate1", ref fn_ChargeRate1, value); }
        }
        int fn_Currency1;
        public int n_Currency1
        {
            get { return fn_Currency1; }
            set { SetPropertyValue<int>("n_Currency1", ref fn_Currency1, value); }
        }
        decimal fn_ChargeRate2;
        public decimal n_ChargeRate2
        {
            get { return fn_ChargeRate2; }
            set { SetPropertyValue<decimal>("n_ChargeRate2", ref fn_ChargeRate2, value); }
        }
        int fn_Currency2;
        public int n_Currency2
        {
            get { return fn_Currency2; }
            set { SetPropertyValue<int>("n_Currency2", ref fn_Currency2, value); }
        }
        DateTime fdt_CreateDate;
        public DateTime dt_CreateDate
        {
            get { return fdt_CreateDate; }
            set { SetPropertyValue<DateTime>("dt_CreateDate", ref fdt_CreateDate, value); }
        }
        DateTime fdt_EditDate;
        public DateTime dt_EditDate
        {
            get { return fdt_EditDate; }
            set { SetPropertyValue<DateTime>("dt_EditDate", ref fdt_EditDate, value); }
        }
        string fs_UserName;
        [Size(50)]
        public string s_UserName
        {
            get { return fs_UserName; }
            set { SetPropertyValue<string>("s_UserName", ref fs_UserName, value); }
        }
        string fs_Password;
        [Size(50)]
        public string s_Password
        {
            get { return fs_Password; }
            set { SetPropertyValue<string>("s_Password", ref fs_Password, value); }
        }
        string fs_EmailName;
        public string s_EmailName
        {
            get { return fs_EmailName; }
            set { SetPropertyValue<string>("s_EmailName", ref fs_EmailName, value); }
        }
        string fs_EmailServer;
        public string s_EmailServer
        {
            get { return fs_EmailServer; }
            set { SetPropertyValue<string>("s_EmailServer", ref fs_EmailServer, value); }
        }
        string fs_Port;
        public string s_Port
        {
            get { return fs_Port; }
            set { SetPropertyValue<string>("s_Port", ref fs_Port, value); }
        }
        string fs_EmailUser;
        public string s_EmailUser
        {
            get { return fs_EmailUser; }
            set { SetPropertyValue<string>("s_EmailUser", ref fs_EmailUser, value); }
        }
        string fs_EmailPwd;
        public string s_EmailPwd
        {
            get { return fs_EmailPwd; }
            set { SetPropertyValue<string>("s_EmailPwd", ref fs_EmailPwd, value); }
        }
        byte[] fs_Signature;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] s_Signature
        {
            get { return fs_Signature; }
            set { SetPropertyValue<byte[]>("s_Signature", ref fs_Signature, value); }
        }
        decimal fn_AttorneyPer;
        public decimal n_AttorneyPer
        {
            get { return fn_AttorneyPer; }
            set { SetPropertyValue<decimal>("n_AttorneyPer", ref fn_AttorneyPer, value); }
        }
        string fs_DataRight;
        [Size(50)]
        public string s_DataRight
        {
            get { return fs_DataRight; }
            set { SetPropertyValue<string>("s_DataRight", ref fs_DataRight, value); }
        }
        string fs_AllowViewDepartData;
        [Size(1)]
        public string s_AllowViewDepartData
        {
            get { return fs_AllowViewDepartData; }
            set { SetPropertyValue<string>("s_AllowViewDepartData", ref fs_AllowViewDepartData, value); }
        }
        string fs_CanCC;
        [Size(1)]
        public string s_CanCC
        {
            get { return fs_CanCC; }
            set { SetPropertyValue<string>("s_CanCC", ref fs_CanCC, value); }
        }
        string fs_CC;
        [Size(500)]
        public string s_CC
        {
            get { return fs_CC; }
            set { SetPropertyValue<string>("s_CC", ref fs_CC, value); }
        }
        string fs_AllowCaseConsoleMyData;
        [Size(1)]
        public string s_AllowCaseConsoleMyData
        {
            get { return fs_AllowCaseConsoleMyData; }
            set { SetPropertyValue<string>("s_AllowCaseConsoleMyData", ref fs_AllowCaseConsoleMyData, value); }
        }
        string fs_AllowCaseConsoleDepartmentData;
        [Size(1)]
        public string s_AllowCaseConsoleDepartmentData
        {
            get { return fs_AllowCaseConsoleDepartmentData; }
            set { SetPropertyValue<string>("s_AllowCaseConsoleDepartmentData", ref fs_AllowCaseConsoleDepartmentData, value); }
        }
        string fs_AllowCaseConsoleAllData;
        [Size(1)]
        public string s_AllowCaseConsoleAllData
        {
            get { return fs_AllowCaseConsoleAllData; }
            set { SetPropertyValue<string>("s_AllowCaseConsoleAllData", ref fs_AllowCaseConsoleAllData, value); }
        }
        bool fn_Valid;
        public bool n_Valid
        {
            get { return fn_Valid; }
            set { SetPropertyValue<bool>("n_Valid", ref fn_Valid, value); }
        }
        string fs_Contact;
        [Size(500)]
        public string s_Contact
        {
            get { return fs_Contact; }
            set { SetPropertyValue<string>("s_Contact", ref fs_Contact, value); }
        }
        DateTime fdt_ModifyPassword;
        public DateTime dt_ModifyPassword
        {
            get { return fdt_ModifyPassword; }
            set { SetPropertyValue<DateTime>("dt_ModifyPassword", ref fdt_ModifyPassword, value); }
        }
        DateTime fdt_Lock;
        public DateTime dt_Lock
        {
            get { return fdt_Lock; }
            set { SetPropertyValue<DateTime>("dt_Lock", ref fdt_Lock, value); }
        }
        int fn_SecurityLevelID;
        [Indexed(Name = @"in_SecurityLevelID_TCode_Employee")]
        public int n_SecurityLevelID
        {
            get { return fn_SecurityLevelID; }
            set { SetPropertyValue<int>("n_SecurityLevelID", ref fn_SecurityLevelID, value); }
        }
        byte[] fimg_MainOrigImg;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] img_MainOrigImg
        {
            get { return fimg_MainOrigImg; }
            set { SetPropertyValue<byte[]>("img_MainOrigImg", ref fimg_MainOrigImg, value); }
        }
        byte[] fimg_MainThumbnail;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] img_MainThumbnail
        {
            get { return fimg_MainThumbnail; }
            set { SetPropertyValue<byte[]>("img_MainThumbnail", ref fimg_MainThumbnail, value); }
        }
        string fs_DefaultIPType;
        [Size(1)]
        public string s_DefaultIPType
        {
            get { return fs_DefaultIPType; }
            set { SetPropertyValue<string>("s_DefaultIPType", ref fs_DefaultIPType, value); }
        }
        string fs_AllowCustomEmail;
        [Size(1)]
        public string s_AllowCustomEmail
        {
            get { return fs_AllowCustomEmail; }
            set { SetPropertyValue<string>("s_AllowCustomEmail", ref fs_AllowCustomEmail, value); }
        }
        [Association(@"TCase_AttorneyReferencesTCode_Employee")]
        public XPCollection<TCase_Attorney> TCase_Attorneys { get { return GetCollection<TCase_Attorney>("TCase_Attorneys"); } }
    }

}
