//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TCode_Country : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        string fs_CountryCode;
        [Size(5)]
        public string s_CountryCode
        {
            get { return fs_CountryCode; }
            set { SetPropertyValue<string>("s_CountryCode", ref fs_CountryCode, value); }
        }
        string fs_Name;
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_OtherName;
        public string s_OtherName
        {
            get { return fs_OtherName; }
            set { SetPropertyValue<string>("s_OtherName", ref fs_OtherName, value); }
        }
        string fs_MadridAgreement;
        [Size(1)]
        public string s_MadridAgreement
        {
            get { return fs_MadridAgreement; }
            set { SetPropertyValue<string>("s_MadridAgreement", ref fs_MadridAgreement, value); }
        }
        string fs_MadridProtocol;
        [Size(1)]
        public string s_MadridProtocol
        {
            get { return fs_MadridProtocol; }
            set { SetPropertyValue<string>("s_MadridProtocol", ref fs_MadridProtocol, value); }
        }
        string fs_PCTContract;
        [Size(1)]
        public string s_PCTContract
        {
            get { return fs_PCTContract; }
            set { SetPropertyValue<string>("s_PCTContract", ref fs_PCTContract, value); }
        }
        string fs_MultiClass;
        [Size(1)]
        public string s_MultiClass
        {
            get { return fs_MultiClass; }
            set { SetPropertyValue<string>("s_MultiClass", ref fs_MultiClass, value); }
        }
        DateTime fdt_CreateDate;
        public DateTime dt_CreateDate
        {
            get { return fdt_CreateDate; }
            set { SetPropertyValue<DateTime>("dt_CreateDate", ref fdt_CreateDate, value); }
        }
        DateTime fdt_EditDate;
        public DateTime dt_EditDate
        {
            get { return fdt_EditDate; }
            set { SetPropertyValue<DateTime>("dt_EditDate", ref fdt_EditDate, value); }
        }
        int fn_FrequentNo;
        public int n_FrequentNo
        {
            get { return fn_FrequentNo; }
            set { SetPropertyValue<int>("n_FrequentNo", ref fn_FrequentNo, value); }
        }
    }

}
