//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TCstmr_CoopAgency : XPLiteObject
    {
        int fn_AgencyID;
        [Key(true)]
        public int n_AgencyID
        {
            get { return fn_AgencyID; }
            set { SetPropertyValue<int>("n_AgencyID", ref fn_AgencyID, value); }
        }
        string fs_Name;
        [Size(300)]
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_NativeName;
        [Size(200)]
        public string s_NativeName
        {
            get { return fs_NativeName; }
            set { SetPropertyValue<string>("s_NativeName", ref fs_NativeName, value); }
        }
        string fs_OtherName;
        [Size(200)]
        public string s_OtherName
        {
            get { return fs_OtherName; }
            set { SetPropertyValue<string>("s_OtherName", ref fs_OtherName, value); }
        }
        int fn_Language;
        public int n_Language
        {
            get { return fn_Language; }
            set { SetPropertyValue<int>("n_Language", ref fn_Language, value); }
        }
        string fs_IPType;
        [Size(50)]
        public string s_IPType
        {
            get { return fs_IPType; }
            set { SetPropertyValue<string>("s_IPType", ref fs_IPType, value); }
        }
        string fs_Credit;
        [Size(20)]
        public string s_Credit
        {
            get { return fs_Credit; }
            set { SetPropertyValue<string>("s_Credit", ref fs_Credit, value); }
        }
        string fs_Notes;
        [Size(800)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
        int fn_ClientID;
        [Indexed(Name = @"in_ClientID_TCstmr_CoopAgency")]
        public int n_ClientID
        {
            get { return fn_ClientID; }
            set { SetPropertyValue<int>("n_ClientID", ref fn_ClientID, value); }
        }
        int fn_PayCurrency;
        public int n_PayCurrency
        {
            get { return fn_PayCurrency; }
            set { SetPropertyValue<int>("n_PayCurrency", ref fn_PayCurrency, value); }
        }
        DateTime fdt_FirstCaseFromDate;
        public DateTime dt_FirstCaseFromDate
        {
            get { return fdt_FirstCaseFromDate; }
            set { SetPropertyValue<DateTime>("dt_FirstCaseFromDate", ref fdt_FirstCaseFromDate, value); }
        }
        DateTime fdt_LastCaseFromDate;
        public DateTime dt_LastCaseFromDate
        {
            get { return fdt_LastCaseFromDate; }
            set { SetPropertyValue<DateTime>("dt_LastCaseFromDate", ref fdt_LastCaseFromDate, value); }
        }
        DateTime fdt_FirstCaseToDate;
        public DateTime dt_FirstCaseToDate
        {
            get { return fdt_FirstCaseToDate; }
            set { SetPropertyValue<DateTime>("dt_FirstCaseToDate", ref fdt_FirstCaseToDate, value); }
        }
        DateTime fdt_LastCaseToDate;
        public DateTime dt_LastCaseToDate
        {
            get { return fdt_LastCaseToDate; }
            set { SetPropertyValue<DateTime>("dt_LastCaseToDate", ref fdt_LastCaseToDate, value); }
        }
        string fs_Phone;
        [Size(150)]
        public string s_Phone
        {
            get { return fs_Phone; }
            set { SetPropertyValue<string>("s_Phone", ref fs_Phone, value); }
        }
        string fs_Mobile;
        [Size(150)]
        public string s_Mobile
        {
            get { return fs_Mobile; }
            set { SetPropertyValue<string>("s_Mobile", ref fs_Mobile, value); }
        }
        string fs_Fax;
        [Size(150)]
        public string s_Fax
        {
            get { return fs_Fax; }
            set { SetPropertyValue<string>("s_Fax", ref fs_Fax, value); }
        }
        string fs_Email;
        [Size(300)]
        public string s_Email
        {
            get { return fs_Email; }
            set { SetPropertyValue<string>("s_Email", ref fs_Email, value); }
        }
        string fs_WebSite;
        [Size(300)]
        public string s_WebSite
        {
            get { return fs_WebSite; }
            set { SetPropertyValue<string>("s_WebSite", ref fs_WebSite, value); }
        }
        string fs_IMAddress;
        public string s_IMAddress
        {
            get { return fs_IMAddress; }
            set { SetPropertyValue<string>("s_IMAddress", ref fs_IMAddress, value); }
        }
        string fs_Facebook;
        [Size(200)]
        public string s_Facebook
        {
            get { return fs_Facebook; }
            set { SetPropertyValue<string>("s_Facebook", ref fs_Facebook, value); }
        }
        string fs_Twitter;
        [Size(200)]
        public string s_Twitter
        {
            get { return fs_Twitter; }
            set { SetPropertyValue<string>("s_Twitter", ref fs_Twitter, value); }
        }
        DateTime fdt_CreateDate;
        public DateTime dt_CreateDate
        {
            get { return fdt_CreateDate; }
            set { SetPropertyValue<DateTime>("dt_CreateDate", ref fdt_CreateDate, value); }
        }
        DateTime fdt_EditDate;
        public DateTime dt_EditDate
        {
            get { return fdt_EditDate; }
            set { SetPropertyValue<DateTime>("dt_EditDate", ref fdt_EditDate, value); }
        }
        int fs_Language;
        public int s_Language
        {
            get { return fs_Language; }
            set { SetPropertyValue<int>("s_Language", ref fs_Language, value); }
        }
        int fs_PayUnit;
        public int s_PayUnit
        {
            get { return fs_PayUnit; }
            set { SetPropertyValue<int>("s_PayUnit", ref fs_PayUnit, value); }
        }
        string fs_IPRole;
        [Size(50)]
        public string s_IPRole
        {
            get { return fs_IPRole; }
            set { SetPropertyValue<string>("s_IPRole", ref fs_IPRole, value); }
        }
        int fn_PayUnit;
        public int n_PayUnit
        {
            get { return fn_PayUnit; }
            set { SetPropertyValue<int>("n_PayUnit", ref fn_PayUnit, value); }
        }
        string fs_Lock;
        [Size(1)]
        public string s_Lock
        {
            get { return fs_Lock; }
            set { SetPropertyValue<string>("s_Lock", ref fs_Lock, value); }
        }
        string fs_Locker;
        [Size(20)]
        public string s_Locker
        {
            get { return fs_Locker; }
            set { SetPropertyValue<string>("s_Locker", ref fs_Locker, value); }
        }
        string fs_Creator;
        [Size(50)]
        public string s_Creator
        {
            get { return fs_Creator; }
            set { SetPropertyValue<string>("s_Creator", ref fs_Creator, value); }
        }
        string fs_Editor;
        [Size(50)]
        public string s_Editor
        {
            get { return fs_Editor; }
            set { SetPropertyValue<string>("s_Editor", ref fs_Editor, value); }
        }
        string fs_Addresses;
        [Size(2000)]
        public string s_Addresses
        {
            get { return fs_Addresses; }
            set { SetPropertyValue<string>("s_Addresses", ref fs_Addresses, value); }
        }
        string fs_ContactsFirstName;
        [Size(500)]
        public string s_ContactsFirstName
        {
            get { return fs_ContactsFirstName; }
            set { SetPropertyValue<string>("s_ContactsFirstName", ref fs_ContactsFirstName, value); }
        }
        string fs_ContactsLastName;
        [Size(500)]
        public string s_ContactsLastName
        {
            get { return fs_ContactsLastName; }
            set { SetPropertyValue<string>("s_ContactsLastName", ref fs_ContactsLastName, value); }
        }
        string fs_ContactsTel;
        [Size(150)]
        public string s_ContactsTel
        {
            get { return fs_ContactsTel; }
            set { SetPropertyValue<string>("s_ContactsTel", ref fs_ContactsTel, value); }
        }
        string fs_ContactsFax;
        [Size(150)]
        public string s_ContactsFax
        {
            get { return fs_ContactsFax; }
            set { SetPropertyValue<string>("s_ContactsFax", ref fs_ContactsFax, value); }
        }
        string fs_ContactsEmail;
        [Size(150)]
        public string s_ContactsEmail
        {
            get { return fs_ContactsEmail; }
            set { SetPropertyValue<string>("s_ContactsEmail", ref fs_ContactsEmail, value); }
        }
        string fs_FirstAddress;
        [Size(500)]
        public string s_FirstAddress
        {
            get { return fs_FirstAddress; }
            set { SetPropertyValue<string>("s_FirstAddress", ref fs_FirstAddress, value); }
        }
        int fn_OAddressCountry;
        public int n_OAddressCountry
        {
            get { return fn_OAddressCountry; }
            set { SetPropertyValue<int>("n_OAddressCountry", ref fn_OAddressCountry, value); }
        }
        int fn_ToPatentCaseCount;
        public int n_ToPatentCaseCount
        {
            get { return fn_ToPatentCaseCount; }
            set { SetPropertyValue<int>("n_ToPatentCaseCount", ref fn_ToPatentCaseCount, value); }
        }
        int fn_ToTMCaseCount;
        public int n_ToTMCaseCount
        {
            get { return fn_ToTMCaseCount; }
            set { SetPropertyValue<int>("n_ToTMCaseCount", ref fn_ToTMCaseCount, value); }
        }
        int fn_ToCopyrightCaseCount;
        public int n_ToCopyrightCaseCount
        {
            get { return fn_ToCopyrightCaseCount; }
            set { SetPropertyValue<int>("n_ToCopyrightCaseCount", ref fn_ToCopyrightCaseCount, value); }
        }
        int fn_ToDomainCaseCount;
        public int n_ToDomainCaseCount
        {
            get { return fn_ToDomainCaseCount; }
            set { SetPropertyValue<int>("n_ToDomainCaseCount", ref fn_ToDomainCaseCount, value); }
        }
        int fn_ToOtherCaseCount;
        public int n_ToOtherCaseCount
        {
            get { return fn_ToOtherCaseCount; }
            set { SetPropertyValue<int>("n_ToOtherCaseCount", ref fn_ToOtherCaseCount, value); }
        }
        int fn_SecurityLevelID;
        [Indexed(Name = @"in_SecurityLevelID_TCstmr_CoopAgency")]
        public int n_SecurityLevelID
        {
            get { return fn_SecurityLevelID; }
            set { SetPropertyValue<int>("n_SecurityLevelID", ref fn_SecurityLevelID, value); }
        }
        string fs_Code;
        [Size(200)]
        public string s_Code
        {
            get { return fs_Code; }
            set { SetPropertyValue<string>("s_Code", ref fs_Code, value); }
        }
        string fs_BeneficiaryBankName;
        [Size(500)]
        public string s_BeneficiaryBankName
        {
            get { return fs_BeneficiaryBankName; }
            set { SetPropertyValue<string>("s_BeneficiaryBankName", ref fs_BeneficiaryBankName, value); }
        }
        string fs_BeneficiaryBankAddress;
        [Size(1000)]
        public string s_BeneficiaryBankAddress
        {
            get { return fs_BeneficiaryBankAddress; }
            set { SetPropertyValue<string>("s_BeneficiaryBankAddress", ref fs_BeneficiaryBankAddress, value); }
        }
        string fs_BeneficiaryName;
        [Size(500)]
        public string s_BeneficiaryName
        {
            get { return fs_BeneficiaryName; }
            set { SetPropertyValue<string>("s_BeneficiaryName", ref fs_BeneficiaryName, value); }
        }
        string fs_BeneficiaryAddress;
        [Size(1000)]
        public string s_BeneficiaryAddress
        {
            get { return fs_BeneficiaryAddress; }
            set { SetPropertyValue<string>("s_BeneficiaryAddress", ref fs_BeneficiaryAddress, value); }
        }
        string fs_BeneficiaryAccountNumber;
        [Size(500)]
        public string s_BeneficiaryAccountNumber
        {
            get { return fs_BeneficiaryAccountNumber; }
            set { SetPropertyValue<string>("s_BeneficiaryAccountNumber", ref fs_BeneficiaryAccountNumber, value); }
        }
        string fs_IBAN;
        [Size(500)]
        public string s_IBAN
        {
            get { return fs_IBAN; }
            set { SetPropertyValue<string>("s_IBAN", ref fs_IBAN, value); }
        }
        string fs_SwiftCode;
        [Size(500)]
        public string s_SwiftCode
        {
            get { return fs_SwiftCode; }
            set { SetPropertyValue<string>("s_SwiftCode", ref fs_SwiftCode, value); }
        }
        string fs_ABA;
        [Size(500)]
        public string s_ABA
        {
            get { return fs_ABA; }
            set { SetPropertyValue<string>("s_ABA", ref fs_ABA, value); }
        }
        [Association(@"T_DemandReferencesTCstmr_CoopAgency")]
        public XPCollection<T_Demand> T_Demands { get { return GetCollection<T_Demand>("T_Demands"); } }
        [Association(@"TCstmr_AgencyAddressReferencesTCstmr_CoopAgency")]
        public XPCollection<TCstmr_AgencyAddress> TCstmr_AgencyAddresss { get { return GetCollection<TCstmr_AgencyAddress>("TCstmr_AgencyAddresss"); } }
        [Association(@"TCstmr_AgencyContactReferencesTCstmr_CoopAgency")]
        public XPCollection<TCstmr_AgencyContact> TCstmr_AgencyContacts { get { return GetCollection<TCstmr_AgencyContact>("TCstmr_AgencyContacts"); } }
        [Association(@"TCase_BaseReferencesTCstmr_CoopAgency")]
        public XPCollection<TCase_Base> TCase_Bases { get { return GetCollection<TCase_Base>("TCase_Bases"); } }
        [Association(@"TCase_BaseReferencesTCstmr_CoopAgency1")]
        public XPCollection<TCase_Base> TCase_Bases1 { get { return GetCollection<TCase_Base>("TCase_Bases1"); } }
        [Association(@"T_OutFilesReferencesTCstmr_CoopAgency")]
        public XPCollection<T_OutFiles> T_OutFiless { get { return GetCollection<T_OutFiles>("T_OutFiless"); } }
    }

}
