//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TCstmr_Applicant : XPLiteObject
    {
        int fn_AppID;
        [Key(true)]
        public int n_AppID
        {
            get { return fn_AppID; }
            set { SetPropertyValue<int>("n_AppID", ref fn_AppID, value); }
        }
        int fn_ClientID;
        [Indexed(Name = @"in_ClientID_TCstmr_Applicant")]
        public int n_ClientID
        {
            get { return fn_ClientID; }
            set { SetPropertyValue<int>("n_ClientID", ref fn_ClientID, value); }
        }
        string fs_Name;
        [Size(300)]
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_NativeName;
        [Size(200)]
        public string s_NativeName
        {
            get { return fs_NativeName; }
            set { SetPropertyValue<string>("s_NativeName", ref fs_NativeName, value); }
        }
        string fs_OtherName;
        [Size(200)]
        public string s_OtherName
        {
            get { return fs_OtherName; }
            set { SetPropertyValue<string>("s_OtherName", ref fs_OtherName, value); }
        }
        string fs_IPType;
        [Size(50)]
        public string s_IPType
        {
            get { return fs_IPType; }
            set { SetPropertyValue<string>("s_IPType", ref fs_IPType, value); }
        }
        string fs_AppType;
        [Size(50)]
        public string s_AppType
        {
            get { return fs_AppType; }
            set { SetPropertyValue<string>("s_AppType", ref fs_AppType, value); }
        }
        string fs_IDName;
        [Size(50)]
        public string s_IDName
        {
            get { return fs_IDName; }
            set { SetPropertyValue<string>("s_IDName", ref fs_IDName, value); }
        }
        string fs_IDNumber;
        [Size(50)]
        public string s_IDNumber
        {
            get { return fs_IDNumber; }
            set { SetPropertyValue<string>("s_IDNumber", ref fs_IDNumber, value); }
        }
        string fs_AppCode;
        [Size(20)]
        public string s_AppCode
        {
            get { return fs_AppCode; }
            set { SetPropertyValue<string>("s_AppCode", ref fs_AppCode, value); }
        }
        string fs_HasTrustDeed;
        [Size(1)]
        public string s_HasTrustDeed
        {
            get { return fs_HasTrustDeed; }
            set { SetPropertyValue<string>("s_HasTrustDeed", ref fs_HasTrustDeed, value); }
        }
        string fs_TrustDeedNo;
        [Size(30)]
        public string s_TrustDeedNo
        {
            get { return fs_TrustDeedNo; }
            set { SetPropertyValue<string>("s_TrustDeedNo", ref fs_TrustDeedNo, value); }
        }
        string fs_TrustDeedPath;
        [Size(300)]
        public string s_TrustDeedPath
        {
            get { return fs_TrustDeedPath; }
            set { SetPropertyValue<string>("s_TrustDeedPath", ref fs_TrustDeedPath, value); }
        }
        string fs_Corporation;
        public string s_Corporation
        {
            get { return fs_Corporation; }
            set { SetPropertyValue<string>("s_Corporation", ref fs_Corporation, value); }
        }
        string fs_Duty;
        public string s_Duty
        {
            get { return fs_Duty; }
            set { SetPropertyValue<string>("s_Duty", ref fs_Duty, value); }
        }
        string fs_Notes;
        [Size(800)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
        string fs_Phone;
        [Size(150)]
        public string s_Phone
        {
            get { return fs_Phone; }
            set { SetPropertyValue<string>("s_Phone", ref fs_Phone, value); }
        }
        string fs_Mobile;
        [Size(150)]
        public string s_Mobile
        {
            get { return fs_Mobile; }
            set { SetPropertyValue<string>("s_Mobile", ref fs_Mobile, value); }
        }
        string fs_Fax;
        [Size(150)]
        public string s_Fax
        {
            get { return fs_Fax; }
            set { SetPropertyValue<string>("s_Fax", ref fs_Fax, value); }
        }
        string fs_Email;
        [Size(300)]
        public string s_Email
        {
            get { return fs_Email; }
            set { SetPropertyValue<string>("s_Email", ref fs_Email, value); }
        }
        string fs_Website;
        [Size(300)]
        public string s_Website
        {
            get { return fs_Website; }
            set { SetPropertyValue<string>("s_Website", ref fs_Website, value); }
        }
        string fs_IMAddress;
        public string s_IMAddress
        {
            get { return fs_IMAddress; }
            set { SetPropertyValue<string>("s_IMAddress", ref fs_IMAddress, value); }
        }
        string fs_Facebook;
        [Size(200)]
        public string s_Facebook
        {
            get { return fs_Facebook; }
            set { SetPropertyValue<string>("s_Facebook", ref fs_Facebook, value); }
        }
        string fs_Twitter;
        [Size(200)]
        public string s_Twitter
        {
            get { return fs_Twitter; }
            set { SetPropertyValue<string>("s_Twitter", ref fs_Twitter, value); }
        }
        DateTime fdt_CreateDate;
        public DateTime dt_CreateDate
        {
            get { return fdt_CreateDate; }
            set { SetPropertyValue<DateTime>("dt_CreateDate", ref fdt_CreateDate, value); }
        }
        DateTime fdt_EditDate;
        public DateTime dt_EditDate
        {
            get { return fdt_EditDate; }
            set { SetPropertyValue<DateTime>("dt_EditDate", ref fdt_EditDate, value); }
        }
        string fs_Lock;
        [Size(1)]
        public string s_Lock
        {
            get { return fs_Lock; }
            set { SetPropertyValue<string>("s_Lock", ref fs_Lock, value); }
        }
        string fs_Locker;
        [Size(20)]
        public string s_Locker
        {
            get { return fs_Locker; }
            set { SetPropertyValue<string>("s_Locker", ref fs_Locker, value); }
        }
        string fs_Creator;
        [Size(50)]
        public string s_Creator
        {
            get { return fs_Creator; }
            set { SetPropertyValue<string>("s_Creator", ref fs_Creator, value); }
        }
        string fs_Editor;
        [Size(50)]
        public string s_Editor
        {
            get { return fs_Editor; }
            set { SetPropertyValue<string>("s_Editor", ref fs_Editor, value); }
        }
        string fs_Area;
        public string s_Area
        {
            get { return fs_Area; }
            set { SetPropertyValue<string>("s_Area", ref fs_Area, value); }
        }
        int fn_PatentCaseCount;
        public int n_PatentCaseCount
        {
            get { return fn_PatentCaseCount; }
            set { SetPropertyValue<int>("n_PatentCaseCount", ref fn_PatentCaseCount, value); }
        }
        int fn_TMCaseCount;
        public int n_TMCaseCount
        {
            get { return fn_TMCaseCount; }
            set { SetPropertyValue<int>("n_TMCaseCount", ref fn_TMCaseCount, value); }
        }
        int fn_CopyrightCaseCount;
        public int n_CopyrightCaseCount
        {
            get { return fn_CopyrightCaseCount; }
            set { SetPropertyValue<int>("n_CopyrightCaseCount", ref fn_CopyrightCaseCount, value); }
        }
        int fn_DomainCaseCount;
        public int n_DomainCaseCount
        {
            get { return fn_DomainCaseCount; }
            set { SetPropertyValue<int>("n_DomainCaseCount", ref fn_DomainCaseCount, value); }
        }
        int fn_OtherCaseCount;
        public int n_OtherCaseCount
        {
            get { return fn_OtherCaseCount; }
            set { SetPropertyValue<int>("n_OtherCaseCount", ref fn_OtherCaseCount, value); }
        }
        string fs_FirstAddress;
        [Size(500)]
        public string s_FirstAddress
        {
            get { return fs_FirstAddress; }
            set { SetPropertyValue<string>("s_FirstAddress", ref fs_FirstAddress, value); }
        }
        DateTime fdt_FirstCaseFromDate;
        public DateTime dt_FirstCaseFromDate
        {
            get { return fdt_FirstCaseFromDate; }
            set { SetPropertyValue<DateTime>("dt_FirstCaseFromDate", ref fdt_FirstCaseFromDate, value); }
        }
        DateTime fdt_LastCaseFromDate;
        public DateTime dt_LastCaseFromDate
        {
            get { return fdt_LastCaseFromDate; }
            set { SetPropertyValue<DateTime>("dt_LastCaseFromDate", ref fdt_LastCaseFromDate, value); }
        }
        string fs_Addresses;
        [Size(500)]
        public string s_Addresses
        {
            get { return fs_Addresses; }
            set { SetPropertyValue<string>("s_Addresses", ref fs_Addresses, value); }
        }
        string fs_ContactsFirstName;
        [Size(200)]
        public string s_ContactsFirstName
        {
            get { return fs_ContactsFirstName; }
            set { SetPropertyValue<string>("s_ContactsFirstName", ref fs_ContactsFirstName, value); }
        }
        string fs_ContactsLastName;
        [Size(200)]
        public string s_ContactsLastName
        {
            get { return fs_ContactsLastName; }
            set { SetPropertyValue<string>("s_ContactsLastName", ref fs_ContactsLastName, value); }
        }
        string fs_ContactsTel;
        [Size(150)]
        public string s_ContactsTel
        {
            get { return fs_ContactsTel; }
            set { SetPropertyValue<string>("s_ContactsTel", ref fs_ContactsTel, value); }
        }
        string fs_ContactsFax;
        [Size(150)]
        public string s_ContactsFax
        {
            get { return fs_ContactsFax; }
            set { SetPropertyValue<string>("s_ContactsFax", ref fs_ContactsFax, value); }
        }
        string fs_ContactsAddresses;
        [Size(500)]
        public string s_ContactsAddresses
        {
            get { return fs_ContactsAddresses; }
            set { SetPropertyValue<string>("s_ContactsAddresses", ref fs_ContactsAddresses, value); }
        }
        string fs_GovName;
        public string s_GovName
        {
            get { return fs_GovName; }
            set { SetPropertyValue<string>("s_GovName", ref fs_GovName, value); }
        }
        string fs_AccountName;
        [Size(200)]
        public string s_AccountName
        {
            get { return fs_AccountName; }
            set { SetPropertyValue<string>("s_AccountName", ref fs_AccountName, value); }
        }
        string fs_BankName;
        [Size(200)]
        public string s_BankName
        {
            get { return fs_BankName; }
            set { SetPropertyValue<string>("s_BankName", ref fs_BankName, value); }
        }
        string fs_AccountNo;
        [Size(200)]
        public string s_AccountNo
        {
            get { return fs_AccountNo; }
            set { SetPropertyValue<string>("s_AccountNo", ref fs_AccountNo, value); }
        }
        string fs_AccountCode;
        [Size(40)]
        public string s_AccountCode
        {
            get { return fs_AccountCode; }
            set { SetPropertyValue<string>("s_AccountCode", ref fs_AccountCode, value); }
        }
        string fs_TaxCode;
        public string s_TaxCode
        {
            get { return fs_TaxCode; }
            set { SetPropertyValue<string>("s_TaxCode", ref fs_TaxCode, value); }
        }
        string fs_RegAddress;
        [Size(400)]
        public string s_RegAddress
        {
            get { return fs_RegAddress; }
            set { SetPropertyValue<string>("s_RegAddress", ref fs_RegAddress, value); }
        }
        string fs_RegTel;
        public string s_RegTel
        {
            get { return fs_RegTel; }
            set { SetPropertyValue<string>("s_RegTel", ref fs_RegTel, value); }
        }
        string fs_InvoiceTo;
        [Size(200)]
        public string s_InvoiceTo
        {
            get { return fs_InvoiceTo; }
            set { SetPropertyValue<string>("s_InvoiceTo", ref fs_InvoiceTo, value); }
        }
        int fn_SecurityLevelID;
        [Indexed(Name = @"in_SecurityLevelID_TCstmr_Applicant")]
        public int n_SecurityLevelID
        {
            get { return fn_SecurityLevelID; }
            set { SetPropertyValue<int>("n_SecurityLevelID", ref fn_SecurityLevelID, value); }
        }
        string fs_PayFeePerson;
        public string s_PayFeePerson
        {
            get { return fs_PayFeePerson; }
            set { SetPropertyValue<string>("s_PayFeePerson", ref fs_PayFeePerson, value); }
        }
        bool fb_ElecPayer;
        public bool b_ElecPayer
        {
            get { return fb_ElecPayer; }
            set { SetPropertyValue<bool>("b_ElecPayer", ref fb_ElecPayer, value); }
        }
        int fn_Country;
        public int n_Country
        {
            get { return fn_Country; }
            set { SetPropertyValue<int>("n_Country", ref fn_Country, value); }
        }
        string fs_FeeMitigationYear;
        public string s_FeeMitigationYear
        {
            get { return fs_FeeMitigationYear; }
            set { SetPropertyValue<string>("s_FeeMitigationYear", ref fs_FeeMitigationYear, value); }
        }
        string fs_FeeMitigationNum;
        public string s_FeeMitigationNum
        {
            get { return fs_FeeMitigationNum; }
            set { SetPropertyValue<string>("s_FeeMitigationNum", ref fs_FeeMitigationNum, value); }
        }
        [Association(@"T_DemandReferencesTCstmr_Applicant")]
        public XPCollection<T_Demand> T_Demands { get { return GetCollection<T_Demand>("T_Demands"); } }
        [Association(@"TCstmr_AppAddressReferencesTCstmr_Applicant")]
        public XPCollection<TCstmr_AppAddress> TCstmr_AppAddresss { get { return GetCollection<TCstmr_AppAddress>("TCstmr_AppAddresss"); } }
        [Association(@"TCstmr_AppContactReferencesTCstmr_Applicant")]
        public XPCollection<TCstmr_AppContact> TCstmr_AppContacts { get { return GetCollection<TCstmr_AppContact>("TCstmr_AppContacts"); } }
    }

}
