//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TF_CustomConditionInTaskChain : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        TFCode_CustomCondition fn_CustomConditionID;
        [Association(@"TF_CustomConditionInTaskChainReferencesTFCode_CustomCondition")]
        public TFCode_CustomCondition n_CustomConditionID
        {
            get { return fn_CustomConditionID; }
            set { SetPropertyValue<TFCode_CustomCondition>("n_CustomConditionID", ref fn_CustomConditionID, value); }
        }
        TF_TaskChain fg_TaskChainID;
        [Association(@"TF_CustomConditionInTaskChainReferencesTF_TaskChain")]
        public TF_TaskChain g_TaskChainID
        {
            get { return fg_TaskChainID; }
            set { SetPropertyValue<TF_TaskChain>("g_TaskChainID", ref fg_TaskChainID, value); }
        }
        string fs_Values;
        [Size(500)]
        public string s_Values
        {
            get { return fs_Values; }
            set { SetPropertyValue<string>("s_Values", ref fs_Values, value); }
        }
    }

}
