//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TF_Deadline : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TFCode_Deadline fg_CodeDeadlineID;
        [Association(@"TF_DeadlineReferencesTFCode_Deadline")]
        public TFCode_Deadline g_CodeDeadlineID
        {
            get { return fg_CodeDeadlineID; }
            set { SetPropertyValue<TFCode_Deadline>("g_CodeDeadlineID", ref fg_CodeDeadlineID, value); }
        }
        string fs_RelatedObjectType;
        [Size(50)]
        public string s_RelatedObjectType
        {
            get { return fs_RelatedObjectType; }
            set { SetPropertyValue<string>("s_RelatedObjectType", ref fs_RelatedObjectType, value); }
        }
        int fn_RelatedObjectID;
        public int n_RelatedObjectID
        {
            get { return fn_RelatedObjectID; }
            set { SetPropertyValue<int>("n_RelatedObjectID", ref fn_RelatedObjectID, value); }
        }
        DateTime fdt_Deadline;
        public DateTime dt_Deadline
        {
            get { return fdt_Deadline; }
            set { SetPropertyValue<DateTime>("dt_Deadline", ref fdt_Deadline, value); }
        }
        string fs_ManualUpdateDeadline;
        [Size(1)]
        public string s_ManualUpdateDeadline
        {
            get { return fs_ManualUpdateDeadline; }
            set { SetPropertyValue<string>("s_ManualUpdateDeadline", ref fs_ManualUpdateDeadline, value); }
        }
        string fs_AllowEdit;
        [Size(1)]
        public string s_AllowEdit
        {
            get { return fs_AllowEdit; }
            set { SetPropertyValue<string>("s_AllowEdit", ref fs_AllowEdit, value); }
        }
    }

}
