//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TF_Node : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        string fs_CodeNodeCode;
        [Size(21)]
        public string s_CodeNodeCode
        {
            get { return fs_CodeNodeCode; }
            set { SetPropertyValue<string>("s_CodeNodeCode", ref fs_CodeNodeCode, value); }
        }
        TF_TaskChain fg_TaskChainGuid;
        [Association(@"TF_NodeReferencesTF_TaskChain")]
        public TF_TaskChain g_TaskChainGuid
        {
            get { return fg_TaskChainGuid; }
            set { SetPropertyValue<TF_TaskChain>("g_TaskChainGuid", ref fg_TaskChainGuid, value); }
        }
        Guid fg_FormerNodeGuid;
        public Guid g_FormerNodeGuid
        {
            get { return fg_FormerNodeGuid; }
            set { SetPropertyValue<Guid>("g_FormerNodeGuid", ref fg_FormerNodeGuid, value); }
        }
        string fs_Mode;
        [Size(1)]
        public string s_Mode
        {
            get { return fs_Mode; }
            set { SetPropertyValue<string>("s_Mode", ref fs_Mode, value); }
        }
        string fs_Type;
        [Size(1)]
        public string s_Type
        {
            get { return fs_Type; }
            set { SetPropertyValue<string>("s_Type", ref fs_Type, value); }
        }
        TF_TaskChain fg_OwnTaskChainGuid;
        [Association(@"TF_NodeReferencesTF_TaskChain1")]
        public TF_TaskChain g_OwnTaskChainGuid
        {
            get { return fg_OwnTaskChainGuid; }
            set { SetPropertyValue<TF_TaskChain>("g_OwnTaskChainGuid", ref fg_OwnTaskChainGuid, value); }
        }
        TF_Task fg_OwnTaskGuid;
        [Association(@"TF_NodeReferencesTF_Task")]
        public TF_Task g_OwnTaskGuid
        {
            get { return fg_OwnTaskGuid; }
            set { SetPropertyValue<TF_Task>("g_OwnTaskGuid", ref fg_OwnTaskGuid, value); }
        }
    }

}
