//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TF_OperationLog : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        Guid fg_TaskChainGuid;
        public Guid g_TaskChainGuid
        {
            get { return fg_TaskChainGuid; }
            set { SetPropertyValue<Guid>("g_TaskChainGuid", ref fg_TaskChainGuid, value); }
        }
        Guid fg_TaskGuid;
        public Guid g_TaskGuid
        {
            get { return fg_TaskGuid; }
            set { SetPropertyValue<Guid>("g_TaskGuid", ref fg_TaskGuid, value); }
        }
        string fs_CodeNodeCode;
        [Size(21)]
        public string s_CodeNodeCode
        {
            get { return fs_CodeNodeCode; }
            set { SetPropertyValue<string>("s_CodeNodeCode", ref fs_CodeNodeCode, value); }
        }
        string fs_TaskName;
        public string s_TaskName
        {
            get { return fs_TaskName; }
            set { SetPropertyValue<string>("s_TaskName", ref fs_TaskName, value); }
        }
        string fs_OperationType;
        [Size(50)]
        public string s_OperationType
        {
            get { return fs_OperationType; }
            set { SetPropertyValue<string>("s_OperationType", ref fs_OperationType, value); }
        }
        string fs_StateBefore;
        [Size(1)]
        public string s_StateBefore
        {
            get { return fs_StateBefore; }
            set { SetPropertyValue<string>("s_StateBefore", ref fs_StateBefore, value); }
        }
        string fs_StateAfter;
        [Size(1)]
        public string s_StateAfter
        {
            get { return fs_StateAfter; }
            set { SetPropertyValue<string>("s_StateAfter", ref fs_StateAfter, value); }
        }
        string fs_Reason;
        [Size(1000)]
        public string s_Reason
        {
            get { return fs_Reason; }
            set { SetPropertyValue<string>("s_Reason", ref fs_Reason, value); }
        }
        int fn_Creator;
        public int n_Creator
        {
            get { return fn_Creator; }
            set { SetPropertyValue<int>("n_Creator", ref fn_Creator, value); }
        }
        DateTime fdt_CreateTime;
        public DateTime dt_CreateTime
        {
            get { return fdt_CreateTime; }
            set { SetPropertyValue<DateTime>("dt_CreateTime", ref fdt_CreateTime, value); }
        }
    }

}
