//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TF_TaskParameter : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        TF_Task fg_TaskID;
        [Association(@"TF_TaskParameterReferencesTF_Task")]
        public TF_Task g_TaskID
        {
            get { return fg_TaskID; }
            set { SetPropertyValue<TF_Task>("g_TaskID", ref fg_TaskID, value); }
        }
        TF_TaskChain fg_TaskChainID;
        [Association(@"TF_TaskParameterReferencesTF_TaskChain")]
        public TF_TaskChain g_TaskChainID
        {
            get { return fg_TaskChainID; }
            set { SetPropertyValue<TF_TaskChain>("g_TaskChainID", ref fg_TaskChainID, value); }
        }
        TFCode_Action fn_CodeActionID;
        [Association(@"TF_TaskParameterReferencesTFCode_Action")]
        public TFCode_Action n_CodeActionID
        {
            get { return fn_CodeActionID; }
            set { SetPropertyValue<TFCode_Action>("n_CodeActionID", ref fn_CodeActionID, value); }
        }
        string fs_ParaType;
        public string s_ParaType
        {
            get { return fs_ParaType; }
            set { SetPropertyValue<string>("s_ParaType", ref fs_ParaType, value); }
        }
        string fs_ParaValue;
        [Size(1000)]
        public string s_ParaValue
        {
            get { return fs_ParaValue; }
            set { SetPropertyValue<string>("s_ParaValue", ref fs_ParaValue, value); }
        }
        int fn_TaskChainID;
        public int n_TaskChainID
        {
            get { return fn_TaskChainID; }
            set { SetPropertyValue<int>("n_TaskChainID", ref fn_TaskChainID, value); }
        }
    }

}
