//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TF_TaskCycleConfig : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        TF_TaskChain fg_TaskChainGuid;
        [Association(@"TF_TaskCycleConfigReferencesTF_TaskChain")]
        public TF_TaskChain g_TaskChainGuid
        {
            get { return fg_TaskChainGuid; }
            set { SetPropertyValue<TF_TaskChain>("g_TaskChainGuid", ref fg_TaskChainGuid, value); }
        }
        string fs_CyclePara;
        [Size(200)]
        public string s_CyclePara
        {
            get { return fs_CyclePara; }
            set { SetPropertyValue<string>("s_CyclePara", ref fs_CyclePara, value); }
        }
        DateTime fdt_BaseDate;
        public DateTime dt_BaseDate
        {
            get { return fdt_BaseDate; }
            set { SetPropertyValue<DateTime>("dt_BaseDate", ref fdt_BaseDate, value); }
        }
        int fn_AdvanceDays;
        public int n_AdvanceDays
        {
            get { return fn_AdvanceDays; }
            set { SetPropertyValue<int>("n_AdvanceDays", ref fn_AdvanceDays, value); }
        }
        string fs_IsChanged;
        [Size(1)]
        public string s_IsChanged
        {
            get { return fs_IsChanged; }
            set { SetPropertyValue<string>("s_IsChanged", ref fs_IsChanged, value); }
        }
        DateTime fdt_OriginalBaseDate;
        public DateTime dt_OriginalBaseDate
        {
            get { return fdt_OriginalBaseDate; }
            set { SetPropertyValue<DateTime>("dt_OriginalBaseDate", ref fdt_OriginalBaseDate, value); }
        }
    }

}
