//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TF_TaskChain : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        Guid fg_CodeTaskChainGuid;
        public Guid g_CodeTaskChainGuid
        {
            get { return fg_CodeTaskChainGuid; }
            set { SetPropertyValue<Guid>("g_CodeTaskChainGuid", ref fg_CodeTaskChainGuid, value); }
        }
        string fs_Name;
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_Description;
        [Size(SizeAttribute.Unlimited)]
        public string s_Description
        {
            get { return fs_Description; }
            set { SetPropertyValue<string>("s_Description", ref fs_Description, value); }
        }
        string fs_State;
        [Size(1)]
        public string s_State
        {
            get { return fs_State; }
            set { SetPropertyValue<string>("s_State", ref fs_State, value); }
        }
        string fs_TriggerType;
        public string s_TriggerType
        {
            get { return fs_TriggerType; }
            set { SetPropertyValue<string>("s_TriggerType", ref fs_TriggerType, value); }
        }
        string fs_RelatedObjectType;
        [Size(50)]
        public string s_RelatedObjectType
        {
            get { return fs_RelatedObjectType; }
            set { SetPropertyValue<string>("s_RelatedObjectType", ref fs_RelatedObjectType, value); }
        }
        int fn_RelatedObjectID;
        public int n_RelatedObjectID
        {
            get { return fn_RelatedObjectID; }
            set { SetPropertyValue<int>("n_RelatedObjectID", ref fn_RelatedObjectID, value); }
        }
        string fs_RelatedInfo1;
        [Size(450)]
        public string s_RelatedInfo1
        {
            get { return fs_RelatedInfo1; }
            set { SetPropertyValue<string>("s_RelatedInfo1", ref fs_RelatedInfo1, value); }
        }
        string fs_RelatedInfo2;
        [Size(450)]
        public string s_RelatedInfo2
        {
            get { return fs_RelatedInfo2; }
            set { SetPropertyValue<string>("s_RelatedInfo2", ref fs_RelatedInfo2, value); }
        }
        int fn_Creator;
        public int n_Creator
        {
            get { return fn_Creator; }
            set { SetPropertyValue<int>("n_Creator", ref fn_Creator, value); }
        }
        DateTime fdt_CreateTime;
        public DateTime dt_CreateTime
        {
            get { return fdt_CreateTime; }
            set { SetPropertyValue<DateTime>("dt_CreateTime", ref fdt_CreateTime, value); }
        }
        int fn_Editor;
        public int n_Editor
        {
            get { return fn_Editor; }
            set { SetPropertyValue<int>("n_Editor", ref fn_Editor, value); }
        }
        DateTime fdt_EditTime;
        public DateTime dt_EditTime
        {
            get { return fdt_EditTime; }
            set { SetPropertyValue<DateTime>("dt_EditTime", ref fdt_EditTime, value); }
        }
        int fn_TaskChainTypeID;
        public int n_TaskChainTypeID
        {
            get { return fn_TaskChainTypeID; }
            set { SetPropertyValue<int>("n_TaskChainTypeID", ref fn_TaskChainTypeID, value); }
        }
        int fn_Num;
        public int n_Num
        {
            get { return fn_Num; }
            set { SetPropertyValue<int>("n_Num", ref fn_Num, value); }
        }
        [Association(@"TF_CustomConditionInTaskChainReferencesTF_TaskChain")]
        public XPCollection<TF_CustomConditionInTaskChain> TF_CustomConditionInTaskChains { get { return GetCollection<TF_CustomConditionInTaskChain>("TF_CustomConditionInTaskChains"); } }
        [Association(@"TF_NodeReferencesTF_TaskChain")]
        public XPCollection<TF_Node> TF_Nodes { get { return GetCollection<TF_Node>("TF_Nodes"); } }
        [Association(@"TF_NodeReferencesTF_TaskChain1")]
        public XPCollection<TF_Node> TF_Nodes1 { get { return GetCollection<TF_Node>("TF_Nodes1"); } }
        [Association(@"TF_TaskCycleConfigReferencesTF_TaskChain")]
        public XPCollection<TF_TaskCycleConfig> TF_TaskCycleConfigs { get { return GetCollection<TF_TaskCycleConfig>("TF_TaskCycleConfigs"); } }
        [Association(@"TF_TaskParameterReferencesTF_TaskChain")]
        public XPCollection<TF_TaskParameter> TF_TaskParameters { get { return GetCollection<TF_TaskParameter>("TF_TaskParameters"); } }
    }

}
