//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TF_Task : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        string fs_Name;
        [Size(300)]
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_Description;
        [Size(1000)]
        public string s_Description
        {
            get { return fs_Description; }
            set { SetPropertyValue<string>("s_Description", ref fs_Description, value); }
        }
        string fs_State;
        [Size(1)]
        public string s_State
        {
            get { return fs_State; }
            set { SetPropertyValue<string>("s_State", ref fs_State, value); }
        }
        string fs_ReadState;
        [Size(1)]
        public string s_ReadState
        {
            get { return fs_ReadState; }
            set { SetPropertyValue<string>("s_ReadState", ref fs_ReadState, value); }
        }
        int fn_Level;
        public int n_Level
        {
            get { return fn_Level; }
            set { SetPropertyValue<int>("n_Level", ref fn_Level, value); }
        }
        TFCode_TaskUrgency fn_UrgencyID;
        [Association(@"TF_TaskReferencesTFCode_TaskUrgency")]
        public TFCode_TaskUrgency n_UrgencyID
        {
            get { return fn_UrgencyID; }
            set { SetPropertyValue<TFCode_TaskUrgency>("n_UrgencyID", ref fn_UrgencyID, value); }
        }
        int fn_ExecutorID;
        public int n_ExecutorID
        {
            get { return fn_ExecutorID; }
            set { SetPropertyValue<int>("n_ExecutorID", ref fn_ExecutorID, value); }
        }
        int fn_ExecutePositionID;
        public int n_ExecutePositionID
        {
            get { return fn_ExecutePositionID; }
            set { SetPropertyValue<int>("n_ExecutePositionID", ref fn_ExecutePositionID, value); }
        }
        int fn_MentorID;
        public int n_MentorID
        {
            get { return fn_MentorID; }
            set { SetPropertyValue<int>("n_MentorID", ref fn_MentorID, value); }
        }
        DateTime fdt_FinishTime;
        public DateTime dt_FinishTime
        {
            get { return fdt_FinishTime; }
            set { SetPropertyValue<DateTime>("dt_FinishTime", ref fdt_FinishTime, value); }
        }
        DateTime fdt_StartDate;
        public DateTime dt_StartDate
        {
            get { return fdt_StartDate; }
            set { SetPropertyValue<DateTime>("dt_StartDate", ref fdt_StartDate, value); }
        }
        DateTime fdt_EndDate;
        public DateTime dt_EndDate
        {
            get { return fdt_EndDate; }
            set { SetPropertyValue<DateTime>("dt_EndDate", ref fdt_EndDate, value); }
        }
        int fn_Creator;
        public int n_Creator
        {
            get { return fn_Creator; }
            set { SetPropertyValue<int>("n_Creator", ref fn_Creator, value); }
        }
        DateTime fdt_CreateTime;
        public DateTime dt_CreateTime
        {
            get { return fdt_CreateTime; }
            set { SetPropertyValue<DateTime>("dt_CreateTime", ref fdt_CreateTime, value); }
        }
        int fn_Editor;
        public int n_Editor
        {
            get { return fn_Editor; }
            set { SetPropertyValue<int>("n_Editor", ref fn_Editor, value); }
        }
        DateTime fdt_EditTime;
        public DateTime dt_EditTime
        {
            get { return fdt_EditTime; }
            set { SetPropertyValue<DateTime>("dt_EditTime", ref fdt_EditTime, value); }
        }
        string fs_TaskConfigType;
        public string s_TaskConfigType
        {
            get { return fs_TaskConfigType; }
            set { SetPropertyValue<string>("s_TaskConfigType", ref fs_TaskConfigType, value); }
        }
        int fn_RelatedDeadlineID;
        public int n_RelatedDeadlineID
        {
            get { return fn_RelatedDeadlineID; }
            set { SetPropertyValue<int>("n_RelatedDeadlineID", ref fn_RelatedDeadlineID, value); }
        }
        int fn_MonitorEmployeeID;
        public int n_MonitorEmployeeID
        {
            get { return fn_MonitorEmployeeID; }
            set { SetPropertyValue<int>("n_MonitorEmployeeID", ref fn_MonitorEmployeeID, value); }
        }
        int fb_Monitor;
        public int b_Monitor
        {
            get { return fb_Monitor; }
            set { SetPropertyValue<int>("b_Monitor", ref fb_Monitor, value); }
        }
        string fs_Note;
        [Size(1000)]
        public string s_Note
        {
            get { return fs_Note; }
            set { SetPropertyValue<string>("s_Note", ref fs_Note, value); }
        }
        int fn_TaskTypeID;
        public int n_TaskTypeID
        {
            get { return fn_TaskTypeID; }
            set { SetPropertyValue<int>("n_TaskTypeID", ref fn_TaskTypeID, value); }
        }
        int fn_Operator;
        public int n_Operator
        {
            get { return fn_Operator; }
            set { SetPropertyValue<int>("n_Operator", ref fn_Operator, value); }
        }
        Guid fg_TaskCycleConfigGuid;
        public Guid g_TaskCycleConfigGuid
        {
            get { return fg_TaskCycleConfigGuid; }
            set { SetPropertyValue<Guid>("g_TaskCycleConfigGuid", ref fg_TaskCycleConfigGuid, value); }
        }
        int fn_Num;
        public int n_Num
        {
            get { return fn_Num; }
            set { SetPropertyValue<int>("n_Num", ref fn_Num, value); }
        }
        int fn_Finisher;
        public int n_Finisher
        {
            get { return fn_Finisher; }
            set { SetPropertyValue<int>("n_Finisher", ref fn_Finisher, value); }
        }
        string fs_Notes;
        [Size(1000)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
        string fs_ManualUpdateDeadline;
        [Size(1)]
        public string s_ManualUpdateDeadline
        {
            get { return fs_ManualUpdateDeadline; }
            set { SetPropertyValue<string>("s_ManualUpdateDeadline", ref fs_ManualUpdateDeadline, value); }
        }
        [Association(@"TF_ActionInTaskReferencesTF_Task")]
        public XPCollection<TF_ActionInTask> TF_ActionInTasks { get { return GetCollection<TF_ActionInTask>("TF_ActionInTasks"); } }
        [Association(@"TF_DemandTypeInTaskReferencesTF_Task")]
        public XPCollection<TF_DemandTypeInTask> TF_DemandTypeInTasks { get { return GetCollection<TF_DemandTypeInTask>("TF_DemandTypeInTasks"); } }
        [Association(@"TF_NodeReferencesTF_Task")]
        public XPCollection<TF_Node> TF_Nodes { get { return GetCollection<TF_Node>("TF_Nodes"); } }
        [Association(@"TF_TaskCheckReferencesTF_Task")]
        public XPCollection<TF_TaskCheck> TF_TaskChecks { get { return GetCollection<TF_TaskCheck>("TF_TaskChecks"); } }
        [Association(@"TF_TaskCheckReferencesTF_Task1")]
        public XPCollection<TF_TaskCheck> TF_TaskChecks1 { get { return GetCollection<TF_TaskCheck>("TF_TaskChecks1"); } }
        [Association(@"TF_TaskParameterReferencesTF_Task")]
        public XPCollection<TF_TaskParameter> TF_TaskParameters { get { return GetCollection<TF_TaskParameter>("TF_TaskParameters"); } }
    }

}
