//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TF_WorkItemInTaskChain : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        Guid fg_TaskChainGuid;
        public Guid g_TaskChainGuid
        {
            get { return fg_TaskChainGuid; }
            set { SetPropertyValue<Guid>("g_TaskChainGuid", ref fg_TaskChainGuid, value); }
        }
        int fn_CodeWorkItemID;
        public int n_CodeWorkItemID
        {
            get { return fn_CodeWorkItemID; }
            set { SetPropertyValue<int>("n_CodeWorkItemID", ref fn_CodeWorkItemID, value); }
        }
        string fs_Description;
        [Size(1000)]
        public string s_Description
        {
            get { return fs_Description; }
            set { SetPropertyValue<string>("s_Description", ref fs_Description, value); }
        }
        string fs_Note;
        [Size(1000)]
        public string s_Note
        {
            get { return fs_Note; }
            set { SetPropertyValue<string>("s_Note", ref fs_Note, value); }
        }
        int fn_RelatedFileID;
        public int n_RelatedFileID
        {
            get { return fn_RelatedFileID; }
            set { SetPropertyValue<int>("n_RelatedFileID", ref fn_RelatedFileID, value); }
        }
        decimal fn_EstimateValue;
        public decimal n_EstimateValue
        {
            get { return fn_EstimateValue; }
            set { SetPropertyValue<decimal>("n_EstimateValue", ref fn_EstimateValue, value); }
        }
        int fn_EstimateValueRecorder;
        public int n_EstimateValueRecorder
        {
            get { return fn_EstimateValueRecorder; }
            set { SetPropertyValue<int>("n_EstimateValueRecorder", ref fn_EstimateValueRecorder, value); }
        }
        string fs_EstimateValueNote;
        [Size(1000)]
        public string s_EstimateValueNote
        {
            get { return fs_EstimateValueNote; }
            set { SetPropertyValue<string>("s_EstimateValueNote", ref fs_EstimateValueNote, value); }
        }
        DateTime fdt_EstimateValueTime;
        public DateTime dt_EstimateValueTime
        {
            get { return fdt_EstimateValueTime; }
            set { SetPropertyValue<DateTime>("dt_EstimateValueTime", ref fdt_EstimateValueTime, value); }
        }
        decimal fn_ActualValue;
        public decimal n_ActualValue
        {
            get { return fn_ActualValue; }
            set { SetPropertyValue<decimal>("n_ActualValue", ref fn_ActualValue, value); }
        }
        int fn_ActualValueRecorder;
        public int n_ActualValueRecorder
        {
            get { return fn_ActualValueRecorder; }
            set { SetPropertyValue<int>("n_ActualValueRecorder", ref fn_ActualValueRecorder, value); }
        }
        string fs_ActualValueNote;
        [Size(1000)]
        public string s_ActualValueNote
        {
            get { return fs_ActualValueNote; }
            set { SetPropertyValue<string>("s_ActualValueNote", ref fs_ActualValueNote, value); }
        }
        DateTime fdt_ActualValueTime;
        public DateTime dt_ActualValueTime
        {
            get { return fdt_ActualValueTime; }
            set { SetPropertyValue<DateTime>("dt_ActualValueTime", ref fdt_ActualValueTime, value); }
        }
        int fn_Status;
        public int n_Status
        {
            get { return fn_Status; }
            set { SetPropertyValue<int>("n_Status", ref fn_Status, value); }
        }
        decimal fn_ActualServiceValue;
        public decimal n_ActualServiceValue
        {
            get { return fn_ActualServiceValue; }
            set { SetPropertyValue<decimal>("n_ActualServiceValue", ref fn_ActualServiceValue, value); }
        }
        int fn_HasCharge;
        public int n_HasCharge
        {
            get { return fn_HasCharge; }
            set { SetPropertyValue<int>("n_HasCharge", ref fn_HasCharge, value); }
        }
        DateTime fdt_ChargeTime;
        public DateTime dt_ChargeTime
        {
            get { return fdt_ChargeTime; }
            set { SetPropertyValue<DateTime>("dt_ChargeTime", ref fdt_ChargeTime, value); }
        }
        int fn_ChargeRecorder;
        public int n_ChargeRecorder
        {
            get { return fn_ChargeRecorder; }
            set { SetPropertyValue<int>("n_ChargeRecorder", ref fn_ChargeRecorder, value); }
        }
        int fn_HasOfeeCharge;
        public int n_HasOfeeCharge
        {
            get { return fn_HasOfeeCharge; }
            set { SetPropertyValue<int>("n_HasOfeeCharge", ref fn_HasOfeeCharge, value); }
        }
        DateTime fdt_OfeeChargeTime;
        public DateTime dt_OfeeChargeTime
        {
            get { return fdt_OfeeChargeTime; }
            set { SetPropertyValue<DateTime>("dt_OfeeChargeTime", ref fdt_OfeeChargeTime, value); }
        }
        int fn_OfeeChargeRecorder;
        public int n_OfeeChargeRecorder
        {
            get { return fn_OfeeChargeRecorder; }
            set { SetPropertyValue<int>("n_OfeeChargeRecorder", ref fn_OfeeChargeRecorder, value); }
        }
        Guid fg_TaskGuid;
        public Guid g_TaskGuid
        {
            get { return fg_TaskGuid; }
            set { SetPropertyValue<Guid>("g_TaskGuid", ref fg_TaskGuid, value); }
        }
    }

}
