//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_Node : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        TFCode_TaskChain fg_CodeTaskChainGuid;
        [Association(@"TFCode_NodeReferencesTFCode_TaskChain")]
        public TFCode_TaskChain g_CodeTaskChainGuid
        {
            get { return fg_CodeTaskChainGuid; }
            set { SetPropertyValue<TFCode_TaskChain>("g_CodeTaskChainGuid", ref fg_CodeTaskChainGuid, value); }
        }
        string fs_Type;
        [Size(1)]
        public string s_Type
        {
            get { return fs_Type; }
            set { SetPropertyValue<string>("s_Type", ref fs_Type, value); }
        }
        TFCode_TaskChain fg_OwnCodeTaskChainGuid;
        [Association(@"TFCode_NodeReferencesTFCode_TaskChain1")]
        public TFCode_TaskChain g_OwnCodeTaskChainGuid
        {
            get { return fg_OwnCodeTaskChainGuid; }
            set { SetPropertyValue<TFCode_TaskChain>("g_OwnCodeTaskChainGuid", ref fg_OwnCodeTaskChainGuid, value); }
        }
        TFCode_Task fg_OwnCodeTaskGuid;
        [Association(@"TFCode_NodeReferencesTFCode_Task")]
        public TFCode_Task g_OwnCodeTaskGuid
        {
            get { return fg_OwnCodeTaskGuid; }
            set { SetPropertyValue<TFCode_Task>("g_OwnCodeTaskGuid", ref fg_OwnCodeTaskGuid, value); }
        }
        string fs_PreGenerate;
        [Size(1)]
        public string s_PreGenerate
        {
            get { return fs_PreGenerate; }
            set { SetPropertyValue<string>("s_PreGenerate", ref fs_PreGenerate, value); }
        }
        string fs_PreCondition;
        [Size(2000)]
        public string s_PreCondition
        {
            get { return fs_PreCondition; }
            set { SetPropertyValue<string>("s_PreCondition", ref fs_PreCondition, value); }
        }
        string fs_Code;
        [Size(21)]
        public string s_Code
        {
            get { return fs_Code; }
            set { SetPropertyValue<string>("s_Code", ref fs_Code, value); }
        }
        [Association(@"TFCode_NodeRelationReferencesTFCode_Node")]
        public XPCollection<TFCode_NodeRelation> TFCode_NodeRelations { get { return GetCollection<TFCode_NodeRelation>("TFCode_NodeRelations"); } }
        [Association(@"TFCode_NodeRelationReferencesTFCode_Node1")]
        public XPCollection<TFCode_NodeRelation> TFCode_NodeRelations1 { get { return GetCollection<TFCode_NodeRelation>("TFCode_NodeRelations1"); } }
    }

}
