//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_Deadline : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        string fs_Name;
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_Type;
        [Size(50)]
        public string s_Type
        {
            get { return fs_Type; }
            set { SetPropertyValue<string>("s_Type", ref fs_Type, value); }
        }
        string fs_ValueRule;
        [Size(50)]
        public string s_ValueRule
        {
            get { return fs_ValueRule; }
            set { SetPropertyValue<string>("s_ValueRule", ref fs_ValueRule, value); }
        }
        string fs_Description;
        [Size(1000)]
        public string s_Description
        {
            get { return fs_Description; }
            set { SetPropertyValue<string>("s_Description", ref fs_Description, value); }
        }
        string fs_Classification;
        [Size(50)]
        public string s_Classification
        {
            get { return fs_Classification; }
            set { SetPropertyValue<string>("s_Classification", ref fs_Classification, value); }
        }
        string fs_AllowEdit;
        [Size(1)]
        public string s_AllowEdit
        {
            get { return fs_AllowEdit; }
            set { SetPropertyValue<string>("s_AllowEdit", ref fs_AllowEdit, value); }
        }
        string fs_StoredProcedure;
        [Size(500)]
        public string s_StoredProcedure
        {
            get { return fs_StoredProcedure; }
            set { SetPropertyValue<string>("s_StoredProcedure", ref fs_StoredProcedure, value); }
        }
        [Association(@"TF_DeadlineReferencesTFCode_Deadline")]
        public XPCollection<TF_Deadline> TF_Deadlines { get { return GetCollection<TF_Deadline>("TF_Deadlines"); } }
        [Association(@"TFCode_BaseDateInCodeDeadlineReferencesTFCode_Deadline")]
        public XPCollection<TFCode_BaseDateInCodeDeadline> TFCode_BaseDateInCodeDeadlines { get { return GetCollection<TFCode_BaseDateInCodeDeadline>("TFCode_BaseDateInCodeDeadlines"); } }
        [Association(@"TFCode_DeadlineInCodeTaskReferencesTFCode_Deadline")]
        public XPCollection<TFCode_DeadlineInCodeTask> TFCode_DeadlineInCodeTasks { get { return GetCollection<TFCode_DeadlineInCodeTask>("TFCode_DeadlineInCodeTasks"); } }
        [Association(@"TFCode_DeadlineInCodeTaskChainReferencesTFCode_Deadline")]
        public XPCollection<TFCode_DeadlineInCodeTaskChain> TFCode_DeadlineInCodeTaskChains { get { return GetCollection<TFCode_DeadlineInCodeTaskChain>("TFCode_DeadlineInCodeTaskChains"); } }
    }

}
