//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_BaseDateInCodeDeadline : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TFCode_Deadline fg_CodeDeadlineID;
        [Association(@"TFCode_BaseDateInCodeDeadlineReferencesTFCode_Deadline")]
        public TFCode_Deadline g_CodeDeadlineID
        {
            get { return fg_CodeDeadlineID; }
            set { SetPropertyValue<TFCode_Deadline>("g_CodeDeadlineID", ref fg_CodeDeadlineID, value); }
        }
        TFCode_BaseDate fn_CodeBaseDateID;
        [Association(@"TFCode_BaseDateInCodeDeadlineReferencesTFCode_BaseDate")]
        public TFCode_BaseDate n_CodeBaseDateID
        {
            get { return fn_CodeBaseDateID; }
            set { SetPropertyValue<TFCode_BaseDate>("n_CodeBaseDateID", ref fn_CodeBaseDateID, value); }
        }
        string fs_CalcRule;
        [Size(50)]
        public string s_CalcRule
        {
            get { return fs_CalcRule; }
            set { SetPropertyValue<string>("s_CalcRule", ref fs_CalcRule, value); }
        }
        int fn_Month;
        public int n_Month
        {
            get { return fn_Month; }
            set { SetPropertyValue<int>("n_Month", ref fn_Month, value); }
        }
        int fn_Day;
        public int n_Day
        {
            get { return fn_Day; }
            set { SetPropertyValue<int>("n_Day", ref fn_Day, value); }
        }
    }

}
