//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_Task : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        string fs_Name;
        [Size(300)]
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_Description;
        [Size(500)]
        public string s_Description
        {
            get { return fs_Description; }
            set { SetPropertyValue<string>("s_Description", ref fs_Description, value); }
        }
        TFCode_TaskType fn_TaskTypeID;
        [Association(@"TFCode_TaskReferencesTFCode_TaskType")]
        public TFCode_TaskType n_TaskTypeID
        {
            get { return fn_TaskTypeID; }
            set { SetPropertyValue<TFCode_TaskType>("n_TaskTypeID", ref fn_TaskTypeID, value); }
        }
        int fn_DemandTypeID;
        public int n_DemandTypeID
        {
            get { return fn_DemandTypeID; }
            set { SetPropertyValue<int>("n_DemandTypeID", ref fn_DemandTypeID, value); }
        }
        int fn_Level;
        public int n_Level
        {
            get { return fn_Level; }
            set { SetPropertyValue<int>("n_Level", ref fn_Level, value); }
        }
        string fs_ExecutorType;
        [Size(1)]
        public string s_ExecutorType
        {
            get { return fs_ExecutorType; }
            set { SetPropertyValue<string>("s_ExecutorType", ref fs_ExecutorType, value); }
        }
        string fs_ExecutorValue;
        [Size(500)]
        public string s_ExecutorValue
        {
            get { return fs_ExecutorValue; }
            set { SetPropertyValue<string>("s_ExecutorValue", ref fs_ExecutorValue, value); }
        }
        string fs_FinishCondition;
        [Size(2000)]
        public string s_FinishCondition
        {
            get { return fs_FinishCondition; }
            set { SetPropertyValue<string>("s_FinishCondition", ref fs_FinishCondition, value); }
        }
        string fs_StartDateCalcRule;
        [Size(50)]
        public string s_StartDateCalcRule
        {
            get { return fs_StartDateCalcRule; }
            set { SetPropertyValue<string>("s_StartDateCalcRule", ref fs_StartDateCalcRule, value); }
        }
        string fs_StartDateTaskCode;
        [Size(21)]
        public string s_StartDateTaskCode
        {
            get { return fs_StartDateTaskCode; }
            set { SetPropertyValue<string>("s_StartDateTaskCode", ref fs_StartDateTaskCode, value); }
        }
        string fs_StartDateTaskDateType;
        [Size(50)]
        public string s_StartDateTaskDateType
        {
            get { return fs_StartDateTaskDateType; }
            set { SetPropertyValue<string>("s_StartDateTaskDateType", ref fs_StartDateTaskDateType, value); }
        }
        Guid fg_StartCodeDeadlineGuid;
        public Guid g_StartCodeDeadlineGuid
        {
            get { return fg_StartCodeDeadlineGuid; }
            set { SetPropertyValue<Guid>("g_StartCodeDeadlineGuid", ref fg_StartCodeDeadlineGuid, value); }
        }
        int fn_StartDateValue1;
        public int n_StartDateValue1
        {
            get { return fn_StartDateValue1; }
            set { SetPropertyValue<int>("n_StartDateValue1", ref fn_StartDateValue1, value); }
        }
        string fs_StartDateType1;
        [Size(50)]
        public string s_StartDateType1
        {
            get { return fs_StartDateType1; }
            set { SetPropertyValue<string>("s_StartDateType1", ref fs_StartDateType1, value); }
        }
        int fn_StartDateValue2;
        public int n_StartDateValue2
        {
            get { return fn_StartDateValue2; }
            set { SetPropertyValue<int>("n_StartDateValue2", ref fn_StartDateValue2, value); }
        }
        string fs_StartDateType2;
        [Size(50)]
        public string s_StartDateType2
        {
            get { return fs_StartDateType2; }
            set { SetPropertyValue<string>("s_StartDateType2", ref fs_StartDateType2, value); }
        }
        string fs_EndDateCalcRule;
        [Size(50)]
        public string s_EndDateCalcRule
        {
            get { return fs_EndDateCalcRule; }
            set { SetPropertyValue<string>("s_EndDateCalcRule", ref fs_EndDateCalcRule, value); }
        }
        string fs_EndDateTaskCode;
        [Size(21)]
        public string s_EndDateTaskCode
        {
            get { return fs_EndDateTaskCode; }
            set { SetPropertyValue<string>("s_EndDateTaskCode", ref fs_EndDateTaskCode, value); }
        }
        string fs_EndDateTaskDateType;
        [Size(50)]
        public string s_EndDateTaskDateType
        {
            get { return fs_EndDateTaskDateType; }
            set { SetPropertyValue<string>("s_EndDateTaskDateType", ref fs_EndDateTaskDateType, value); }
        }
        Guid fg_EndCodeDeadlineGuid;
        public Guid g_EndCodeDeadlineGuid
        {
            get { return fg_EndCodeDeadlineGuid; }
            set { SetPropertyValue<Guid>("g_EndCodeDeadlineGuid", ref fg_EndCodeDeadlineGuid, value); }
        }
        int fn_EndDateValue1;
        public int n_EndDateValue1
        {
            get { return fn_EndDateValue1; }
            set { SetPropertyValue<int>("n_EndDateValue1", ref fn_EndDateValue1, value); }
        }
        string fs_EndDateType1;
        [Size(50)]
        public string s_EndDateType1
        {
            get { return fs_EndDateType1; }
            set { SetPropertyValue<string>("s_EndDateType1", ref fs_EndDateType1, value); }
        }
        int fn_EndDateValue2;
        public int n_EndDateValue2
        {
            get { return fn_EndDateValue2; }
            set { SetPropertyValue<int>("n_EndDateValue2", ref fn_EndDateValue2, value); }
        }
        string fs_EndDateType2;
        [Size(50)]
        public string s_EndDateType2
        {
            get { return fs_EndDateType2; }
            set { SetPropertyValue<string>("s_EndDateType2", ref fs_EndDateType2, value); }
        }
        Guid fg_EndFinallyCodeDeadlineGuid;
        public Guid g_EndFinallyCodeDeadlineGuid
        {
            get { return fg_EndFinallyCodeDeadlineGuid; }
            set { SetPropertyValue<Guid>("g_EndFinallyCodeDeadlineGuid", ref fg_EndFinallyCodeDeadlineGuid, value); }
        }
        [Association(@"TFCode_ActionInCodeTaskReferencesTFCode_Task")]
        public XPCollection<TFCode_ActionInCodeTask> TFCode_ActionInCodeTasks { get { return GetCollection<TFCode_ActionInCodeTask>("TFCode_ActionInCodeTasks"); } }
        [Association(@"TFCode_DeadlineInCodeTaskReferencesTFCode_Task")]
        public XPCollection<TFCode_DeadlineInCodeTask> TFCode_DeadlineInCodeTasks { get { return GetCollection<TFCode_DeadlineInCodeTask>("TFCode_DeadlineInCodeTasks"); } }
        [Association(@"TFCode_DemandTypeInCodeTaskReferencesTFCode_Task")]
        public XPCollection<TFCode_DemandTypeInCodeTask> TFCode_DemandTypeInCodeTasks { get { return GetCollection<TFCode_DemandTypeInCodeTask>("TFCode_DemandTypeInCodeTasks"); } }
        [Association(@"TFCode_NodeReferencesTFCode_Task")]
        public XPCollection<TFCode_Node> TFCode_Nodes { get { return GetCollection<TFCode_Node>("TFCode_Nodes"); } }
        [Association(@"TFCode_TaskGenerateFeeReferencesTFCode_Task")]
        public XPCollection<TFCode_TaskGenerateFee> TFCode_TaskGenerateFees { get { return GetCollection<TFCode_TaskGenerateFee>("TFCode_TaskGenerateFees"); } }
        [Association(@"TFCode_TaskTriggerTaskChainReferencesTFCode_Task")]
        public XPCollection<TFCode_TaskTriggerTaskChain> TFCode_TaskTriggerTaskChains { get { return GetCollection<TFCode_TaskTriggerTaskChain>("TFCode_TaskTriggerTaskChains"); } }
    }

}
