//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_WorkItem : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        string fs_Name;
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_Unit;
        public string s_Unit
        {
            get { return fs_Unit; }
            set { SetPropertyValue<string>("s_Unit", ref fs_Unit, value); }
        }
        string fs_Description;
        [Size(1000)]
        public string s_Description
        {
            get { return fs_Description; }
            set { SetPropertyValue<string>("s_Description", ref fs_Description, value); }
        }
        int fn_TypeID;
        public int n_TypeID
        {
            get { return fn_TypeID; }
            set { SetPropertyValue<int>("n_TypeID", ref fn_TypeID, value); }
        }
        int fn_CodeFeeID;
        public int n_CodeFeeID
        {
            get { return fn_CodeFeeID; }
            set { SetPropertyValue<int>("n_CodeFeeID", ref fn_CodeFeeID, value); }
        }
        string fs_ConvertToFeeMethod;
        [Size(1)]
        public string s_ConvertToFeeMethod
        {
            get { return fs_ConvertToFeeMethod; }
            set { SetPropertyValue<string>("s_ConvertToFeeMethod", ref fs_ConvertToFeeMethod, value); }
        }
        [Association(@"TFCode_WorkItemInCodeTaskChainReferencesTFCode_WorkItem")]
        public XPCollection<TFCode_WorkItemInCodeTaskChain> TFCode_WorkItemInCodeTaskChains { get { return GetCollection<TFCode_WorkItemInCodeTaskChain>("TFCode_WorkItemInCodeTaskChains"); } }
    }

}
