//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_TaskChainLayout : TFCode_TaskChain
    {
        string fs_Layout;
        [Size(SizeAttribute.Unlimited)]
        public string s_Layout
        {
            get { return fs_Layout; }
            set { SetPropertyValue<string>("s_Layout", ref fs_Layout, value); }
        }
    }

}
