//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_CaseProcessInCodeTaskChain : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        Guid fg_CodeTaskGuid;
        public Guid g_CodeTaskGuid
        {
            get { return fg_CodeTaskGuid; }
            set { SetPropertyValue<Guid>("g_CodeTaskGuid", ref fg_CodeTaskGuid, value); }
        }
        int fn_CodeCaseProcessID;
        public int n_CodeCaseProcessID
        {
            get { return fn_CodeCaseProcessID; }
            set { SetPropertyValue<int>("n_CodeCaseProcessID", ref fn_CodeCaseProcessID, value); }
        }
        int fn_CodeCaseProcessItemID;
        public int n_CodeCaseProcessItemID
        {
            get { return fn_CodeCaseProcessItemID; }
            set { SetPropertyValue<int>("n_CodeCaseProcessItemID", ref fn_CodeCaseProcessItemID, value); }
        }
        string fs_When;
        [Size(5)]
        public string s_When
        {
            get { return fs_When; }
            set { SetPropertyValue<string>("s_When", ref fs_When, value); }
        }
    }

}
