//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_DemandType : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        string fs_Name;
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_Description;
        [Size(1000)]
        public string s_Description
        {
            get { return fs_Description; }
            set { SetPropertyValue<string>("s_Description", ref fs_Description, value); }
        }
        [Association(@"TF_DemandTypeInTaskReferencesTFCode_DemandType")]
        public XPCollection<TF_DemandTypeInTask> TF_DemandTypeInTasks { get { return GetCollection<TF_DemandTypeInTask>("TF_DemandTypeInTasks"); } }
        [Association(@"TFCode_DemandReferencesTFCode_DemandType")]
        public XPCollection<TFCode_Demand> TFCode_Demands { get { return GetCollection<TFCode_Demand>("TFCode_Demands"); } }
        [Association(@"TFCode_DemandTypeInCodeTaskReferencesTFCode_DemandType")]
        public XPCollection<TFCode_DemandTypeInCodeTask> TFCode_DemandTypeInCodeTasks { get { return GetCollection<TFCode_DemandTypeInCodeTask>("TFCode_DemandTypeInCodeTasks"); } }
    }

}
