//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_TaskGenerateFee : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        TFCode_Task fg_CodeTaskGuid;
        [Association(@"TFCode_TaskGenerateFeeReferencesTFCode_Task")]
        public TFCode_Task g_CodeTaskGuid
        {
            get { return fg_CodeTaskGuid; }
            set { SetPropertyValue<TFCode_Task>("g_CodeTaskGuid", ref fg_CodeTaskGuid, value); }
        }
        int fn_CodeFeeID;
        public int n_CodeFeeID
        {
            get { return fn_CodeFeeID; }
            set { SetPropertyValue<int>("n_CodeFeeID", ref fn_CodeFeeID, value); }
        }
        string fs_GenerateTime;
        [Size(1)]
        public string s_GenerateTime
        {
            get { return fs_GenerateTime; }
            set { SetPropertyValue<string>("s_GenerateTime", ref fs_GenerateTime, value); }
        }
        string fs_GenerateCondition;
        [Size(2000)]
        public string s_GenerateCondition
        {
            get { return fs_GenerateCondition; }
            set { SetPropertyValue<string>("s_GenerateCondition", ref fs_GenerateCondition, value); }
        }
    }

}
