//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_DeadlineInCodeTaskChain : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        TFCode_TaskChain fg_CodeTaskChainGuid;
        [Association(@"TFCode_DeadlineInCodeTaskChainReferencesTFCode_TaskChain")]
        public TFCode_TaskChain g_CodeTaskChainGuid
        {
            get { return fg_CodeTaskChainGuid; }
            set { SetPropertyValue<TFCode_TaskChain>("g_CodeTaskChainGuid", ref fg_CodeTaskChainGuid, value); }
        }
        TFCode_Deadline fg_CodeDeadlineID;
        [Association(@"TFCode_DeadlineInCodeTaskChainReferencesTFCode_Deadline")]
        public TFCode_Deadline g_CodeDeadlineID
        {
            get { return fg_CodeDeadlineID; }
            set { SetPropertyValue<TFCode_Deadline>("g_CodeDeadlineID", ref fg_CodeDeadlineID, value); }
        }
    }

}
