//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_BaseDate : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        string fs_Name;
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_ObjectType;
        [Size(50)]
        public string s_ObjectType
        {
            get { return fs_ObjectType; }
            set { SetPropertyValue<string>("s_ObjectType", ref fs_ObjectType, value); }
        }
        string fs_NameSpace;
        [Size(500)]
        public string s_NameSpace
        {
            get { return fs_NameSpace; }
            set { SetPropertyValue<string>("s_NameSpace", ref fs_NameSpace, value); }
        }
        string fs_FieldName;
        [Size(50)]
        public string s_FieldName
        {
            get { return fs_FieldName; }
            set { SetPropertyValue<string>("s_FieldName", ref fs_FieldName, value); }
        }
        [Association(@"TFCode_BaseDateInCodeDeadlineReferencesTFCode_BaseDate")]
        public XPCollection<TFCode_BaseDateInCodeDeadline> TFCode_BaseDateInCodeDeadlines { get { return GetCollection<TFCode_BaseDateInCodeDeadline>("TFCode_BaseDateInCodeDeadlines"); } }
    }

}
