//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_Action : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        string fs_Name;
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_Type;
        [Size(50)]
        public string s_Type
        {
            get { return fs_Type; }
            set { SetPropertyValue<string>("s_Type", ref fs_Type, value); }
        }
        string fs_FuncNameSpace;
        [Size(500)]
        public string s_FuncNameSpace
        {
            get { return fs_FuncNameSpace; }
            set { SetPropertyValue<string>("s_FuncNameSpace", ref fs_FuncNameSpace, value); }
        }
        string fs_FuncName;
        [Size(500)]
        public string s_FuncName
        {
            get { return fs_FuncName; }
            set { SetPropertyValue<string>("s_FuncName", ref fs_FuncName, value); }
        }
        string fs_DefaultParamIn;
        [Size(50)]
        public string s_DefaultParamIn
        {
            get { return fs_DefaultParamIn; }
            set { SetPropertyValue<string>("s_DefaultParamIn", ref fs_DefaultParamIn, value); }
        }
        string fs_Description;
        [Size(1000)]
        public string s_Description
        {
            get { return fs_Description; }
            set { SetPropertyValue<string>("s_Description", ref fs_Description, value); }
        }
        [Association(@"TF_ActionInTaskReferencesTFCode_Action")]
        public XPCollection<TF_ActionInTask> TF_ActionInTasks { get { return GetCollection<TF_ActionInTask>("TF_ActionInTasks"); } }
        [Association(@"TF_TaskParameterReferencesTFCode_Action")]
        public XPCollection<TF_TaskParameter> TF_TaskParameters { get { return GetCollection<TF_TaskParameter>("TF_TaskParameters"); } }
        [Association(@"TFCode_ActionInCodeTaskReferencesTFCode_Action")]
        public XPCollection<TFCode_ActionInCodeTask> TFCode_ActionInCodeTasks { get { return GetCollection<TFCode_ActionInCodeTask>("TFCode_ActionInCodeTasks"); } }
    }

}
