//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_NodeRelation : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        string fs_Name;
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_Description;
        [Size(1000)]
        public string s_Description
        {
            get { return fs_Description; }
            set { SetPropertyValue<string>("s_Description", ref fs_Description, value); }
        }
        TFCode_TaskChain fg_CodeTaskChainGuid;
        [Association(@"TFCode_NodeRelationReferencesTFCode_TaskChain")]
        public TFCode_TaskChain g_CodeTaskChainGuid
        {
            get { return fg_CodeTaskChainGuid; }
            set { SetPropertyValue<TFCode_TaskChain>("g_CodeTaskChainGuid", ref fg_CodeTaskChainGuid, value); }
        }
        TFCode_Node fg_FromNodeGuid;
        [Association(@"TFCode_NodeRelationReferencesTFCode_Node")]
        public TFCode_Node g_FromNodeGuid
        {
            get { return fg_FromNodeGuid; }
            set { SetPropertyValue<TFCode_Node>("g_FromNodeGuid", ref fg_FromNodeGuid, value); }
        }
        TFCode_Node fg_ToNodeGuid;
        [Association(@"TFCode_NodeRelationReferencesTFCode_Node1")]
        public TFCode_Node g_ToNodeGuid
        {
            get { return fg_ToNodeGuid; }
            set { SetPropertyValue<TFCode_Node>("g_ToNodeGuid", ref fg_ToNodeGuid, value); }
        }
        string fs_Condition;
        [Size(2000)]
        public string s_Condition
        {
            get { return fs_Condition; }
            set { SetPropertyValue<string>("s_Condition", ref fs_Condition, value); }
        }
        string fs_Reopen;
        [Size(1)]
        public string s_Reopen
        {
            get { return fs_Reopen; }
            set { SetPropertyValue<string>("s_Reopen", ref fs_Reopen, value); }
        }
    }

}
