//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_DeadlineInCodeTask : XPLiteObject
    {
        Guid fg_ID;
        [Key(true)]
        public Guid g_ID
        {
            get { return fg_ID; }
            set { SetPropertyValue<Guid>("g_ID", ref fg_ID, value); }
        }
        TFCode_Task fg_CodeTaskGuid;
        [Association(@"TFCode_DeadlineInCodeTaskReferencesTFCode_Task")]
        public TFCode_Task g_CodeTaskGuid
        {
            get { return fg_CodeTaskGuid; }
            set { SetPropertyValue<TFCode_Task>("g_CodeTaskGuid", ref fg_CodeTaskGuid, value); }
        }
        TFCode_Deadline fg_CodeDeadlineID;
        [Association(@"TFCode_DeadlineInCodeTaskReferencesTFCode_Deadline")]
        public TFCode_Deadline g_CodeDeadlineID
        {
            get { return fg_CodeDeadlineID; }
            set { SetPropertyValue<TFCode_Deadline>("g_CodeDeadlineID", ref fg_CodeDeadlineID, value); }
        }
        string fs_UpdateTime;
        [Size(1)]
        public string s_UpdateTime
        {
            get { return fs_UpdateTime; }
            set { SetPropertyValue<string>("s_UpdateTime", ref fs_UpdateTime, value); }
        }
    }

}
