//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TFCode_Demand : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        string fs_Name;
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        TFCode_DemandType fn_DemandTypeID;
        [Association(@"TFCode_DemandReferencesTFCode_DemandType")]
        public TFCode_DemandType n_DemandTypeID
        {
            get { return fn_DemandTypeID; }
            set { SetPropertyValue<TFCode_DemandType>("n_DemandTypeID", ref fn_DemandTypeID, value); }
        }
    }

}
