//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_CustomMemo : XPLiteObject
    {
        int fn_CaseID;
        [Key]
        public int n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<int>("n_CaseID", ref fn_CaseID, value); }
        }
        string fs_Name;
        [Size(300)]
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_LicenseNum;
        [Size(30)]
        public string s_LicenseNum
        {
            get { return fs_LicenseNum; }
            set { SetPropertyValue<string>("s_LicenseNum", ref fs_LicenseNum, value); }
        }
        DateTime fdt_ExpiredDate;
        public DateTime dt_ExpiredDate
        {
            get { return fdt_ExpiredDate; }
            set { SetPropertyValue<DateTime>("dt_ExpiredDate", ref fdt_ExpiredDate, value); }
        }
        string fs_Note;
        [Size(600)]
        public string s_Note
        {
            get { return fs_Note; }
            set { SetPropertyValue<string>("s_Note", ref fs_Note, value); }
        }
        string fs_AttachedFiles;
        [Size(15)]
        public string s_AttachedFiles
        {
            get { return fs_AttachedFiles; }
            set { SetPropertyValue<string>("s_AttachedFiles", ref fs_AttachedFiles, value); }
        }
        string fs_OtherClaim;
        [Size(600)]
        public string s_OtherClaim
        {
            get { return fs_OtherClaim; }
            set { SetPropertyValue<string>("s_OtherClaim", ref fs_OtherClaim, value); }
        }
        string fs_AppNum;
        [Size(60)]
        public string s_AppNum
        {
            get { return fs_AppNum; }
            set { SetPropertyValue<string>("s_AppNum", ref fs_AppNum, value); }
        }
        DateTime fdt_ReceiveDate;
        public DateTime dt_ReceiveDate
        {
            get { return fdt_ReceiveDate; }
            set { SetPropertyValue<DateTime>("dt_ReceiveDate", ref fdt_ReceiveDate, value); }
        }
        string fs_MemoName;
        [Size(300)]
        public string s_MemoName
        {
            get { return fs_MemoName; }
            set { SetPropertyValue<string>("s_MemoName", ref fs_MemoName, value); }
        }
        DateTime fdt_CheckDate;
        public DateTime dt_CheckDate
        {
            get { return fdt_CheckDate; }
            set { SetPropertyValue<DateTime>("dt_CheckDate", ref fdt_CheckDate, value); }
        }
        DateTime fdt_ConfirmDate;
        public DateTime dt_ConfirmDate
        {
            get { return fdt_ConfirmDate; }
            set { SetPropertyValue<DateTime>("dt_ConfirmDate", ref fdt_ConfirmDate, value); }
        }
        string fs_MemoNum;
        [Size(30)]
        public string s_MemoNum
        {
            get { return fs_MemoNum; }
            set { SetPropertyValue<string>("s_MemoNum", ref fs_MemoNum, value); }
        }
        DateTime fdt_MemoExpireDate;
        public DateTime dt_MemoExpireDate
        {
            get { return fdt_MemoExpireDate; }
            set { SetPropertyValue<DateTime>("dt_MemoExpireDate", ref fdt_MemoExpireDate, value); }
        }
        [Association(@"TPCase_TortiousWareReferencesTPCase_CustomMemo")]
        public XPCollection<TPCase_TortiousWare> TPCase_TortiousWares { get { return GetCollection<TPCase_TortiousWare>("TPCase_TortiousWares"); } }
    }

}
