//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_Inventor : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TPCase_Patent fn_CaseID;
        [Association(@"TPCase_InventorReferencesTPCase_Patent")]
        public TPCase_Patent n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TPCase_Patent>("n_CaseID", ref fn_CaseID, value); }
        }
        int fn_Sequence;
        public int n_Sequence
        {
            get { return fn_Sequence; }
            set { SetPropertyValue<int>("n_Sequence", ref fn_Sequence, value); }
        }
        string fs_Name;
        [Size(300)]
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_NativeName;
        [Size(300)]
        public string s_NativeName
        {
            get { return fs_NativeName; }
            set { SetPropertyValue<string>("s_NativeName", ref fs_NativeName, value); }
        }
        int fn_Country;
        public int n_Country
        {
            get { return fn_Country; }
            set { SetPropertyValue<int>("n_Country", ref fn_Country, value); }
        }
        string fs_Address;
        [Size(300)]
        public string s_Address
        {
            get { return fs_Address; }
            set { SetPropertyValue<string>("s_Address", ref fs_Address, value); }
        }
        string fs_NativeAddress;
        [Size(300)]
        public string s_NativeAddress
        {
            get { return fs_NativeAddress; }
            set { SetPropertyValue<string>("s_NativeAddress", ref fs_NativeAddress, value); }
        }
        string fs_IDCard;
        [Size(50)]
        public string s_IDCard
        {
            get { return fs_IDCard; }
            set { SetPropertyValue<string>("s_IDCard", ref fs_IDCard, value); }
        }
        int fPatent;
        [Indexed(Name = @"iPatent_TPCase_Inventor")]
        public int Patent
        {
            get { return fPatent; }
            set { SetPropertyValue<int>("Patent", ref fPatent, value); }
        }
        string fs_SecretName;
        [Size(1)]
        public string s_SecretName
        {
            get { return fs_SecretName; }
            set { SetPropertyValue<string>("s_SecretName", ref fs_SecretName, value); }
        }
        string fs_OtherName;
        [Size(500)]
        public string s_OtherName
        {
            get { return fs_OtherName; }
            set { SetPropertyValue<string>("s_OtherName", ref fs_OtherName, value); }
        }
        string fs_OtherAddr;
        [Size(500)]
        public string s_OtherAddr
        {
            get { return fs_OtherAddr; }
            set { SetPropertyValue<string>("s_OtherAddr", ref fs_OtherAddr, value); }
        }
        string fs_Notes;
        [Size(500)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
    }

}
