//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_PermitPatents : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TPCase_PermitMemo fn_CaseID;
        [Association(@"TPCase_PermitPatentsReferencesTPCase_PermitMemo")]
        public TPCase_PermitMemo n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TPCase_PermitMemo>("n_CaseID", ref fn_CaseID, value); }
        }
        string fs_PatentNum;
        [Size(50)]
        public string s_PatentNum
        {
            get { return fs_PatentNum; }
            set { SetPropertyValue<string>("s_PatentNum", ref fs_PatentNum, value); }
        }
        string fs_PatentName;
        [Size(300)]
        public string s_PatentName
        {
            get { return fs_PatentName; }
            set { SetPropertyValue<string>("s_PatentName", ref fs_PatentName, value); }
        }
        DateTime fdt_AppDate;
        public DateTime dt_AppDate
        {
            get { return fdt_AppDate; }
            set { SetPropertyValue<DateTime>("dt_AppDate", ref fdt_AppDate, value); }
        }
        DateTime fdt_ProcDate;
        public DateTime dt_ProcDate
        {
            get { return fdt_ProcDate; }
            set { SetPropertyValue<DateTime>("dt_ProcDate", ref fdt_ProcDate, value); }
        }
        int fPatent;
        [Indexed(Name = @"iPatent_TPCase_PermitPatents")]
        public int Patent
        {
            get { return fPatent; }
            set { SetPropertyValue<int>("Patent", ref fPatent, value); }
        }
    }

}
