//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_SearchInfo : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TPCase_Patent fn_CaseID;
        [Association(@"TPCase_SearchInfoReferencesTPCase_Patent")]
        public TPCase_Patent n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TPCase_Patent>("n_CaseID", ref fn_CaseID, value); }
        }
        string fs_Property;
        [Size(50)]
        public string s_Property
        {
            get { return fs_Property; }
            set { SetPropertyValue<string>("s_Property", ref fs_Property, value); }
        }
        string fs_Aim;
        [Size(200)]
        public string s_Aim
        {
            get { return fs_Aim; }
            set { SetPropertyValue<string>("s_Aim", ref fs_Aim, value); }
        }
        string fs_SearchType;
        [Size(50)]
        public string s_SearchType
        {
            get { return fs_SearchType; }
            set { SetPropertyValue<string>("s_SearchType", ref fs_SearchType, value); }
        }
        string fs_ReqDesc;
        [Size(500)]
        public string s_ReqDesc
        {
            get { return fs_ReqDesc; }
            set { SetPropertyValue<string>("s_ReqDesc", ref fs_ReqDesc, value); }
        }
        string fs_SearchAppNumber;
        [Size(1)]
        public string s_SearchAppNumber
        {
            get { return fs_SearchAppNumber; }
            set { SetPropertyValue<string>("s_SearchAppNumber", ref fs_SearchAppNumber, value); }
        }
        string fs_AppNumber;
        [Size(50)]
        public string s_AppNumber
        {
            get { return fs_AppNumber; }
            set { SetPropertyValue<string>("s_AppNumber", ref fs_AppNumber, value); }
        }
        string fs_SearchAppDate;
        [Size(1)]
        public string s_SearchAppDate
        {
            get { return fs_SearchAppDate; }
            set { SetPropertyValue<string>("s_SearchAppDate", ref fs_SearchAppDate, value); }
        }
        DateTime fdt_AppDate;
        public DateTime dt_AppDate
        {
            get { return fdt_AppDate; }
            set { SetPropertyValue<DateTime>("dt_AppDate", ref fdt_AppDate, value); }
        }
        string fs_SearchApplicant;
        [Size(1)]
        public string s_SearchApplicant
        {
            get { return fs_SearchApplicant; }
            set { SetPropertyValue<string>("s_SearchApplicant", ref fs_SearchApplicant, value); }
        }
        string fs_Applicant;
        [Size(300)]
        public string s_Applicant
        {
            get { return fs_Applicant; }
            set { SetPropertyValue<string>("s_Applicant", ref fs_Applicant, value); }
        }
        string fs_SearchPatentName;
        [Size(1)]
        public string s_SearchPatentName
        {
            get { return fs_SearchPatentName; }
            set { SetPropertyValue<string>("s_SearchPatentName", ref fs_SearchPatentName, value); }
        }
        string fs_PatentName;
        [Size(300)]
        public string s_PatentName
        {
            get { return fs_PatentName; }
            set { SetPropertyValue<string>("s_PatentName", ref fs_PatentName, value); }
        }
        string fs_Result;
        [Size(500)]
        public string s_Result
        {
            get { return fs_Result; }
            set { SetPropertyValue<string>("s_Result", ref fs_Result, value); }
        }
        DateTime fdt_FulFillDate;
        public DateTime dt_FulFillDate
        {
            get { return fdt_FulFillDate; }
            set { SetPropertyValue<DateTime>("dt_FulFillDate", ref fdt_FulFillDate, value); }
        }
        string fs_SearchNotes;
        [Size(800)]
        public string s_SearchNotes
        {
            get { return fs_SearchNotes; }
            set { SetPropertyValue<string>("s_SearchNotes", ref fs_SearchNotes, value); }
        }
        string fs_SearchTypeCode;
        [Size(20)]
        public string s_SearchTypeCode
        {
            get { return fs_SearchTypeCode; }
            set { SetPropertyValue<string>("s_SearchTypeCode", ref fs_SearchTypeCode, value); }
        }
    }

}
