//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_HongKongApplication : XPLiteObject
    {
        int fn_CaseID;
        [Key]
        public int n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<int>("n_CaseID", ref fn_CaseID, value); }
        }
        int fn_Type;
        public int n_Type
        {
            get { return fn_Type; }
            set { SetPropertyValue<int>("n_Type", ref fn_Type, value); }
        }
        string fs_Note;
        [Size(1000)]
        public string s_Note
        {
            get { return fs_Note; }
            set { SetPropertyValue<string>("s_Note", ref fs_Note, value); }
        }
        string fs_ParentCaseSerial;
        [Size(50)]
        public string s_ParentCaseSerial
        {
            get { return fs_ParentCaseSerial; }
            set { SetPropertyValue<string>("s_ParentCaseSerial", ref fs_ParentCaseSerial, value); }
        }
        string fs_ParentCaseAppNo;
        [Size(50)]
        public string s_ParentCaseAppNo
        {
            get { return fs_ParentCaseAppNo; }
            set { SetPropertyValue<string>("s_ParentCaseAppNo", ref fs_ParentCaseAppNo, value); }
        }
        string fs_ParentCaseCountry;
        public string s_ParentCaseCountry
        {
            get { return fs_ParentCaseCountry; }
            set { SetPropertyValue<string>("s_ParentCaseCountry", ref fs_ParentCaseCountry, value); }
        }
        DateTime fdt_1stRegisterDate;
        public DateTime dt_1stRegisterDate
        {
            get { return fdt_1stRegisterDate; }
            set { SetPropertyValue<DateTime>("dt_1stRegisterDate", ref fdt_1stRegisterDate, value); }
        }
        DateTime fdt_2ndRegisterDate;
        public DateTime dt_2ndRegisterDate
        {
            get { return fdt_2ndRegisterDate; }
            set { SetPropertyValue<DateTime>("dt_2ndRegisterDate", ref fdt_2ndRegisterDate, value); }
        }
        DateTime fdt_1stAgentReport;
        public DateTime dt_1stAgentReport
        {
            get { return fdt_1stAgentReport; }
            set { SetPropertyValue<DateTime>("dt_1stAgentReport", ref fdt_1stAgentReport, value); }
        }
        DateTime fdt_1stPublish;
        public DateTime dt_1stPublish
        {
            get { return fdt_1stPublish; }
            set { SetPropertyValue<DateTime>("dt_1stPublish", ref fdt_1stPublish, value); }
        }
        DateTime fdt_2ndAgentReport;
        public DateTime dt_2ndAgentReport
        {
            get { return fdt_2ndAgentReport; }
            set { SetPropertyValue<DateTime>("dt_2ndAgentReport", ref fdt_2ndAgentReport, value); }
        }
        DateTime fdt_2ndGrantReport;
        public DateTime dt_2ndGrantReport
        {
            get { return fdt_2ndGrantReport; }
            set { SetPropertyValue<DateTime>("dt_2ndGrantReport", ref fdt_2ndGrantReport, value); }
        }
        DateTime fdt_RemindShldDate;
        public DateTime dt_RemindShldDate
        {
            get { return fdt_RemindShldDate; }
            set { SetPropertyValue<DateTime>("dt_RemindShldDate", ref fdt_RemindShldDate, value); }
        }
    }

}
