//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_InvalidityInfo : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TPCase_Patent fn_CaseID;
        [Association(@"TPCase_InvalidityInfoReferencesTPCase_Patent")]
        public TPCase_Patent n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TPCase_Patent>("n_CaseID", ref fn_CaseID, value); }
        }
        DateTime fdt_NullPubDate;
        public DateTime dt_NullPubDate
        {
            get { return fdt_NullPubDate; }
            set { SetPropertyValue<DateTime>("dt_NullPubDate", ref fdt_NullPubDate, value); }
        }
        string fs_NullProposer;
        [Size(300)]
        public string s_NullProposer
        {
            get { return fs_NullProposer; }
            set { SetPropertyValue<string>("s_NullProposer", ref fs_NullProposer, value); }
        }
        string fs_Reason;
        [Size(800)]
        public string s_Reason
        {
            get { return fs_Reason; }
            set { SetPropertyValue<string>("s_Reason", ref fs_Reason, value); }
        }
    }

}
