//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_AnnFeeStage : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        int fn_CaseID;
        public int n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<int>("n_CaseID", ref fn_CaseID, value); }
        }
        string fs_OfficialDiscStyle;
        [Size(1)]
        public string s_OfficialDiscStyle
        {
            get { return fs_OfficialDiscStyle; }
            set { SetPropertyValue<string>("s_OfficialDiscStyle", ref fs_OfficialDiscStyle, value); }
        }
        decimal fn_OfficialDiscount;
        public decimal n_OfficialDiscount
        {
            get { return fn_OfficialDiscount; }
            set { SetPropertyValue<decimal>("n_OfficialDiscount", ref fn_OfficialDiscount, value); }
        }
        int fn_DiscYears;
        public int n_DiscYears
        {
            get { return fn_DiscYears; }
            set { SetPropertyValue<int>("n_DiscYears", ref fn_DiscYears, value); }
        }
        int fn_FstPayYear;
        public int n_FstPayYear
        {
            get { return fn_FstPayYear; }
            set { SetPropertyValue<int>("n_FstPayYear", ref fn_FstPayYear, value); }
        }
        int fn_LastPayYear;
        public int n_LastPayYear
        {
            get { return fn_LastPayYear; }
            set { SetPropertyValue<int>("n_LastPayYear", ref fn_LastPayYear, value); }
        }
        int fn_AlarmMonths;
        public int n_AlarmMonths
        {
            get { return fn_AlarmMonths; }
            set { SetPropertyValue<int>("n_AlarmMonths", ref fn_AlarmMonths, value); }
        }
        string fs_Notes;
        [Size(800)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
        string fs_PayMode;
        [Size(2)]
        public string s_PayMode
        {
            get { return fs_PayMode; }
            set { SetPropertyValue<string>("s_PayMode", ref fs_PayMode, value); }
        }
        string fs_StatusOrder;
        [Size(10)]
        public string s_StatusOrder
        {
            get { return fs_StatusOrder; }
            set { SetPropertyValue<string>("s_StatusOrder", ref fs_StatusOrder, value); }
        }
        string fs_StatusInit;
        [Size(10)]
        public string s_StatusInit
        {
            get { return fs_StatusInit; }
            set { SetPropertyValue<string>("s_StatusInit", ref fs_StatusInit, value); }
        }
        int fn_ChargeCurrency;
        public int n_ChargeCurrency
        {
            get { return fn_ChargeCurrency; }
            set { SetPropertyValue<int>("n_ChargeCurrency", ref fn_ChargeCurrency, value); }
        }
        int fn_OfficialCurrency;
        public int n_OfficialCurrency
        {
            get { return fn_OfficialCurrency; }
            set { SetPropertyValue<int>("n_OfficialCurrency", ref fn_OfficialCurrency, value); }
        }
        string fs_FeeMode;
        [Size(1)]
        public string s_FeeMode
        {
            get { return fs_FeeMode; }
            set { SetPropertyValue<string>("s_FeeMode", ref fs_FeeMode, value); }
        }
        decimal fn_FeeDiscount;
        public decimal n_FeeDiscount
        {
            get { return fn_FeeDiscount; }
            set { SetPropertyValue<decimal>("n_FeeDiscount", ref fn_FeeDiscount, value); }
        }
        decimal fn_FixAFee;
        public decimal n_FixAFee
        {
            get { return fn_FixAFee; }
            set { SetPropertyValue<decimal>("n_FixAFee", ref fn_FixAFee, value); }
        }
        decimal fn_FixFee;
        public decimal n_FixFee
        {
            get { return fn_FixFee; }
            set { SetPropertyValue<decimal>("n_FixFee", ref fn_FixFee, value); }
        }
        int fn_CountPayYear;
        public int n_CountPayYear
        {
            get { return fn_CountPayYear; }
            set { SetPropertyValue<int>("n_CountPayYear", ref fn_CountPayYear, value); }
        }
    }

}
