//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_WriteInfo : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TPCase_Patent fn_CaseID;
        [Association(@"TPCase_WriteInfoReferencesTPCase_Patent")]
        public TPCase_Patent n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TPCase_Patent>("n_CaseID", ref fn_CaseID, value); }
        }
        string fs_OrigCaseSerial;
        [Size(50)]
        public string s_OrigCaseSerial
        {
            get { return fs_OrigCaseSerial; }
            set { SetPropertyValue<string>("s_OrigCaseSerial", ref fs_OrigCaseSerial, value); }
        }
        int fn_WriterID;
        public int n_WriterID
        {
            get { return fn_WriterID; }
            set { SetPropertyValue<int>("n_WriterID", ref fn_WriterID, value); }
        }
        DateTime fdt_WriteAssignDate;
        public DateTime dt_WriteAssignDate
        {
            get { return fdt_WriteAssignDate; }
            set { SetPropertyValue<DateTime>("dt_WriteAssignDate", ref fdt_WriteAssignDate, value); }
        }
        DateTime fdt_WriteLtdDate;
        public DateTime dt_WriteLtdDate
        {
            get { return fdt_WriteLtdDate; }
            set { SetPropertyValue<DateTime>("dt_WriteLtdDate", ref fdt_WriteLtdDate, value); }
        }
        DateTime fdt_WriteEndDate;
        public DateTime dt_WriteEndDate
        {
            get { return fdt_WriteEndDate; }
            set { SetPropertyValue<DateTime>("dt_WriteEndDate", ref fdt_WriteEndDate, value); }
        }
        int fn_DescPageNum;
        public int n_DescPageNum
        {
            get { return fn_DescPageNum; }
            set { SetPropertyValue<int>("n_DescPageNum", ref fn_DescPageNum, value); }
        }
        int fn_ImgNum;
        public int n_ImgNum
        {
            get { return fn_ImgNum; }
            set { SetPropertyValue<int>("n_ImgNum", ref fn_ImgNum, value); }
        }
        int fn_PowerItemNum;
        public int n_PowerItemNum
        {
            get { return fn_PowerItemNum; }
            set { SetPropertyValue<int>("n_PowerItemNum", ref fn_PowerItemNum, value); }
        }
        string fs_WriteQuality;
        [Size(300)]
        public string s_WriteQuality
        {
            get { return fs_WriteQuality; }
            set { SetPropertyValue<string>("s_WriteQuality", ref fs_WriteQuality, value); }
        }
        int fn_TypewriteID;
        public int n_TypewriteID
        {
            get { return fn_TypewriteID; }
            set { SetPropertyValue<int>("n_TypewriteID", ref fn_TypewriteID, value); }
        }
        int fn_TypeWritePageNum;
        public int n_TypeWritePageNum
        {
            get { return fn_TypeWritePageNum; }
            set { SetPropertyValue<int>("n_TypeWritePageNum", ref fn_TypeWritePageNum, value); }
        }
    }

}
