//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_LawsuitInfo : XPLiteObject
    {
        int fn_CaseID;
        [Key]
        public int n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<int>("n_CaseID", ref fn_CaseID, value); }
        }
        string fs_CaseBrief;
        [Size(2000)]
        public string s_CaseBrief
        {
            get { return fs_CaseBrief; }
            set { SetPropertyValue<string>("s_CaseBrief", ref fs_CaseBrief, value); }
        }
        string fs_CourtName;
        [Size(200)]
        public string s_CourtName
        {
            get { return fs_CourtName; }
            set { SetPropertyValue<string>("s_CourtName", ref fs_CourtName, value); }
        }
        string fs_CourtAddr;
        [Size(300)]
        public string s_CourtAddr
        {
            get { return fs_CourtAddr; }
            set { SetPropertyValue<string>("s_CourtAddr", ref fs_CourtAddr, value); }
        }
        string fs_CourtZipCode;
        [Size(50)]
        public string s_CourtZipCode
        {
            get { return fs_CourtZipCode; }
            set { SetPropertyValue<string>("s_CourtZipCode", ref fs_CourtZipCode, value); }
        }
        string fs_CourtContact;
        [Size(200)]
        public string s_CourtContact
        {
            get { return fs_CourtContact; }
            set { SetPropertyValue<string>("s_CourtContact", ref fs_CourtContact, value); }
        }
        string fs_CourtTel;
        [Size(50)]
        public string s_CourtTel
        {
            get { return fs_CourtTel; }
            set { SetPropertyValue<string>("s_CourtTel", ref fs_CourtTel, value); }
        }
        string fs_CourtFax;
        [Size(50)]
        public string s_CourtFax
        {
            get { return fs_CourtFax; }
            set { SetPropertyValue<string>("s_CourtFax", ref fs_CourtFax, value); }
        }
        string fs_CourtEmail;
        [Size(50)]
        public string s_CourtEmail
        {
            get { return fs_CourtEmail; }
            set { SetPropertyValue<string>("s_CourtEmail", ref fs_CourtEmail, value); }
        }
        string fs_CourtSerial;
        [Size(50)]
        public string s_CourtSerial
        {
            get { return fs_CourtSerial; }
            set { SetPropertyValue<string>("s_CourtSerial", ref fs_CourtSerial, value); }
        }
        DateTime fdt_CourtRegDate;
        public DateTime dt_CourtRegDate
        {
            get { return fdt_CourtRegDate; }
            set { SetPropertyValue<DateTime>("dt_CourtRegDate", ref fdt_CourtRegDate, value); }
        }
        DateTime fdt_CourtNoticeDate;
        public DateTime dt_CourtNoticeDate
        {
            get { return fdt_CourtNoticeDate; }
            set { SetPropertyValue<DateTime>("dt_CourtNoticeDate", ref fdt_CourtNoticeDate, value); }
        }
        string fs_Judge;
        [Size(200)]
        public string s_Judge
        {
            get { return fs_Judge; }
            set { SetPropertyValue<string>("s_Judge", ref fs_Judge, value); }
        }
        string fs_CourtOfficer;
        [Size(200)]
        public string s_CourtOfficer
        {
            get { return fs_CourtOfficer; }
            set { SetPropertyValue<string>("s_CourtOfficer", ref fs_CourtOfficer, value); }
        }
        string fs_AcceptCourt;
        public string s_AcceptCourt
        {
            get { return fs_AcceptCourt; }
            set { SetPropertyValue<string>("s_AcceptCourt", ref fs_AcceptCourt, value); }
        }
        string fs_CheckLevel;
        public string s_CheckLevel
        {
            get { return fs_CheckLevel; }
            set { SetPropertyValue<string>("s_CheckLevel", ref fs_CheckLevel, value); }
        }
        DateTime fdt_PubProofDate;
        public DateTime dt_PubProofDate
        {
            get { return fdt_PubProofDate; }
            set { SetPropertyValue<DateTime>("dt_PubProofDate", ref fdt_PubProofDate, value); }
        }
        DateTime fdt_CourtDate;
        public DateTime dt_CourtDate
        {
            get { return fdt_CourtDate; }
            set { SetPropertyValue<DateTime>("dt_CourtDate", ref fdt_CourtDate, value); }
        }
        DateTime fdt_SubpoenaDate;
        public DateTime dt_SubpoenaDate
        {
            get { return fdt_SubpoenaDate; }
            set { SetPropertyValue<DateTime>("dt_SubpoenaDate", ref fdt_SubpoenaDate, value); }
        }
        DateTime fdt_ReplyDate;
        public DateTime dt_ReplyDate
        {
            get { return fdt_ReplyDate; }
            set { SetPropertyValue<DateTime>("dt_ReplyDate", ref fdt_ReplyDate, value); }
        }
    }

}
