//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_MacaoApplication : XPLiteObject
    {
        int fn_CaseID;
        [Key]
        public int n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<int>("n_CaseID", ref fn_CaseID, value); }
        }
        string fs_ParentCaseSerial;
        [Size(50)]
        public string s_ParentCaseSerial
        {
            get { return fs_ParentCaseSerial; }
            set { SetPropertyValue<string>("s_ParentCaseSerial", ref fs_ParentCaseSerial, value); }
        }
        string fs_ParentCaseAppNo;
        [Size(50)]
        public string s_ParentCaseAppNo
        {
            get { return fs_ParentCaseAppNo; }
            set { SetPropertyValue<string>("s_ParentCaseAppNo", ref fs_ParentCaseAppNo, value); }
        }
        string fs_ParentCaseCountry;
        public string s_ParentCaseCountry
        {
            get { return fs_ParentCaseCountry; }
            set { SetPropertyValue<string>("s_ParentCaseCountry", ref fs_ParentCaseCountry, value); }
        }
        DateTime fdt_AppDate;
        public DateTime dt_AppDate
        {
            get { return fdt_AppDate; }
            set { SetPropertyValue<DateTime>("dt_AppDate", ref fdt_AppDate, value); }
        }
        DateTime fdt_GrantDate;
        public DateTime dt_GrantDate
        {
            get { return fdt_GrantDate; }
            set { SetPropertyValue<DateTime>("dt_GrantDate", ref fdt_GrantDate, value); }
        }
    }

}
