//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_PCTICountry : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TPCase_PCTICaseInfo fn_CaseID;
        [Association(@"TPCase_PCTICountryReferencesTPCase_PCTICaseInfo")]
        public TPCase_PCTICaseInfo n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TPCase_PCTICaseInfo>("n_CaseID", ref fn_CaseID, value); }
        }
        int fn_Country;
        public int n_Country
        {
            get { return fn_Country; }
            set { SetPropertyValue<int>("n_Country", ref fn_Country, value); }
        }
        string fs_Require;
        [Size(800)]
        public string s_Require
        {
            get { return fs_Require; }
            set { SetPropertyValue<string>("s_Require", ref fs_Require, value); }
        }
        int fPatent;
        [Indexed(Name = @"iPatent_TPCase_PCTICountry")]
        public int Patent
        {
            get { return fPatent; }
            set { SetPropertyValue<int>("Patent", ref fPatent, value); }
        }
    }

}
