//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_Priority : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TPCase_Patent fn_CaseID;
        [Association(@"TPCase_PriorityReferencesTPCase_Patent")]
        public TPCase_Patent n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TPCase_Patent>("n_CaseID", ref fn_CaseID, value); }
        }
        int fn_Sequence;
        public int n_Sequence
        {
            get { return fn_Sequence; }
            set { SetPropertyValue<int>("n_Sequence", ref fn_Sequence, value); }
        }
        string fs_Priority;
        [Size(500)]
        public string s_Priority
        {
            get { return fs_Priority; }
            set { SetPropertyValue<string>("s_Priority", ref fs_Priority, value); }
        }
        string fs_POfficeType;
        [Size(50)]
        public string s_POfficeType
        {
            get { return fs_POfficeType; }
            set { SetPropertyValue<string>("s_POfficeType", ref fs_POfficeType, value); }
        }
        int fn_PCountry;
        public int n_PCountry
        {
            get { return fn_PCountry; }
            set { SetPropertyValue<int>("n_PCountry", ref fn_PCountry, value); }
        }
        string fs_POffice;
        [Size(200)]
        public string s_POffice
        {
            get { return fs_POffice; }
            set { SetPropertyValue<string>("s_POffice", ref fs_POffice, value); }
        }
        DateTime fdt_PDate;
        public DateTime dt_PDate
        {
            get { return fdt_PDate; }
            set { SetPropertyValue<DateTime>("dt_PDate", ref fdt_PDate, value); }
        }
        string fs_PNum;
        [Size(50)]
        public string s_PNum
        {
            get { return fs_PNum; }
            set { SetPropertyValue<string>("s_PNum", ref fs_PNum, value); }
        }
        string fs_PDocProvided;
        [Size(1)]
        public string s_PDocProvided
        {
            get { return fs_PDocProvided; }
            set { SetPropertyValue<string>("s_PDocProvided", ref fs_PDocProvided, value); }
        }
        string fs_PTransDocProvided;
        [Size(1)]
        public string s_PTransDocProvided
        {
            get { return fs_PTransDocProvided; }
            set { SetPropertyValue<string>("s_PTransDocProvided", ref fs_PTransDocProvided, value); }
        }
        int fPatent;
        [Indexed(Name = @"iPatent_TPCase_Priority")]
        public int Patent
        {
            get { return fPatent; }
            set { SetPropertyValue<int>("Patent", ref fPatent, value); }
        }
        string fs_InputNum;
        [Size(50)]
        public string s_InputNum
        {
            get { return fs_InputNum; }
            set { SetPropertyValue<string>("s_InputNum", ref fs_InputNum, value); }
        }
        string fs_Notes;
        [Size(1000)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
    }

}
