//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_PCTICaseInfo : XPLiteObject
    {
        int fn_CaseID;
        [Key]
        public int n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<int>("n_CaseID", ref fn_CaseID, value); }
        }
        string fs_ISA;
        [Size(200)]
        public string s_ISA
        {
            get { return fs_ISA; }
            set { SetPropertyValue<string>("s_ISA", ref fs_ISA, value); }
        }
        string fs_ISANum;
        [Size(20)]
        public string s_ISANum
        {
            get { return fs_ISANum; }
            set { SetPropertyValue<string>("s_ISANum", ref fs_ISANum, value); }
        }
        DateTime fdt_ISADate;
        public DateTime dt_ISADate
        {
            get { return fdt_ISADate; }
            set { SetPropertyValue<DateTime>("dt_ISADate", ref fdt_ISADate, value); }
        }
        int fn_ISACountry;
        public int n_ISACountry
        {
            get { return fn_ISACountry; }
            set { SetPropertyValue<int>("n_ISACountry", ref fn_ISACountry, value); }
        }
        int fPatent;
        [Indexed(Name = @"iPatent_TPCase_PCTICaseInfo")]
        public int Patent
        {
            get { return fPatent; }
            set { SetPropertyValue<int>("Patent", ref fPatent, value); }
        }
        [Association(@"TPCase_PCTICountryReferencesTPCase_PCTICaseInfo")]
        public XPCollection<TPCase_PCTICountry> TPCase_PCTICountrys { get { return GetCollection<TPCase_PCTICountry>("TPCase_PCTICountrys"); } }
    }

}
