//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_LawInfo : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        string fs_AppNo;
        [Size(50)]
        public string s_AppNo
        {
            get { return fs_AppNo; }
            set { SetPropertyValue<string>("s_AppNo", ref fs_AppNo, value); }
        }
        DateTime fdt_AppDate;
        public DateTime dt_AppDate
        {
            get { return fdt_AppDate; }
            set { SetPropertyValue<DateTime>("dt_AppDate", ref fdt_AppDate, value); }
        }
        int fn_ClaimCount;
        public int n_ClaimCount
        {
            get { return fn_ClaimCount; }
            set { SetPropertyValue<int>("n_ClaimCount", ref fn_ClaimCount, value); }
        }
        string fs_PubNo;
        [Size(50)]
        public string s_PubNo
        {
            get { return fs_PubNo; }
            set { SetPropertyValue<string>("s_PubNo", ref fs_PubNo, value); }
        }
        DateTime fdt_PubDate;
        public DateTime dt_PubDate
        {
            get { return fdt_PubDate; }
            set { SetPropertyValue<DateTime>("dt_PubDate", ref fdt_PubDate, value); }
        }
        string fs_PubVolume;
        [Size(50)]
        public string s_PubVolume
        {
            get { return fs_PubVolume; }
            set { SetPropertyValue<string>("s_PubVolume", ref fs_PubVolume, value); }
        }
        string fs_PubGazette;
        [Size(50)]
        public string s_PubGazette
        {
            get { return fs_PubGazette; }
            set { SetPropertyValue<string>("s_PubGazette", ref fs_PubGazette, value); }
        }
        string fs_PubClass1;
        [Size(50)]
        public string s_PubClass1
        {
            get { return fs_PubClass1; }
            set { SetPropertyValue<string>("s_PubClass1", ref fs_PubClass1, value); }
        }
        string fs_PubClass2;
        [Size(50)]
        public string s_PubClass2
        {
            get { return fs_PubClass2; }
            set { SetPropertyValue<string>("s_PubClass2", ref fs_PubClass2, value); }
        }
        DateTime fdt_SubstantiveExamDate;
        public DateTime dt_SubstantiveExamDate
        {
            get { return fdt_SubstantiveExamDate; }
            set { SetPropertyValue<DateTime>("dt_SubstantiveExamDate", ref fdt_SubstantiveExamDate, value); }
        }
        string fs_IssuedPubNo;
        [Size(50)]
        public string s_IssuedPubNo
        {
            get { return fs_IssuedPubNo; }
            set { SetPropertyValue<string>("s_IssuedPubNo", ref fs_IssuedPubNo, value); }
        }
        DateTime fdt_IssuedPubDate;
        public DateTime dt_IssuedPubDate
        {
            get { return fdt_IssuedPubDate; }
            set { SetPropertyValue<DateTime>("dt_IssuedPubDate", ref fdt_IssuedPubDate, value); }
        }
        string fs_IssuedPubVolume;
        [Size(50)]
        public string s_IssuedPubVolume
        {
            get { return fs_IssuedPubVolume; }
            set { SetPropertyValue<string>("s_IssuedPubVolume", ref fs_IssuedPubVolume, value); }
        }
        string fs_IssuedPubGazette;
        [Size(50)]
        public string s_IssuedPubGazette
        {
            get { return fs_IssuedPubGazette; }
            set { SetPropertyValue<string>("s_IssuedPubGazette", ref fs_IssuedPubGazette, value); }
        }
        string fs_IssuedPubClass1;
        [Size(50)]
        public string s_IssuedPubClass1
        {
            get { return fs_IssuedPubClass1; }
            set { SetPropertyValue<string>("s_IssuedPubClass1", ref fs_IssuedPubClass1, value); }
        }
        string fs_IssuedPubClass2;
        [Size(50)]
        public string s_IssuedPubClass2
        {
            get { return fs_IssuedPubClass2; }
            set { SetPropertyValue<string>("s_IssuedPubClass2", ref fs_IssuedPubClass2, value); }
        }
        string fs_CertfNo;
        [Size(50)]
        public string s_CertfNo
        {
            get { return fs_CertfNo; }
            set { SetPropertyValue<string>("s_CertfNo", ref fs_CertfNo, value); }
        }
        DateTime fdt_CertfDate;
        public DateTime dt_CertfDate
        {
            get { return fdt_CertfDate; }
            set { SetPropertyValue<DateTime>("dt_CertfDate", ref fdt_CertfDate, value); }
        }
        string fs_PCTAppNo;
        [Size(50)]
        public string s_PCTAppNo
        {
            get { return fs_PCTAppNo; }
            set { SetPropertyValue<string>("s_PCTAppNo", ref fs_PCTAppNo, value); }
        }
        DateTime fdt_PctAppDate;
        public DateTime dt_PctAppDate
        {
            get { return fdt_PctAppDate; }
            set { SetPropertyValue<DateTime>("dt_PctAppDate", ref fdt_PctAppDate, value); }
        }
        string fs_PCTPubNo;
        [Size(50)]
        public string s_PCTPubNo
        {
            get { return fs_PCTPubNo; }
            set { SetPropertyValue<string>("s_PCTPubNo", ref fs_PCTPubNo, value); }
        }
        DateTime fdt_PctPubDate;
        public DateTime dt_PctPubDate
        {
            get { return fdt_PctPubDate; }
            set { SetPropertyValue<DateTime>("dt_PctPubDate", ref fdt_PctPubDate, value); }
        }
        DateTime fdt_PctInNationDate;
        public DateTime dt_PctInNationDate
        {
            get { return fdt_PctInNationDate; }
            set { SetPropertyValue<DateTime>("dt_PctInNationDate", ref fdt_PctInNationDate, value); }
        }
        int fn_PCTPubLan;
        public int n_PCTPubLan
        {
            get { return fn_PCTPubLan; }
            set { SetPropertyValue<int>("n_PCTPubLan", ref fn_PCTPubLan, value); }
        }
        int fn_ManualPages;
        public int n_ManualPages
        {
            get { return fn_ManualPages; }
            set { SetPropertyValue<int>("n_ManualPages", ref fn_ManualPages, value); }
        }
        decimal fn_ProtectionDuration;
        public decimal n_ProtectionDuration
        {
            get { return fn_ProtectionDuration; }
            set { SetPropertyValue<decimal>("n_ProtectionDuration", ref fn_ProtectionDuration, value); }
        }
        DateTime fdt_ExpirationDate;
        public DateTime dt_ExpirationDate
        {
            get { return fdt_ExpirationDate; }
            set { SetPropertyValue<DateTime>("dt_ExpirationDate", ref fdt_ExpirationDate, value); }
        }
        string fs_PCTSearchBureau;
        [Size(200)]
        public string s_PCTSearchBureau
        {
            get { return fs_PCTSearchBureau; }
            set { SetPropertyValue<string>("s_PCTSearchBureau", ref fs_PCTSearchBureau, value); }
        }
        DateTime fdt_FirstCheckDate;
        public DateTime dt_FirstCheckDate
        {
            get { return fdt_FirstCheckDate; }
            set { SetPropertyValue<DateTime>("dt_FirstCheckDate", ref fdt_FirstCheckDate, value); }
        }
        string fs_ReviewNo;
        [Size(50)]
        public string s_ReviewNo
        {
            get { return fs_ReviewNo; }
            set { SetPropertyValue<string>("s_ReviewNo", ref fs_ReviewNo, value); }
        }
        [Association(@"TPCase_PatentReferencesTPCase_LawInfo")]
        public XPCollection<TPCase_Patent> TPCase_Patents { get { return GetCollection<TPCase_Patent>("TPCase_Patents"); } }
    }

}
