//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_ReviewInfo : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TPCase_Patent fn_CaseID;
        [Association(@"TPCase_ReviewInfoReferencesTPCase_Patent")]
        public TPCase_Patent n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TPCase_Patent>("n_CaseID", ref fn_CaseID, value); }
        }
        DateTime fdt_RejectDate;
        public DateTime dt_RejectDate
        {
            get { return fdt_RejectDate; }
            set { SetPropertyValue<DateTime>("dt_RejectDate", ref fdt_RejectDate, value); }
        }
        string fs_Reason;
        [Size(1000)]
        public string s_Reason
        {
            get { return fs_Reason; }
            set { SetPropertyValue<string>("s_Reason", ref fs_Reason, value); }
        }
    }

}
