//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_OppositePersons : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TPCase_Patent fn_CaseID;
        [Association(@"TPCase_OppositePersonsReferencesTPCase_Patent")]
        public TPCase_Patent n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TPCase_Patent>("n_CaseID", ref fn_CaseID, value); }
        }
        string fs_Role;
        [Size(1)]
        public string s_Role
        {
            get { return fs_Role; }
            set { SetPropertyValue<string>("s_Role", ref fs_Role, value); }
        }
        string fs_Name;
        [Size(300)]
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_OtherName;
        [Size(200)]
        public string s_OtherName
        {
            get { return fs_OtherName; }
            set { SetPropertyValue<string>("s_OtherName", ref fs_OtherName, value); }
        }
        string fs_Addr;
        [Size(300)]
        public string s_Addr
        {
            get { return fs_Addr; }
            set { SetPropertyValue<string>("s_Addr", ref fs_Addr, value); }
        }
        string fs_OtherAddr;
        [Size(300)]
        public string s_OtherAddr
        {
            get { return fs_OtherAddr; }
            set { SetPropertyValue<string>("s_OtherAddr", ref fs_OtherAddr, value); }
        }
        string fs_ZipCode;
        [Size(50)]
        public string s_ZipCode
        {
            get { return fs_ZipCode; }
            set { SetPropertyValue<string>("s_ZipCode", ref fs_ZipCode, value); }
        }
        string fs_Tel;
        [Size(50)]
        public string s_Tel
        {
            get { return fs_Tel; }
            set { SetPropertyValue<string>("s_Tel", ref fs_Tel, value); }
        }
        string fs_Fax;
        [Size(50)]
        public string s_Fax
        {
            get { return fs_Fax; }
            set { SetPropertyValue<string>("s_Fax", ref fs_Fax, value); }
        }
        string fs_Email;
        [Size(50)]
        public string s_Email
        {
            get { return fs_Email; }
            set { SetPropertyValue<string>("s_Email", ref fs_Email, value); }
        }
        string fs_LawDeputy;
        [Size(200)]
        public string s_LawDeputy
        {
            get { return fs_LawDeputy; }
            set { SetPropertyValue<string>("s_LawDeputy", ref fs_LawDeputy, value); }
        }
        string fs_Contact;
        [Size(200)]
        public string s_Contact
        {
            get { return fs_Contact; }
            set { SetPropertyValue<string>("s_Contact", ref fs_Contact, value); }
        }
        int fPatent;
        [Indexed(Name = @"iPatent_TPCase_OppositePersons")]
        public int Patent
        {
            get { return fPatent; }
            set { SetPropertyValue<int>("Patent", ref fPatent, value); }
        }
        int fn_Country;
        public int n_Country
        {
            get { return fn_Country; }
            set { SetPropertyValue<int>("n_Country", ref fn_Country, value); }
        }
    }

}
