//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DataSyncTool.DBIPS4_Import
{

    public partial class TPCase_TranslateInfo : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TPCase_Patent fn_CaseID;
        [Association(@"TPCase_TranslateInfoReferencesTPCase_Patent")]
        public TPCase_Patent n_CaseID
        {
            get { return fn_CaseID; }
            set { SetPropertyValue<TPCase_Patent>("n_CaseID", ref fn_CaseID, value); }
        }
        int fn_OrigLan;
        public int n_OrigLan
        {
            get { return fn_OrigLan; }
            set { SetPropertyValue<int>("n_OrigLan", ref fn_OrigLan, value); }
        }
        int fn_OrigWordsNum;
        public int n_OrigWordsNum
        {
            get { return fn_OrigWordsNum; }
            set { SetPropertyValue<int>("n_OrigWordsNum", ref fn_OrigWordsNum, value); }
        }
        int fn_DestLan;
        public int n_DestLan
        {
            get { return fn_DestLan; }
            set { SetPropertyValue<int>("n_DestLan", ref fn_DestLan, value); }
        }
        int fn_TranslatorID;
        public int n_TranslatorID
        {
            get { return fn_TranslatorID; }
            set { SetPropertyValue<int>("n_TranslatorID", ref fn_TranslatorID, value); }
        }
        DateTime fdt_TransAssignDate;
        public DateTime dt_TransAssignDate
        {
            get { return fdt_TransAssignDate; }
            set { SetPropertyValue<DateTime>("dt_TransAssignDate", ref fdt_TransAssignDate, value); }
        }
        DateTime fdt_TransLtdDate;
        public DateTime dt_TransLtdDate
        {
            get { return fdt_TransLtdDate; }
            set { SetPropertyValue<DateTime>("dt_TransLtdDate", ref fdt_TransLtdDate, value); }
        }
        DateTime fdt_TransEndDate;
        public DateTime dt_TransEndDate
        {
            get { return fdt_TransEndDate; }
            set { SetPropertyValue<DateTime>("dt_TransEndDate", ref fdt_TransEndDate, value); }
        }
        string fs_TransQuality;
        [Size(500)]
        public string s_TransQuality
        {
            get { return fs_TransQuality; }
            set { SetPropertyValue<string>("s_TransQuality", ref fs_TransQuality, value); }
        }
        int fn_Collator1ID;
        public int n_Collator1ID
        {
            get { return fn_Collator1ID; }
            set { SetPropertyValue<int>("n_Collator1ID", ref fn_Collator1ID, value); }
        }
        int fn_Collator2ID;
        public int n_Collator2ID
        {
            get { return fn_Collator2ID; }
            set { SetPropertyValue<int>("n_Collator2ID", ref fn_Collator2ID, value); }
        }
        DateTime fdt_CollateAssignDate;
        public DateTime dt_CollateAssignDate
        {
            get { return fdt_CollateAssignDate; }
            set { SetPropertyValue<DateTime>("dt_CollateAssignDate", ref fdt_CollateAssignDate, value); }
        }
        DateTime fdt_CollateLtdDate;
        public DateTime dt_CollateLtdDate
        {
            get { return fdt_CollateLtdDate; }
            set { SetPropertyValue<DateTime>("dt_CollateLtdDate", ref fdt_CollateLtdDate, value); }
        }
        DateTime fdt_CollateEndDate;
        public DateTime dt_CollateEndDate
        {
            get { return fdt_CollateEndDate; }
            set { SetPropertyValue<DateTime>("dt_CollateEndDate", ref fdt_CollateEndDate, value); }
        }
        int fn_TypeWriteByID;
        public int n_TypeWriteByID
        {
            get { return fn_TypeWriteByID; }
            set { SetPropertyValue<int>("n_TypeWriteByID", ref fn_TypeWriteByID, value); }
        }
    }

}
