//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicFacility.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicFacility.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string BASICFACILITY_ERROR {
            get {
                return ResourceManager.GetString("BASICFACILITY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input box can not be empty. 的本地化字符串。
        /// </summary>
        internal static string BASICFACILITY_INPUT_NOT_EMPTY {
            get {
                return ResourceManager.GetString("BASICFACILITY_INPUT_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Question 的本地化字符串。
        /// </summary>
        internal static string BASICFACILITY_QUESTION {
            get {
                return ResourceManager.GetString("BASICFACILITY_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want SWD record the current system information for reference? 的本地化字符串。
        /// </summary>
        internal static string BASICFACILITY_RECORD_SYSINFOR {
            get {
                return ResourceManager.GetString("BASICFACILITY_RECORD_SYSINFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string BASICFACILITY_TIPS {
            get {
                return ResourceManager.GetString("BASICFACILITY_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string BASICFACILITY_WARNING {
            get {
                return ResourceManager.GetString("BASICFACILITY_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string DateEditClear {
            get {
                return ResourceManager.GetString("DateEditClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string DateEditToday {
            get {
                return ResourceManager.GetString("DateEditToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading data, please wait... 的本地化字符串。
        /// </summary>
        internal static string Loading_Data_For_Waiting {
            get {
                return ResourceManager.GetString("Loading_Data_For_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checked 的本地化字符串。
        /// </summary>
        internal static string MENU_CHECKED {
            get {
                return ResourceManager.GetString("MENU_CHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string MENU_COPY {
            get {
                return ResourceManager.GetString("MENU_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string MENU_CUT {
            get {
                return ResourceManager.GetString("MENU_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string MENU_DELETE {
            get {
                return ResourceManager.GetString("MENU_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string MENU_PASTE {
            get {
                return ResourceManager.GetString("MENU_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select. 的本地化字符串。
        /// </summary>
        internal static string MENU_SELECT_AGAIN {
            get {
                return ResourceManager.GetString("MENU_SELECT_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        internal static string MENU_SELECT_ALL {
            get {
                return ResourceManager.GetString("MENU_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unchecked 的本地化字符串。
        /// </summary>
        internal static string MENU_UNCHECKED {
            get {
                return ResourceManager.GetString("MENU_UNCHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string MENU_UNDO {
            get {
                return ResourceManager.GetString("MENU_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Abort 的本地化字符串。
        /// </summary>
        internal static string MESSAGEBOX_ABORT {
            get {
                return ResourceManager.GetString("MESSAGEBOX_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Cancel 的本地化字符串。
        /// </summary>
        internal static string MESSAGEBOX_CANCEL {
            get {
                return ResourceManager.GetString("MESSAGEBOX_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Ignore 的本地化字符串。
        /// </summary>
        internal static string MESSAGEBOX_IGNORE {
            get {
                return ResourceManager.GetString("MESSAGEBOX_IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;No 的本地化字符串。
        /// </summary>
        internal static string MESSAGEBOX_NO {
            get {
                return ResourceManager.GetString("MESSAGEBOX_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Ok 的本地化字符串。
        /// </summary>
        internal static string MESSAGEBOX_OK {
            get {
                return ResourceManager.GetString("MESSAGEBOX_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Retry 的本地化字符串。
        /// </summary>
        internal static string MESSAGEBOX_RETRY {
            get {
                return ResourceManager.GetString("MESSAGEBOX_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string MessageBox_Text_Delete {
            get {
                return ResourceManager.GetString("MessageBox_Text_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete all 的本地化字符串。
        /// </summary>
        internal static string MessageBox_Text_Delete_All {
            get {
                return ResourceManager.GetString("MessageBox_Text_Delete_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import add. 的本地化字符串。
        /// </summary>
        internal static string MessageBox_Text_Import_Addtional {
            get {
                return ResourceManager.GetString("MessageBox_Text_Import_Addtional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;OK 的本地化字符串。
        /// </summary>
        internal static string MessageBox_Text_OK {
            get {
                return ResourceManager.GetString("MessageBox_Text_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override 的本地化字符串。
        /// </summary>
        internal static string MessageBox_Text_Override {
            get {
                return ResourceManager.GetString("MessageBox_Text_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override all 的本地化字符串。
        /// </summary>
        internal static string MessageBox_Text_Override_All {
            get {
                return ResourceManager.GetString("MessageBox_Text_Override_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Retry 的本地化字符串。
        /// </summary>
        internal static string MessageBox_Text_Retry {
            get {
                return ResourceManager.GetString("MessageBox_Text_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip 的本地化字符串。
        /// </summary>
        internal static string MessageBox_Text_Skip {
            get {
                return ResourceManager.GetString("MessageBox_Text_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip all 的本地化字符串。
        /// </summary>
        internal static string MessageBox_Text_Skip_All {
            get {
                return ResourceManager.GetString("MessageBox_Text_Skip_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Yes 的本地化字符串。
        /// </summary>
        internal static string MESSAGEBOX_YES {
            get {
                return ResourceManager.GetString("MESSAGEBOX_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want save the current system information for future referring? 的本地化字符串。
        /// </summary>
        internal static string Save_Current_System_Info {
            get {
                return ResourceManager.GetString("Save_Current_System_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (Seperator)  的本地化字符串。
        /// </summary>
        internal static string Seperator {
            get {
                return ResourceManager.GetString("Seperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sqlcon is empty 的本地化字符串。
        /// </summary>
        internal static string Sqlconn_Empty {
            get {
                return ResourceManager.GetString("Sqlconn_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sqlcon is not empty 的本地化字符串。
        /// </summary>
        internal static string Sqlconn_Not_Empty {
            get {
                return ResourceManager.GetString("Sqlconn_Not_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose a value here 的本地化字符串。
        /// </summary>
        internal static string Validation_LookupEdit_Need_Choosing {
            get {
                return ResourceManager.GetString("Validation_LookupEdit_Need_Choosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a value here 的本地化字符串。
        /// </summary>
        internal static string Validation_Not_Empty {
            get {
                return ResourceManager.GetString("Validation_Not_Empty", resourceCulture);
            }
        }
    }
}
