//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntities.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataEntities.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Aboard Angecy 的本地化字符串。
        /// </summary>
        internal static string AboardAngecy {
            get {
                return ResourceManager.GetString("AboardAngecy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accepted year 的本地化字符串。
        /// </summary>
        internal static string AcceptYear {
            get {
                return ResourceManager.GetString("AcceptYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agenct code 的本地化字符串。
        /// </summary>
        internal static string AgenctCode {
            get {
                return ResourceManager.GetString("AgenctCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agency 的本地化字符串。
        /// </summary>
        internal static string AgencyDemand {
            get {
                return ResourceManager.GetString("AgencyDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agent Fee Discount({0}%) 的本地化字符串。
        /// </summary>
        internal static string Agent_Fee_Discount {
            get {
                return ResourceManager.GetString("Agent_Fee_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Annual Fee 的本地化字符串。
        /// </summary>
        internal static string AnnualFee {
            get {
                return ResourceManager.GetString("AnnualFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applicant-ClientDemand 的本地化字符串。
        /// </summary>
        internal static string ApplicantClientDemand {
            get {
                return ResourceManager.GetString("ApplicantClientDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applicate type 的本地化字符串。
        /// </summary>
        internal static string ApplicateType {
            get {
                return ResourceManager.GetString("ApplicateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applicate way 的本地化字符串。
        /// </summary>
        internal static string ApplicateWay {
            get {
                return ResourceManager.GetString("ApplicateWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application 的本地化字符串。
        /// </summary>
        internal static string ApplicationDemand {
            get {
                return ResourceManager.GetString("ApplicationDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personal 的本地化字符串。
        /// </summary>
        internal static string AppTypePersonal {
            get {
                return ResourceManager.GetString("AppTypePersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit/Enterprise 的本地化字符串。
        /// </summary>
        internal static string AppTypeUnitOrEnterprise {
            get {
                return ResourceManager.GetString("AppTypeUnitOrEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bussiness type 的本地化字符串。
        /// </summary>
        internal static string BussinessType {
            get {
                return ResourceManager.GetString("BussinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Case 的本地化字符串。
        /// </summary>
        internal static string CaseDemand {
            get {
                return ResourceManager.GetString("CaseDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client-ApplicantDemand 的本地化字符串。
        /// </summary>
        internal static string ClientApplicantDemand {
            get {
                return ResourceManager.GetString("ClientApplicantDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client code 的本地化字符串。
        /// </summary>
        internal static string ClientCode {
            get {
                return ResourceManager.GetString("ClientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        internal static string ClientDemand {
            get {
                return ResourceManager.GetString("ClientDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close case 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Be due 的本地化字符串。
        /// </summary>
        internal static string Color_Config_Be_Due {
            get {
                return ResourceManager.GetString("Color_Config_Be_Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Days before due date: 的本地化字符串。
        /// </summary>
        internal static string Color_Config_Before_1 {
            get {
                return ResourceManager.GetString("Color_Config_Before_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Color_Config_Before_2 {
            get {
                return ResourceManager.GetString("Color_Config_Before_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overdue 的本地化字符串。
        /// </summary>
        internal static string Color_Config_Overdue {
            get {
                return ResourceManager.GetString("Color_Config_Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charging after handling 的本地化字符串。
        /// </summary>
        internal static string Column_Text_Charge_First {
            get {
                return ResourceManager.GetString("Column_Text_Charge_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The client pays O.fee,we only notify the client 的本地化字符串。
        /// </summary>
        internal static string Column_Text_Client {
            get {
                return ResourceManager.GetString("Column_Text_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charging before handling 的本地化字符串。
        /// </summary>
        internal static string Column_Text_Pay_First {
            get {
                return ResourceManager.GetString("Column_Text_Pay_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright 的本地化字符串。
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handling 的本地化字符串。
        /// </summary>
        internal static string Dealing {
            get {
                return ResourceManager.GetString("Dealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain 的本地化字符串。
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain Renewal Fee 的本地化字符串。
        /// </summary>
        internal static string DomainRenewalFee {
            get {
                return ResourceManager.GetString("DomainRenewalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example 的本地化字符串。
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Forward 的本地化字符串。
        /// </summary>
        internal static string File_NotTransfer {
            get {
                return ResourceManager.GetString("File_NotTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forwarded 的本地化字符串。
        /// </summary>
        internal static string File_Transfered {
            get {
                return ResourceManager.GetString("File_Transfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string FileActive_Active {
            get {
                return ResourceManager.GetString("FileActive_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closed 的本地化字符串。
        /// </summary>
        internal static string FileActive_NotActive {
            get {
                return ResourceManager.GetString("FileActive_NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        internal static string FileClientGov_Client {
            get {
                return ResourceManager.GetString("FileClientGov_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auth. 的本地化字符串。
        /// </summary>
        internal static string FileClientGov_Officical {
            get {
                return ResourceManager.GetString("FileClientGov_Officical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string FileClientGov_Other {
            get {
                return ResourceManager.GetString("FileClientGov_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In File 的本地化字符串。
        /// </summary>
        internal static string FileIOType_In {
            get {
                return ResourceManager.GetString("FileIOType_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string FileIOType_Other {
            get {
                return ResourceManager.GetString("FileIOType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out File 的本地化字符串。
        /// </summary>
        internal static string FileIOType_Out {
            get {
                return ResourceManager.GetString("FileIOType_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed Agent Fee({0}) 的本地化字符串。
        /// </summary>
        internal static string Fixed_AFee {
            get {
                return ResourceManager.GetString("Fixed_AFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed Total Fee({0}) 的本地化字符串。
        /// </summary>
        internal static string Fixed_Total_Fee {
            get {
                return ResourceManager.GetString("Fixed_Total_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed words 的本地化字符串。
        /// </summary>
        internal static string FixedWords {
            get {
                return ResourceManager.GetString("FixedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow direction 的本地化字符串。
        /// </summary>
        internal static string FlowDirection {
            get {
                return ResourceManager.GetString("FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow number 的本地化字符串。
        /// </summary>
        internal static string FlowNumber {
            get {
                return ResourceManager.GetString("FlowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recycle the numbers formerly discarded, if available. 的本地化字符串。
        /// </summary>
        internal static string FollowNotUsed {
            get {
                return ResourceManager.GetString("FollowNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get from the  的本地化字符串。
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From the agency code management. 的本地化字符串。
        /// </summary>
        internal static string FromAgentCode {
            get {
                return ResourceManager.GetString("FromAgentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From the applicant management. 的本地化字符串。
        /// </summary>
        internal static string FromApplicantCode {
            get {
                return ResourceManager.GetString("FromApplicantCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From the bussiness type management. 的本地化字符串。
        /// </summary>
        internal static string FromBussinessType {
            get {
                return ResourceManager.GetString("FromBussinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From the client management. 的本地化字符串。
        /// </summary>
        internal static string FromClientCode {
            get {
                return ResourceManager.GetString("FromClientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From the introducer management. 的本地化字符串。
        /// </summary>
        internal static string FromIntroducerCode {
            get {
                return ResourceManager.GetString("FromIntroducerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From the pantent type management. 的本地化字符串。
        /// </summary>
        internal static string FromPatentType {
            get {
                return ResourceManager.GetString("FromPatentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From the trademark type management. 的本地化字符串。
        /// </summary>
        internal static string FromTrademarkType {
            get {
                return ResourceManager.GetString("FromTrademarkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In-In: 的本地化字符串。
        /// </summary>
        internal static string In_In {
            get {
                return ResourceManager.GetString("In_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 II 的本地化字符串。
        /// </summary>
        internal static string In_In_Value {
            get {
                return ResourceManager.GetString("In_In_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In-Out: 的本地化字符串。
        /// </summary>
        internal static string In_Out {
            get {
                return ResourceManager.GetString("In_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO 的本地化字符串。
        /// </summary>
        internal static string In_Out_Value {
            get {
                return ResourceManager.GetString("In_Out_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Introducer code 的本地化字符串。
        /// </summary>
        internal static string IntroducerCode {
            get {
                return ResourceManager.GetString("IntroducerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MadridAgreement 的本地化字符串。
        /// </summary>
        internal static string MadridAgreement {
            get {
                return ResourceManager.GetString("MadridAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Madrid applicate 的本地化字符串。
        /// </summary>
        internal static string MadridApplicate {
            get {
                return ResourceManager.GetString("MadridApplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MadridProtocol 的本地化字符串。
        /// </summary>
        internal static string MadridProtocol {
            get {
                return ResourceManager.GetString("MadridProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximun plus 1 的本地化字符串。
        /// </summary>
        internal static string MaxNumber {
            get {
                return ResourceManager.GetString("MaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Middle 的本地化字符串。
        /// </summary>
        internal static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not use 的本地化字符串。
        /// </summary>
        internal static string NotUse {
            get {
                return ResourceManager.GetString("NotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;office&gt; 的本地化字符串。
        /// </summary>
        internal static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online 的本地化字符串。
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can input one word in each textbox. 的本地化字符串。
        /// </summary>
        internal static string OnlyChar {
            get {
                return ResourceManager.GetString("OnlyChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out-In: 的本地化字符串。
        /// </summary>
        internal static string Out_In {
            get {
                return ResourceManager.GetString("Out_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OI 的本地化字符串。
        /// </summary>
        internal static string Out_In_Value {
            get {
                return ResourceManager.GetString("Out_In_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out-Out: 的本地化字符串。
        /// </summary>
        internal static string Out_Out {
            get {
                return ResourceManager.GetString("Out_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OO 的本地化字符串。
        /// </summary>
        internal static string Out_Out_Value {
            get {
                return ResourceManager.GetString("Out_Out_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paper 的本地化字符串。
        /// </summary>
        internal static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patent 的本地化字符串。
        /// </summary>
        internal static string Patent {
            get {
                return ResourceManager.GetString("Patent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patent type 的本地化字符串。
        /// </summary>
        internal static string PatentType {
            get {
                return ResourceManager.GetString("PatentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 place 的本地化字符串。
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  of the days past 的本地化字符串。
        /// </summary>
        internal static string RadioGroup_3_Text {
            get {
                return ResourceManager.GetString("RadioGroup_3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reg country or state 的本地化字符串。
        /// </summary>
        internal static string RegCountryOrState {
            get {
                return ResourceManager.GetString("RegCountryOrState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Related Client 的本地化字符串。
        /// </summary>
        internal static string RelatedClient {
            get {
                return ResourceManager.GetString("RelatedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of serial No. is more 50. 的本地化字符串。
        /// </summary>
        internal static string SerialNoIsTooLong {
            get {
                return ResourceManager.GetString("SerialNoIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direct applicate 的本地化字符串。
        /// </summary>
        internal static string SingleApplicate {
            get {
                return ResourceManager.GetString("SingleApplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agent Fee Discount 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid 的本地化字符串。
        /// </summary>
        internal static string sUnValid {
            get {
                return ResourceManager.GetString("sUnValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid 的本地化字符串。
        /// </summary>
        internal static string sValid {
            get {
                return ResourceManager.GetString("sValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished 的本地化字符串。
        /// </summary>
        internal static string TaskFinish {
            get {
                return ResourceManager.GetString("TaskFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discarded 的本地化字符串。
        /// </summary>
        internal static string TaskInvalid {
            get {
                return ResourceManager.GetString("TaskInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 place to the  的本地化字符串。
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trademark 的本地化字符串。
        /// </summary>
        internal static string Trademark {
            get {
                return ResourceManager.GetString("Trademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trademark Renewal Fee 的本地化字符串。
        /// </summary>
        internal static string TrademarkRenewalFee {
            get {
                return ResourceManager.GetString("TrademarkRenewalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trademark type 的本地化字符串。
        /// </summary>
        internal static string TrademarkType {
            get {
                return ResourceManager.GetString("TrademarkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type of bussiness type 的本地化字符串。
        /// </summary>
        internal static string TypeOfBussinessType {
            get {
                return ResourceManager.GetString("TypeOfBussinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnClosed 的本地化字符串。
        /// </summary>
        internal static string UnClose {
            get {
                return ResourceManager.GetString("UnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnHandled 的本地化字符串。
        /// </summary>
        internal static string Undeal {
            get {
                return ResourceManager.GetString("Undeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Week 的本地化字符串。
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
